/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_camel_case_types)]
#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
use libc::{nlmsghdr, proc_cn_event, proc_cn_mcast_op};
pub type exec_proc_event = proc_event__bindgen_ty_1_exec_proc_event;
pub type fork_proc_event = proc_event__bindgen_ty_1_fork_proc_event;
pub type exit_proc_event = proc_event__bindgen_ty_1_exit_proc_event;

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub type __u8 = ::std::os::raw::c_uchar;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
pub type __kernel_pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cb_id {
    pub idx: __u32,
    pub val: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cb_id"][::std::mem::size_of::<cb_id>() - 8usize];
    ["Alignment of cb_id"][::std::mem::align_of::<cb_id>() - 4usize];
    ["Offset of field: cb_id::idx"][::std::mem::offset_of!(cb_id, idx) - 0usize];
    ["Offset of field: cb_id::val"][::std::mem::offset_of!(cb_id, val) - 4usize];
};
#[repr(C)]
pub struct cn_msg {
    pub id: cb_id,
    pub seq: __u32,
    pub ack: __u32,
    pub len: __u16,
    pub flags: __u16,
    pub data: __IncompleteArrayField<__u8>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cn_msg"][::std::mem::size_of::<cn_msg>() - 20usize];
    ["Alignment of cn_msg"][::std::mem::align_of::<cn_msg>() - 4usize];
    ["Offset of field: cn_msg::id"][::std::mem::offset_of!(cn_msg, id) - 0usize];
    ["Offset of field: cn_msg::seq"][::std::mem::offset_of!(cn_msg, seq) - 8usize];
    ["Offset of field: cn_msg::ack"][::std::mem::offset_of!(cn_msg, ack) - 12usize];
    ["Offset of field: cn_msg::len"][::std::mem::offset_of!(cn_msg, len) - 16usize];
    ["Offset of field: cn_msg::flags"][::std::mem::offset_of!(cn_msg, flags) - 18usize];
    ["Offset of field: cn_msg::data"][::std::mem::offset_of!(cn_msg, data) - 20usize];
};
#[repr(C)]
pub struct proc_event {
    pub what: proc_cn_event,
    pub cpu: __u32,
    pub timestamp_ns: __u64,
    pub event_data: proc_event__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union proc_event__bindgen_ty_1 {
    pub ack: proc_event__bindgen_ty_1__bindgen_ty_1,
    pub fork: proc_event__bindgen_ty_1_fork_proc_event,
    pub exec: proc_event__bindgen_ty_1_exec_proc_event,
    pub id: proc_event__bindgen_ty_1_id_proc_event,
    pub sid: proc_event__bindgen_ty_1_sid_proc_event,
    pub ptrace: proc_event__bindgen_ty_1_ptrace_proc_event,
    pub comm: proc_event__bindgen_ty_1_comm_proc_event,
    pub coredump: proc_event__bindgen_ty_1_coredump_proc_event,
    pub exit: proc_event__bindgen_ty_1_exit_proc_event,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1__bindgen_ty_1 {
    pub err: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Alignment of proc_event__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1__bindgen_ty_1::err"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1__bindgen_ty_1, err) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_fork_proc_event {
    pub parent_pid: __kernel_pid_t,
    pub parent_tgid: __kernel_pid_t,
    pub child_pid: __kernel_pid_t,
    pub child_tgid: __kernel_pid_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_fork_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_fork_proc_event>() - 16usize];
    ["Alignment of proc_event__bindgen_ty_1_fork_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_fork_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_fork_proc_event::parent_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_fork_proc_event, parent_pid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_fork_proc_event::parent_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_fork_proc_event, parent_tgid) - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_fork_proc_event::child_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_fork_proc_event, child_pid) - 8usize];
    ["Offset of field: proc_event__bindgen_ty_1_fork_proc_event::child_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_fork_proc_event, child_tgid) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_exec_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_exec_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_exec_proc_event>() - 8usize];
    ["Alignment of proc_event__bindgen_ty_1_exec_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_exec_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_exec_proc_event::process_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exec_proc_event, process_pid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_exec_proc_event::process_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exec_proc_event, process_tgid) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_id_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub r: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1,
    pub e: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1 {
    pub ruid: __u32,
    pub rgid: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1>() - 4usize];
    ["Alignment of proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1::ruid"][::std::mem::offset_of!(
        proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1,
        ruid
    ) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1::rgid"][::std::mem::offset_of!(
        proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1,
        rgid
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2 {
    pub euid: __u32,
    pub egid: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2>() - 4usize];
    ["Alignment of proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2::euid"][::std::mem::offset_of!(
        proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2,
        euid
    ) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2::egid"][::std::mem::offset_of!(
        proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2,
        egid
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_id_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_id_proc_event>() - 16usize];
    ["Alignment of proc_event__bindgen_ty_1_id_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_id_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event::process_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_id_proc_event, process_pid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event::process_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_id_proc_event, process_tgid) - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event::r"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_id_proc_event, r) - 8usize];
    ["Offset of field: proc_event__bindgen_ty_1_id_proc_event::e"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_id_proc_event, e) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_sid_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_sid_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_sid_proc_event>() - 8usize];
    ["Alignment of proc_event__bindgen_ty_1_sid_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_sid_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_sid_proc_event::process_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_sid_proc_event, process_pid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_sid_proc_event::process_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_sid_proc_event, process_tgid) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_ptrace_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub tracer_pid: __kernel_pid_t,
    pub tracer_tgid: __kernel_pid_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_ptrace_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_ptrace_proc_event>() - 16usize];
    ["Alignment of proc_event__bindgen_ty_1_ptrace_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_ptrace_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_ptrace_proc_event::process_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_ptrace_proc_event, process_pid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_ptrace_proc_event::process_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_ptrace_proc_event, process_tgid) - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_ptrace_proc_event::tracer_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_ptrace_proc_event, tracer_pid) - 8usize];
    ["Offset of field: proc_event__bindgen_ty_1_ptrace_proc_event::tracer_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_ptrace_proc_event, tracer_tgid) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_comm_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub comm: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_comm_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_comm_proc_event>() - 24usize];
    ["Alignment of proc_event__bindgen_ty_1_comm_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_comm_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_comm_proc_event::process_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_comm_proc_event, process_pid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_comm_proc_event::process_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_comm_proc_event, process_tgid) - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_comm_proc_event::comm"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_comm_proc_event, comm) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_coredump_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub parent_pid: __kernel_pid_t,
    pub parent_tgid: __kernel_pid_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_coredump_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_coredump_proc_event>() - 16usize];
    ["Alignment of proc_event__bindgen_ty_1_coredump_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_coredump_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_coredump_proc_event::process_pid"][::std::mem::offset_of!(
        proc_event__bindgen_ty_1_coredump_proc_event,
        process_pid
    ) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_coredump_proc_event::process_tgid"][::std::mem::offset_of!(
        proc_event__bindgen_ty_1_coredump_proc_event,
        process_tgid
    ) - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_coredump_proc_event::parent_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_coredump_proc_event, parent_pid) - 8usize];
    ["Offset of field: proc_event__bindgen_ty_1_coredump_proc_event::parent_tgid"][::std::mem::offset_of!(
        proc_event__bindgen_ty_1_coredump_proc_event,
        parent_tgid
    ) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_exit_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub exit_code: __u32,
    pub exit_signal: __u32,
    pub parent_pid: __kernel_pid_t,
    pub parent_tgid: __kernel_pid_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1_exit_proc_event"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1_exit_proc_event>() - 24usize];
    ["Alignment of proc_event__bindgen_ty_1_exit_proc_event"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1_exit_proc_event>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_exit_proc_event::process_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exit_proc_event, process_pid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1_exit_proc_event::process_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exit_proc_event, process_tgid) - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1_exit_proc_event::exit_code"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exit_proc_event, exit_code) - 8usize];
    ["Offset of field: proc_event__bindgen_ty_1_exit_proc_event::exit_signal"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exit_proc_event, exit_signal) - 12usize];
    ["Offset of field: proc_event__bindgen_ty_1_exit_proc_event::parent_pid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exit_proc_event, parent_pid) - 16usize];
    ["Offset of field: proc_event__bindgen_ty_1_exit_proc_event::parent_tgid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1_exit_proc_event, parent_tgid) - 20usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event__bindgen_ty_1"]
        [::std::mem::size_of::<proc_event__bindgen_ty_1>() - 24usize];
    ["Alignment of proc_event__bindgen_ty_1"]
        [::std::mem::align_of::<proc_event__bindgen_ty_1>() - 4usize];
    ["Offset of field: proc_event__bindgen_ty_1::ack"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, ack) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::fork"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, fork) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::exec"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, exec) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::id"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, id) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::sid"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, sid) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::ptrace"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, ptrace) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::comm"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, comm) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::coredump"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, coredump) - 0usize];
    ["Offset of field: proc_event__bindgen_ty_1::exit"]
        [::std::mem::offset_of!(proc_event__bindgen_ty_1, exit) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of proc_event"][::std::mem::size_of::<proc_event>() - 40usize];
    ["Alignment of proc_event"][::std::mem::align_of::<proc_event>() - 8usize];
    ["Offset of field: proc_event::what"][::std::mem::offset_of!(proc_event, what) - 0usize];
    ["Offset of field: proc_event::cpu"][::std::mem::offset_of!(proc_event, cpu) - 4usize];
    ["Offset of field: proc_event::timestamp_ns"]
        [::std::mem::offset_of!(proc_event, timestamp_ns) - 8usize];
    ["Offset of field: proc_event::event_data"]
        [::std::mem::offset_of!(proc_event, event_data) - 16usize];
};
#[repr(C, packed)]
pub struct nlcn_subscribe_payload {
    pub cn_msg: cn_msg,
    pub cn_mcast: proc_cn_mcast_op,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nlcn_subscribe_payload"][::std::mem::size_of::<nlcn_subscribe_payload>() - 24usize];
    ["Alignment of nlcn_subscribe_payload"]
        [::std::mem::align_of::<nlcn_subscribe_payload>() - 1usize];
    ["Offset of field: nlcn_subscribe_payload::cn_msg"]
        [::std::mem::offset_of!(nlcn_subscribe_payload, cn_msg) - 0usize];
    ["Offset of field: nlcn_subscribe_payload::cn_mcast"]
        [::std::mem::offset_of!(nlcn_subscribe_payload, cn_mcast) - 20usize];
};
#[repr(C)]
pub struct nlcn_subscribe_msg {
    pub nl_hdr: nlmsghdr,
    pub payload: nlcn_subscribe_payload,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nlcn_subscribe_msg"][::std::mem::size_of::<nlcn_subscribe_msg>() - 40usize];
    ["Alignment of nlcn_subscribe_msg"][::std::mem::align_of::<nlcn_subscribe_msg>() - 4usize];
    ["Offset of field: nlcn_subscribe_msg::nl_hdr"]
        [::std::mem::offset_of!(nlcn_subscribe_msg, nl_hdr) - 0usize];
    ["Offset of field: nlcn_subscribe_msg::payload"]
        [::std::mem::offset_of!(nlcn_subscribe_msg, payload) - 16usize];
};
#[repr(C, packed)]
pub struct nlcn_event_payload {
    pub cn_msg: cn_msg,
    pub proc_ev: proc_event,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nlcn_event_payload"][::std::mem::size_of::<nlcn_event_payload>() - 60usize];
    ["Alignment of nlcn_event_payload"][::std::mem::align_of::<nlcn_event_payload>() - 1usize];
    ["Offset of field: nlcn_event_payload::cn_msg"]
        [::std::mem::offset_of!(nlcn_event_payload, cn_msg) - 0usize];
    ["Offset of field: nlcn_event_payload::proc_ev"]
        [::std::mem::offset_of!(nlcn_event_payload, proc_ev) - 20usize];
};
#[repr(C)]
pub struct nlcn_event_msg {
    pub nl_hdr: nlmsghdr,
    pub payload: nlcn_event_payload,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nlcn_event_msg"][::std::mem::size_of::<nlcn_event_msg>() - 76usize];
    ["Alignment of nlcn_event_msg"][::std::mem::align_of::<nlcn_event_msg>() - 4usize];
    ["Offset of field: nlcn_event_msg::nl_hdr"]
        [::std::mem::offset_of!(nlcn_event_msg, nl_hdr) - 0usize];
    ["Offset of field: nlcn_event_msg::payload"]
        [::std::mem::offset_of!(nlcn_event_msg, payload) - 16usize];
};
