[package]
name = "nym-wg-go"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ipnetwork.workspace = true
thiserror.workspace = true
tracing.workspace = true
hex.workspace = true
base64.workspace = true
x25519-dalek = { workspace = true, features = ["static_secrets"] }
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_NetworkManagement_Ndis"] }
