[package]
name = "nym-wg-go"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
amnezia = []

[dependencies]
ipnetwork.workspace = true
thiserror.workspace = true
tracing.workspace = true
typed-builder.workspace = true
hex.workspace = true
rand.workspace = true
nym-crypto.workspace = true
nym-wireguard-types.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_NetworkManagement_Ndis"] }
nym-windows.workspace = true
