version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "Bykow"
  - package-ecosystem: gradle
    directory: /nym-vpn-android
    schedule:
      interval: weekly
    assignees:
      - "zaneschepke"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: swift
    directory: /nym-vpn-apple
    schedule:
      interval: weekly
    assignees:
      - "rokas-ambrazevicius"
  - package-ecosystem: cargo
    directory: /nym-vpn-core
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "nym-*"
    assignees:
      - "octol"
      - "neacsu"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: npm
    directory: /nym-vpn-app
    schedule:
      interval: weekly
    assignees:
      - "doums"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: cargo
    directory: /nym-vpn-app/src-tauri
    schedule:
      interval: weekly
    assignees:
      - "doums"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
