version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "Bykow"
    milestone: 6
  - package-ecosystem: gradle
    directory: /nym-vpn-android
    assignees:
      - "mrkiwi"
    schedule:
      interval: weekly
    milestone: 6
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: swift
    directory: /nym-vpn-apple
    schedule:
      interval: weekly
    milestone: 6
    assignees:
      - "rokas-ambrazevicius"
  - package-ecosystem: cargo
    directory: /nym-vpn-core
    assignees:
      - "pronebird"
      - "neacsu"
    schedule:
      interval: weekly
    milestone: 6
    ignore:
      - dependency-name: "nym-*"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  # - package-ecosystem: cargo
  #   directory: /nym-vpn-app/src-tauri
  #   schedule:
  #     interval: weekly
  #   milestone: 6
  #   groups:
  #     patch-updates:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "patch"
  - package-ecosystem: npm
    directory: /nym-vpn-app
    schedule:
      interval: weekly
    milestone: 6
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
