---
# proto changes
"nym-vpn-core/crates/nym-vpn-proto/**":
  - rokas-ambrazevicius
  - neacsu
  - agentpietrucha
  - pronebird
  - mrkiwi
  - trojanfoe

# client app changes
"nym-vpn-app/*":
  - agentpietrucha
"nym-vpn-apple/*":
  - rokas-ambrazevicius
"nym-vpn-android/*":
  - mrkiwi
