---
# proto changes
"proto/**/*.proto":
  - rokas-ambrazevicius
  - neacsu
  - zaneschepke
  - doums
  - pronebird
  - octol

# uniffi changes
"nym-vpn-core/crates/nym-vpn-lib/uniffi/*":
  - zaneschepke
  - rokas-ambrazevicius
  - neacsu
  - pronebird
  - octol

# client app changes
"nym-vpn-app/*":
  - doums
"nym-vpn-apple/*":
  - rokas-ambrazevicius
"nym-vpn-android/*":
  - zaneschepke
