---
# core changes
"nym-vpn-core/**":
  - neacsu
  - pronebird
  - trojanfoe
# client app changes
"nym-vpn-app/**":
  - agentpietrucha
  - mrkiwi
"nym-vpn-apple/**":
  - agentpietrucha
  - mrkiwi
"nym-vpn-android/**":
  - mrkiwi
  - agentpietrucha
