appId: net.nymtech.nymvpn.mock.debug
---
- launchApp

- extendedWaitUntil:
    visible:
      text: "Connect"
    timeout: 15000

- tapOn: "Settings"

- assertVisible:
    text: "Account"
    index: 1

- assertVisible:
    text: "Passphrase"
    index: 1

- assertVisible: "Support & feedback"

- assertVisible:
    text: "Auto-connect"
    index: 0

- assertVisible:
    text: "Bypass LAN"
    index: 0

- assertVisible:
    text: "Kill switch"
    index: 1

- assertVisible:
    text: "Split tunneling"
    index: 1

- assertVisible:
    text: "Customize DNS"
    index: 1

- assertVisible:
    text: "Anti-censorship"
    index: 1

- scrollUntilVisible:
    element:
      text: "Daemon version: mock-1.0.0"
    direction: DOWN

- assertVisible:
    text: "Appearance"
    index: 1

- assertVisible:
    text: "Notifications"
    index: 1
  
- assertVisible:
    text: "Battery optimization"
    index: 1

- assertVisible:
    text: "App shortcuts"
    index: 0

- assertVisible:
    text: "Logs (stored locally)"
    index: 1

- assertVisible:
    text: "Data & Privacy"
    index: 1

- assertVisible: "Legal"

- assertVisible: "Quit NymVPN"

- assertVisible: "App version: v2.9.1-debug"
- assertVisible: "Daemon version: mock-1.0.0"
