appId: net.nymtech.nymvpn.mock.debug
---
- launchApp

- extendedWaitUntil:
    visible:
      text: "Connect"
    timeout: 15000

- tapOn:
    text: "Settings"

- assertVisible:
    text: "Settings"

- back

- assertVisible:
    text: "Connect"
