[package]
name = "nym-vpnd"
description = "NymVPN daemon"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["cgroup2"]
cgroup2 = ["nym-vpn-lib/cgroup2"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
time.workspace = true
tokio = { workspace = true, features = [
    "signal",
    "rt-multi-thread",
    "sync",
    "io-util",
    "net",
] }
tokio-stream.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tracing.workspace = true

nym-bin-common.workspace = true
nym-sdk.workspace = true

nym-ipc = { workspace = true, features = ["daemon"] }
nym-platform-metadata = { workspace = true, features = ["user-agent-macro"] }
nym-vpn-lib = { workspace = true }
nym-vpn-lib-types = { workspace = true, features = ["serde"] }
nym-vpn-network-config = { workspace = true }
nym-vpn-proto = { workspace = true, features = ["conversions"] }

[target.'cfg(windows)'.dependencies]
windows-service.workspace = true
eventlog.workspace = true

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_Security_Authorization",
    "Win32_Security_Authentication_Identity",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_Memory",
    "Win32_System_Threading",
]

[dev-dependencies]
pretty_assertions.workspace = true

[build-dependencies]
vergen-gitcl = { workspace = true, default-features = false, features = [
    "build",
    "cargo",
    "rustc",
] }

# Debian
[package.metadata.deb]
name = "nym-vpnd"
extended-description = '''NymVPN is a vpn service that uses the Nym mixnet.

This package contains the nym-vpnd daemon binary, which runs as a background service.

End-users should use either the CLI client, nym-vpnc, or the GUI client, nym-vpn-app.'''
maintainer-scripts = "linux/scripts"
recommends = "nym-vpnc"
depends = "$auto, adduser, policykit-1 | polkit | polkitd"
assets = [
    "$auto",
    { source = "target/release/nym-exclude", dest = "usr/bin/nym-exclude", mode = "755" },
    { source = "target/release/nym-socks5-proxy", dest = "usr/bin/nym-socks5-proxy", mode = "755" },
    { source = ".pkg/sysusers.d/nym-vpn.conf", dest = "usr/lib/sysusers.d/nym-vpn.conf", mode = "644" },
]
revision = ""

[package.metadata.deb.systemd-units]
unit-name = "nym-vpnd"
enable = true
start = true
restart-after-upgrade = false
stop-on-upgrade = true
unit-scripts = "linux/unit-scripts"

[package.metadata.cargo-machete]
ignored = ["vergen"]
