# private = { ignore = true }

accepted = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "GPL-3.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NOASSERTION",
    "OpenSSL",
    "Unicode-DFS-2016",
    "WTFPL",
]

workarounds = [
    "ring",
    "rustls",
]
