#!/usr/bin/env bash
# Copyright 2025 Mullvad VPN AB https://github.com/mullvad/mullvadvpn-app
# Copyright 2025 - Nym Technologies SA <contact@nymtech.net>
# SPDX-License-Identifier: GPL-3.0

# This is a logging tool for bash scripts

function log {
    local NO_COLOR="0m"
    local msg=$1
    local color=${2:-"$NO_COLOR"}
    echo -e "\033[$color$msg\033[$NO_COLOR"
}

function log_header {
    local YELLOW="33m"
    echo ""
    log "### $1 ###" $YELLOW
    echo ""
}

function log_success {
    local GREEN="32m"
    log "$1" $GREEN
}

function log_error {
    local RED="31m"
    log "!! $1" $RED
}

function log_info {
    local BOLD="1m"
    log "$1" $BOLD
}
