#!/usr/bin/env bash
# Copyright 2025 Mullvad VPN AB https://github.com/mullvad/mullvadvpn-app
# Copyright 2025 - Nym Technologies SA <contact@nymtech.net>
# SPDX-License-Identifier: GPL-3.0

# This is a small utility script that can be sourced to provide a function that prints its arguments
# and then calls them as a command, e.g. `print_and_run sleep 5`.

function print_and_run {
    echo "+ $*"
    "$@"
}
