[package]
name = "nym-gateway-probe"
build = "build.rs"
edition = "2021"

[workspace]


[dependencies]
tokio-util = "*"
tracing-subscriber = {version = "*", features = ["env-filter"]}
tracing = "*"
x25519-dalek = { version = "*", features = [
    "reusable_secrets",
    "static_secrets",
] }
anyhow = "*"
base64 = "*"
bincode = "*"
bs58 = "*"
bytes = "*"
clap = { version = "*", features = ["cargo", "derive"] }
cfg-if = "*"
dirs = "*"
dns-lookup = "*"
futures = "*"
hex = "*"
log = "*"
pnet_packet = "*"
rand = "*"
rust2go = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
thiserror = "*"
tokio = { version = "*", features = [
    "process",
    "rt-multi-thread",
    "fs",
    "sync",
    "macros",
] }


# nym monorepo
nym-authenticator-requests = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-client-core = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-crypto = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-config = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-wireguard-types = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-ip-packet-requests = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-sdk = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-task = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-topology = { git = "https://github.com/nymtech/nym.git", branch = "develop" }
nym-bin-common = { git = "https://github.com/nymtech/nym.git", branch = "develop" }

nym-authenticator-requests-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-authenticator-requests", branch = "release/2024.13-magura" }
nym-client-core-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-client-core", branch = "release/2024.13-magura" }
nym-crypto-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-crypto", branch = "release/2024.13-magura" }
nym-config-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-config", branch = "release/2024.13-magura" }
nym-wireguard-types-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-wireguard-types", branch = "release/2024.13-magura" }
nym-ip-packet-requests-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-ip-packet-requests", branch = "release/2024.13-magura" }
nym-sdk-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-sdk", branch = "release/2024.13-magura" }
nym-task-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-task", branch = "release/2024.13-magura" }
nym-topology-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-topology", branch = "release/2024.13-magura" }
nym-bin-common-magura = { git = "https://github.com/nymtech/nym.git", package = "nym-bin-common", branch = "release/2024.13-magura" }

# nym-vpn-client
nym-connection-monitor = { git = "https://github.com/nymtech/nym-vpn-client.git", branch = "main" }
nym-gateway-directory = { git = "https://github.com/nymtech/nym-vpn-client.git", branch = "main" }
nym-ip-packet-client = { git = "https://github.com/nymtech/nym-vpn-client.git", branch = "main" }
nym-authenticator-client = { git = "https://github.com/nymtech/nym-vpn-client.git", branch = "main" }

nym-connection-monitor-magura = { git = "https://github.com/nymtech/nym-vpn-client.git", package = "nym-connection-monitor", rev = "18e8d8f4ea72bdff001657034968b040ed9cf71a" }
nym-gateway-directory-magura = { git = "https://github.com/nymtech/nym-vpn-client.git", package = "nym-gateway-directory", rev = "18e8d8f4ea72bdff001657034968b040ed9cf71a" }
nym-ip-packet-client-magura = { git = "https://github.com/nymtech/nym-vpn-client.git", package = "nym-ip-packet-client", rev = "18e8d8f4ea72bdff001657034968b040ed9cf71a" }
nym-authenticator-client-magura = { git = "https://github.com/nymtech/nym-vpn-client.git", package = "nym-authenticator-client", rev = "18e8d8f4ea72bdff001657034968b040ed9cf71a" }



[build-dependencies]
vergen = { version = "*", default-features = false, features = [
    "build",
    "git",
    "gitcl",
    "rustc",
    "cargo",
] }

rust2go = { version = "*", features = ["build"] }
