[package]
name = "nym-vpnd-types"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
time.workspace = true
thiserror.workspace = true
zeroize.workspace = true

nym-vpn-lib.workspace = true
nym-vpn-lib-types.workspace = true
nym-validator-client.workspace = true
nym-vpn-network-config.workspace = true
nym-vpn-account-controller.workspace = true
