[package]
name = "nym-platform-metadata"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["network-manager"]
network-manager = ["dep:nym-dbus"]
user-agent-macro = ["dep:nym-sdk", "dep:nym-bin-common"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc2-foundation = { workspace = true, features = ["NSProcessInfo"] }

[target.'cfg(target_os = "linux")'.dependencies]
rs-release.workspace = true
nym-dbus = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
]

[dependencies]
sha2.workspace = true
sysinfo = { workspace = true, features = ["system"] }
nym-bin-common = { workspace = true, optional = true }
nym-sdk = { workspace = true, optional = true }
