#!/bin/bash

# NymVPN installer combo
#
# Install the following components:
# - daemon (nym-vpnd) as prebuilt binary
# - client (nymvpn-x) as AppImage
#
# To uninstall, run with `uninstall` as argument

set -E
set -o pipefail
# catch errors
trap 'catch $? ${FUNCNAME[0]:-main} $LINENO' ERR
cwd=$(pwd)

# ANSI style codes
RED="\e[38;5;1m" # red
GRN="\e[38;5;2m" # green
YLW="\e[38;5;3m" # yellow
GRY="\e[38;5;8m" # gray
BLD="\e[1m"      # bold
ITL="\e[3m"      # italic
RS="\e[0m"       # style reset
B_RED="$BLD$RED"
B_GRN="$BLD$GRN"
B_YLW="$BLD$YLW"
I_YLW="$ITL$YLW"
B_GRY="$BLD$GRY"
I_GRY="$ITL$GRY"
BI_YLW="$ITL$B_YLW"
BI_GRY="$ITL$B_GRY"
BI="$ITL$BLD"
####

# nymvpn-x AppImage
vpnx_tag=nym-vpn-x-v0.1.7
vpnx_version=0.1.7
appimage_url="https://github.com/nymtech/nym-vpn-client/releases/download/$vpnx_tag/nymvpn-x_${vpnx_version}.AppImage"

# nym-vpnd prebuilt binary
vpnd_tag=nym-vpn-core-v0.1.10
vpnd_version=0.1.10
vpnd_url="https://github.com/nymtech/nym-vpn-client/releases/download/$vpnd_tag/nym-vpn-core-v${vpnd_version}_linux_x86_64.tar.gz"

# function called when an error occurs, will print the exit
# status, function name and line number
catch() {
  log_e "$B_RED✗$RS unexpected error, [$BLD$1$RS] $BLD$2$RS L#$BLD$3$RS"
  cleanup
  cd "$cwd" || true
  exit 1
}

log() {
  echo -e "$1"
}

# log to stderr
log_e() {
  echo >&2 -e "$1"
}

# silent pushd that don't print the directory change
_pushd() {
  command pushd "$@" >/dev/null || exit 1
}

# silent popd that don't print the directory change
_popd() {
  command popd >/dev/null || exit 1
}

# check if a command exists
need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log_e " $B_RED⚠$RS need$BLD $1$RS (command not found)"
    exit 1
  fi
}

# replace the HOME directory with '~' in the given path
tilded() {
  echo "${1/#$HOME/\~}"
}

# check if a binary is in the PATH
# outputs 0 if found, 1 if not found
bin_in_path() {
  if which "$1" &>/dev/null; then
    log "${B_YLW}⚠$RS $1 is present in the system"
    echo 0
  fi
  echo 1
}

user_prompt() {
  # check if the script is running in a terminal, if not,
  # ie. piped into bash read from /dev/tty to get user input
  if [ -t 0 ]; then
    read -r -p "$(echo -e "$2")" "$1"
  else
    read -r -p "$(echo -e "$2")" "$1" </dev/tty
  fi
}

rmfile() {
  filename="$I_YLW${1/#$HOME/\~}$RS"
  if [ -f "$1" ]; then
    sudo rm -f "$1"
    log "    removed $filename"
  elif [ -d "$1" ]; then
    sudo rm -rf "$1"
    log "    removed $filename"
  fi
}

data_home=${XDG_DATA_HOME:-$HOME/.local/share}
state_home=${XDG_STATE_HOME:-$HOME/.local/state}
config_home=${XDG_CONFIG_HOME:-$HOME/.config}
cache_home=${XDG_CACHE_HOME:-$HOME/.cache}
xdg_bin_home="$HOME/.local/bin"
app_dir="nymvpn-x"
usr_bin_dir="/usr/bin"
# default installation directory
prefix_install="$HOME/.local"
install_dir="$xdg_bin_home"
icon_name="nymvpn-x.svg"
icons_dir="$data_home/icons"
desktop_dir="$data_home/applications"
appimage="nymvpn-x_${vpnx_version}.AppImage"
wrapper_sh="nymvpn-x-wrapper.sh"
target_appimage="nymvpn-x.appimage"
core_archive="nym-vpn-core-v${vpnd_version}_linux_x86_64.tar.gz"
vpnd_bin="nym-vpnd"
vpnd_service="nym-vpnd.service"
units_dir="/usr/lib/systemd/system"
os=$(uname -a)
# → to lowercase
os="${os,,}"

# components to install/uninstall
# 0 = to be (un)installed
_vpnd=1
_vpnx=1
# system packages to check
sys_pkgs=()

### desktop entry wrapper script ###
wrapper="#! /bin/bash

# fix an issue with NVIDIA gpu
# https://github.com/nymtech/nym-vpn-client/issues/305
export WEBKIT_DISABLE_DMABUF_RENDERER=1

LOG_FILE=1 RUST_LOG=info,nym_vpn_x=trace INSTALL_DIR/$target_appimage"
###

### desktop entry ###
desktop_entry="[Desktop Entry]
Name=NymVPN-x
Type=Application
Version=1.0
Comment=Decentralized, mixnet, and zero-knowledge VPN
Exec=INSTALL_DIR/$wrapper_sh %U
Icon=ICONS_DIR/$icon_name
Terminal=false
Categories=Network;"
###

### app icon ###
icon='<svg width="32" height="32" viewBox="0 0 32 32" fill="#FB6E4E" xmlns="http://www.w3.org/2000/svg"><path d="M3.7229 29.9997C-0.460546 26.7617 -1.23766 20.7391 2.0003 16.5557C5.23826 12.3722 11.2609 11.5951 15.4443 14.8331C19.6278 18.0711 20.4049 24.0937 17.1669 28.2771C13.9289 32.4605 7.90634 33.2377 3.7229 29.9997ZM28.0076 23.2647C33.3308 17.9415 33.3308 9.31561 28.0076 3.9924C22.6844 -1.3308 14.0455 -1.3308 8.73526 3.9924C3.42501 9.31561 3.41205 17.9415 8.73526 23.2647C14.0585 28.5879 22.6844 28.5879 28.0076 23.2647Z" fill="#FB6E4E"/></svg>'
###

### daemon service ###
service="[Unit]
Description=NymVPN daemon
StartLimitBurst=6
StartLimitIntervalSec=24
Wants=network-pre.target
After=network-pre.target NetworkManager.service systemd-resolved.service

[Service]
ExecStart=INSTALL_DIR/$vpnd_bin
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target"
###

# do not install/uninstall if system packages are installed
# ⚠ be sure to call `select_components` before this function
check_system_pkg() {
  case "$os" in
  *debian* | *ubuntu* | *mint*)
    for pkg in "${sys_pkgs[@]}"; do
      if dpkg-query -W "$pkg"; then
        log "${B_YLW}⚠$RS $pkg system package is installed, aborting…"
        exit 1
      fi
    done
    ;;
  *arch* | *manjaro* | *endeavour* | *garuda*)
    for pkg in "${sys_pkgs[@]}"; do
      if pacman -Qs "$pkg"; then
        log "${B_YLW}⚠$RS $pkg system package is installed, aborting…"
        exit 1
      fi
    done
    ;;
  *)
    return 0
    ;;
  esac
}

pre_check() {
  if [ -z "$vpnx_tag" ] || [ -z "$vpnx_version" ]; then
    log "${B_RED}✗$RS \`vpnx_tag\` and \`vpnx_version\` must be set"
    exit 1
  fi
  if [ -z "$vpnd_tag" ] || [ -z "$vpnd_version" ]; then
    log "${B_RED}✗$RS \`vpnd_tag\` and \`vpnd_version\` must be set"
    exit 1
  fi
}

select_components() {
  operation=${1:-install}
  choice=""
  log "  ${B_GRN}Select$RS the component(s) to $operation"
  prompt="    ${BI_YLW}N$RS vpnd and vpn-x combo (default)\n    ${BI_YLW}D$RS vpnd only\n    ${BI_YLW}X$RS vpn-x only\n(${BI_YLW}N$RS/${BI_YLW}D$RS/${BI_YLW}X$RS) "
  user_prompt choice "$prompt"

  case "$choice" in
  d | D)
    _vpnd=0
    sys_pkgs+=('nym-vpnd')
    ;;
  x | X)
    _vpnx=0
    sys_pkgs+=('nymvpn-x')
    ;;
  *)
    _vpnd=0
    _vpnx=0
    sys_pkgs+=('nym-vpnd' 'nymvpn-x')
    ;;
  esac
}

# Download `nymvpn-x` appimage
download_client() {
  _pushd "$temp_dir"
  log "  ${B_GRN}Downloading$RS $appimage"
  curl -fL -# "$appimage_url" -o $appimage
  log "  ${B_GRN}Downloading$RS $appimage.sha256sum"
  curl -fL -# "$appimage_url.sha256sum" -o "$appimage.sha256sum"
  log "  ${B_GRN}Checking$RS sha256sum"
  sha256sum --check --status "$appimage.sha256sum"
  _popd
}

# Download `nym-vpnd` prebuilt binary
download_daemon() {
  _pushd "$temp_dir"
  log "  ${B_GRN}Downloading$RS nym-vpnd archive"
  curl -fL -# "$vpnd_url" -o $core_archive
  log "  ${B_GRN}Downloading$RS archive sha256sum"
  curl -fL -# "$vpnd_url.sha256sum" -o "$core_archive.sha256sum"
  log "  ${B_GRN}Checking$RS sha256sum"
  sha256sum --check --status "$core_archive.sha256sum"
  log "  ${B_GRN}Unarchiving$RS nym-vpnd"
  tar -xzf "$core_archive"
  mv "${core_archive%.tar.gz}/$vpnd_bin" $vpnd_bin
  _popd
}

select_install_dir() {
  # prompt user for the installation directory
  # select between these 2 options
  # 1. ~/.local (default)
  # 2. /usr
  choice=""
  log "  ${B_GRN}Select$RS the install directory"
  prompt="    ${BI_YLW}H$RS ~/.local (default) or ${BI_YLW}U$RS /usr\n(${BI_YLW}H$RS/${BI_YLW}U$RS) "
  user_prompt choice "$prompt"

  if [ "$choice" = "u" ] || [ "$choice" = "U" ]; then
    prefix_install="/usr"
    install_dir="$usr_bin_dir"
    desktop_dir="/usr/share/applications"
    icons_dir="/usr/share/icons"
  else
    prefix_install="~/.local"
    install_dir="$xdg_bin_home"
    desktop_dir="$data_home/applications"
    icons_dir="$data_home/icons"
  fi
}

# checking if a directory is in the PATH
dir_in_path() {
  if [[ ":$PATH:" == *":$1:"* ]]; then
    return 0
  fi
  return 1
}

check_install_dir() {
  if ! dir_in_path "$xdg_bin_home"; then
    prefix_install="/usr"
    install_dir="$usr_bin_dir"
    desktop_dir="/usr/share/applications"
    icons_dir="/usr/share/icons"
    log "  ${B_GRN}Install$RS directory set to $prefix_install"
  else
    select_install_dir
    log "  ${B_GRN}Selected$RS install directory $prefix_install"
  fi
}

# check if a unit exists
# return 0 if found, 1 if not found
check_unit() {
  if systemctl status nym-vpnd &>/dev/null; then
    return 0
  else
    status=$?
    if [ $status -eq 4 ]; then
      # exit code 4 means the service is not found
      return 1
    fi
  fi
  # other exit code mean the service exists
  return 0
}

# check for existing installation presence
sanity_check() {
  log "  ${B_GRN}Checking$RS for existing installation"

  vpnd_in_path=$(bin_in_path $vpnd_bin)
  vpnx_in_path=$(bin_in_path $target_appimage)

  # check for any existing installation, if found cancel the script
  if [[ "$_vpnd" == 0 && $vpnd_in_path == 0 ]] ||
    [[ "$_vpnx" == 0 && $vpnx_in_path == 0 ]]; then
    log "  ${I_YLW}Please remove or cleanup any existing installation before running this script$RS"
    exit 1
  fi

  files_check=()
  if [ "$_vpnd" == 0 ]; then
    files_check+=("$install_dir/$vpnd_bin" "$units_dir/$vpnd_service")
  fi
  if [ "$_vpnx" == 0 ]; then
    files_check+=("$install_dir/$target_appimage" "$install_dir/$wrapper_sh" "$desktop_dir/nymvpn-x.desktop" "$icons_dir/$icon_name")
  fi

  for file in "${files_check[@]}"; do
    if [ -a "$file" ]; then
      log "${B_YLW}⚠$RS $file already exists"
      log "  ${I_YLW}Please remove or cleanup any existing installation before running this script$RS"
      exit 1
    fi
  done

  if [ "$_vpnd" == 0 ] && check_unit "nym_vpnd"; then
    log "  ${I_YLW}⚠$RS nym-vpnd unit service found on the system$RS"
    log "  ${I_YLW}Please remove or cleanup any existing installation before running this script$RS"
    exit 1
  fi
}

# prompt user to enable and start the service
start_service() {
  choice=""
  log "  ${B_GRN}Enable$RS and start nym-vpnd service?"
  prompt="    ${BI_YLW}Y${RS}es (recommended) ${BI_YLW}N${RS}o "
  user_prompt choice "$prompt"

  if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
    sudo systemctl enable $vpnd_service
    sudo systemctl start $vpnd_service
    log "   ${B_GRN}Enabled$RS and started nym-vpnd service"
  else
    log "   Run the following commands to enable and start the VPN service:
    ${I_YLW}sudo systemctl enable $vpnd_service$RS
    ${I_YLW}sudo systemctl start $vpnd_service$RS"
  fi
}

check_system_deps() {
  log "  ${B_GRN}Checking$RS for system dependencies"

  # this check only applies to the client for now
  # if client is not selected, skip it
  if [ "$_vpnx" != 0 ]; then
    return 0
  fi

  case "$os" in
  *ubuntu* | *debian*)
    # check for ubuntu version > 22.04 libfuse2 (needed for AppImage)
    fuse_output=$(dpkg --get-selections | grep fuse)
    if [[ "$fuse_output" != *"libfuse2"* ]]; then
      choice=""
      log "  ${B_GRN}Install$RS required package libfuse2?"
      prompt="    ${BI_YLW}Y${RS}es (recommended) ${BI_YLW}N${RS}o "
      user_prompt choice "$prompt"

      if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
        sudo apt install libfuse2
        log "   ${B_GRN}Installed$RS libfuse2"
      else
        log "   ${B_YLW}⚠$RS libfuse2 is required for the app to work, install it with:
        ${I_YLW}sudo apt install libfuse2$RS"
      fi
    fi
    ;;
  *arch* | *manjaro* | *endeavour* | *garuda*)
    # check if fuse2 is installed (needed for AppImage)
    if ! pacman -Qk fuse2 &>/dev/null; then
      choice=""
      log "  ${B_GRN}Install$RS required package fuse2?"
      user_prompt choice "    ${BI_YLW}Y${RS}es ${BI_YLW}N${RS}o "

      if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
        sudo pacman -S fuse2 --noconfirm
        log "   ${B_GRN}Installed$RS fuse2"
      else
        log "   ${B_YLW}⚠$RS fuse2 is required for the app to work, install it with:
        ${I_YLW}sudo pacman -S fuse2$RS"
      fi
    fi
    ;;
  *)
    return 0
    ;;
  esac
}

install_client() {
  log "  ${B_GRN}Installing$RS nymvpn-x.AppImage"
  _pushd "$temp_dir"
  echo "${wrapper/INSTALL_DIR/$install_dir}" >"$wrapper_sh"
  _popd

  if [ "$install_dir" = "$usr_bin_dir" ]; then
    log "  ${B_YLW}sudo$RS needed to install AppImage in $install_dir"
    sudo install -o "$(id -u)" -g "$(id -g)" -Dm755 "$temp_dir/$appimage" "$install_dir/$target_appimage"
    sudo install -o "$(id -u)" -g "$(id -g)" -Dm755 "$temp_dir/$wrapper_sh" "$install_dir/$wrapper_sh"
  else
    install -Dm755 "$temp_dir/$appimage" "$install_dir/$target_appimage"
    install -Dm755 "$temp_dir/$wrapper_sh" "$install_dir/$wrapper_sh"
  fi

  log "   ${B_GRN}Installed$RS $(tilded "$install_dir/$target_appimage")"
  log "   ${B_GRN}Installed$RS $(tilded "$install_dir/$wrapper_sh")"

  log "  ${B_GRN}Installing$RS desktop entry"
  _pushd "$temp_dir"
  echo "${desktop_entry/INSTALL_DIR/$install_dir}" >"nymvpn-x.desktop"
  sed -i "s|ICONS_DIR|$icons_dir|" "nymvpn-x.desktop"
  echo "$icon" >"$icon_name"
  _popd
  if [ "$install_dir" = "$usr_bin_dir" ]; then
    log "  ${B_YLW}sudo$RS needed to install desktop entry in $desktop_dir"
    sudo install -Dm644 "$temp_dir/nymvpn-x.desktop" "$desktop_dir/nymvpn-x.desktop"
    sudo install -Dm644 "$temp_dir/$icon_name" "$icons_dir/$icon_name"
  else
    install -Dm644 "$temp_dir/nymvpn-x.desktop" "$desktop_dir/nymvpn-x.desktop"
    install -Dm644 "$temp_dir/$icon_name" "$icons_dir/$icon_name"
  fi
  log "   ${B_GRN}Installed$RS $(tilded "$desktop_dir/nymvpn-x.desktop")"
  log "   ${B_GRN}Installed$RS $(tilded "$icons_dir/$icon_name")"
  install -Dm755 -d "$state_home/$app_dir"
}

install_daemon() {
  log "  ${B_GRN}Installing$RS nym-vpnd"
  if [ "$install_dir" = "$usr_bin_dir" ]; then
    log "  ${B_YLW}sudo$RS needed to install nym-vpnd in $install_dir"
    sudo install -o "$(id -u)" -g "$(id -g)" -Dm755 "$temp_dir/$vpnd_bin" "$install_dir/$vpnd_bin"
  else
    install -Dm755 "$temp_dir/$vpnd_bin" "$install_dir/$vpnd_bin"
  fi
  log "   ${B_GRN}Installed$RS $(tilded "$install_dir/$vpnd_bin")"

  log "  ${B_GRN}Installing$RS systemd service"
  _pushd "$temp_dir"
  echo "${service/INSTALL_DIR/$install_dir}" >"$vpnd_service"
  _popd
  log "  ${B_YLW}sudo$RS needed to install nym-vpnd.service in $units_dir"
  sudo install -Dm644 "$temp_dir/$vpnd_service" "$units_dir/$vpnd_service"
  log "   ${B_GRN}Installed$RS $(tilded "$units_dir/$vpnd_service")"
}

# try to remove a bunch of files or directories
# $1 the array of files
remove_file_set() {
  local -n _files=$1
  declare -a file_set

  # filter out files that don't exist
  for file in "${_files[@]}"; do
    if [ -a "$file" ]; then
      file_set+=("$file")
    fi
  done

  if [ "${#file_set[@]}" == 0 ]; then
    log "    ${ITL}No files found to remove$RS"
    return 0
  fi

  log "  Files to remove:"
  for file in "${file_set[@]}"; do
    log "    $I_YLW${file/#$HOME/\~}$RS"
  done

  choice=""
  log "  Proceed?"
  prompt="    ${BI_YLW}Y${RS}es ${BI_YLW}N${RS}o "
  user_prompt choice "$prompt"

  if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
    for file in "${file_set[@]}"; do
      rmfile "$file"
    done
  fi
}

uninstall_vpnd_service() {
  log "  ${B_GRN}Remove$RS nym-vpnd service?"

  choice=""
  prompt="    ${BI_YLW}Y${RS}es ${BI_YLW}N${RS}o "
  user_prompt choice "$prompt"

  if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
    log "  ${B_YLW}sudo$RS needed to stop and disable the service"
    if sudo systemctl stop nym-vpnd.service &>/dev/null; then
      log "   ${B_GRN}Stopped$RS nym-vpnd service"
    fi
    if sudo systemctl disable nym-vpnd.service &>/dev/null; then
      log "   ${B_GRN}Disabled$RS nym-vpnd service"
    fi
    rmfile /usr/lib/systemd/system/nym-vpnd.service
  fi
}

post_install() {
  if ! dir_in_path "$install_dir"; then
    log "${B_YLW}⚠$RS $install_dir is not in the ${BLD}PATH$RS
  please add it using your shell configuration"
  fi
}

cleanup() {
  rm -rf "$temp_dir"
}

_install() {
  log "$ITL${B_GRN}nym$RS${BI_GRY}VPN$RS ${BI}installer$RS\n"
  log "  nym-vpnd $ITL${B_YLW}$vpnd_version$RS ${I_GRY}daemon$RS"
  log "  nymvpn-x $ITL${B_YLW}$vpnx_version$RS ${I_GRY}client$RS\n"

  need_cmd mktemp
  temp_dir=$(mktemp -d)

  pre_check
  select_components
  check_system_pkg
  sanity_check
  check_system_deps
  check_install_dir
  [[ "$_vpnx" == 0 ]] && download_client
  [[ "$_vpnd" == 0 ]] && download_daemon
  [[ "$_vpnx" == 0 ]] && install_client
  if [ "$_vpnd" == 0 ]; then
    install_daemon
    start_service
  fi
  post_install
  cleanup

  log "\n${B_GRN}✓$RS"
}

_uninstall() {
  log "$ITL${B_GRN}nym$RS${BI_GRY}VPN$RS ${BI}uninstaller$RS\n"

  select_components uninstall
  check_system_pkg

  local files=()
  if [ "$_vpnd" == 0 ]; then
    files+=(
      "$xdg_bin_home/nym-vpnd"
      "/usr/bin/nym-vpnd"
    )
  fi
  if [ "$_vpnx" == 0 ]; then
    files+=(
      "$xdg_bin_home/nymvpn-x.appimage"
      "$xdg_bin_home/nymvpn-x-wrapper.sh"
      "$data_home/applications/nymvpn-x.desktop"
      "$data_home/icons/nymvpn-x.svg"
      "/usr/bin/nymvpn-x.appimage"
      "/usr/bin/nymvpn-x-wrapper.sh"
      /usr/share/applications/nymvpn-x.desktop
      /usr/share/icons/nymvpn-x.svg
    )
  fi

  log "  ${B_GRN}Removing$RS installed files"
  remove_file_set 'files'

  if [ "$_vpnx" == 0 ]; then
    log "  ${B_GRN}Remove$RS app config and cache files?"

    choice=""
    prompt="    ${BI_YLW}Y${RS}es ${BI_YLW}N${RS}o "
    user_prompt choice "$prompt"

    if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
      local app_dirs=(
        "$config_home/$app_dir"
        "$data_home/$app_dir"
        "$state_home/$app_dir"
        "$cache_home/$app_dir"
      )
      remove_file_set 'app_dirs'
    fi
  fi

  [[ "$_vpnd" == 0 ]] && uninstall_vpnd_service

  log "\n${B_GRN}✓$RS"
}

need_cmd uname
need_cmd install
need_cmd sudo
need_cmd sed
need_cmd curl
need_cmd tar
need_cmd sha256sum
need_cmd which
need_cmd grep

if [ "$1" == uninstall ]; then
  _uninstall
  exit 0
fi
_install
