[package]
name = "nym-gateway-directory"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-compression = { workspace = true, features = ["tokio", "gzip"] }
ipnetwork.workspace = true
itertools.workspace = true
nym-client-core.workspace = true
nym-http-api-client.workspace = true
nym-network-defaults.workspace = true
nym-offline-monitor.workspace = true
nym-sdk.workspace = true
nym-topology.workspace = true
nym-validator-client.workspace = true
nym-vpn-api-client = { workspace = true }
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
typed-builder.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
