[package]
name = "nym-vpn-lib"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
adblock = { workspace = true, features = ["embedded-domain-resolver"] }
anyhow.workspace = true
async-stream.workspace = true
async-compression = { workspace = true, features = ["tokio", "gzip"] }
async-trait.workspace = true
base64.workspace = true
bincode.workspace = true
bs58.workspace = true
bytes.workspace = true
ed25519-dalek = { workspace = true, features = [
    "pkcs8",
    "alloc",
    "pem",
    "rand_core",
] }
futures.workspace = true
geo.workspace = true
hex.workspace = true
hickory-resolver = { workspace = true, features = [
    "tokio",
    "tls-ring",
    "https-ring",
    "h3-ring",
    "quic-ring",
    "webpki-roots",
] }
hyper = { workspace = true, features = ["server", "http1"] }
hyper-util = { workspace = true, features = ["tokio"] }
http-body-util = { workspace = true }
ipnetwork.workspace = true
itertools.workspace = true
log-panics.workspace = true
lazy_static.workspace = true
nym-bandwidth-controller.workspace = true
nym-bin-common.workspace = true
nym-client-core.workspace = true
nym-config.workspace = true
nym-credentials-interface.workspace = true
nym-crypto.workspace = true
nym-http-api-client.workspace = true
nym-ip-packet-requests.workspace = true
nym-lp.workspace = true
nym-sdk.workspace = true
nym-validator-client.workspace = true
nym-wireguard-types.workspace = true
nym-apple-network.workspace = true
nym-authenticator-client.workspace = true
nym-common.workspace = true
nym-diagnostic.workspace = true
nym-platform-metadata = { workspace = true, features = ["user-agent-macro"] }
nym-connection-monitor.workspace = true
nym-gateway-directory.workspace = true
nym-ip-packet-client.workspace = true
nym-offline-monitor.workspace = true
nym-registration-client.workspace = true
nym-registration-common.workspace = true
nym-split-tunnel.workspace = true
nym-socks5-proxy-ipc.workspace = true
nym-statistics.workspace = true
nym-statistics-api-client.workspace = true
nym-vpn-api-client.workspace = true
nym-vpn-account-controller.workspace = true
nym-vpn-lib-types = { workspace = true, features = ["nym-type-conversions"] }
nym-vpn-network-config.workspace = true
nym-vpn-store.workspace = true
nym-wg-go = { workspace = true, features = ["amnezia"] }
nym-wg-metadata-client.workspace = true
nym-sqlx-pool-guard.workspace = true
nym-file-updater.workspace = true
nym-favorites.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
quinn.workspace = true
quinn-proto.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["socks", "rustls", "stream"] }
rustls = { workspace = true, default-features = false, features = [
    "std",
    "ring",
    "logging",
] }
serial_test.workspace = true
serde.workspace = true
serde_json.workspace = true
semver = { workspace = true }
sentry = { workspace = true, features = [
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
    "tracing",
    "logs",
] }
sha2.workspace = true
strum.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "sqlite"] }
sysinfo = { workspace = true, features = ["network"] }
toml.workspace = true
thiserror.workspace = true
time.workspace = true
tokio = { workspace = true, features = [
    "process",
    "rt-multi-thread",
    "fs",
    "sync",
] }
tokio-stream.workspace = true
tokio-util = { workspace = true, features = ["codec", "rt"] }
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "ansi",
    "json",
] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tun = { workspace = true, features = ["async"] }
url.workspace = true
urlencoding.workspace = true
webpki-roots.workspace = true
x509-parser = { workspace = true, features = ["verify"] }

# UNIX-specific dependencies
[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = [
    "socket",
    "net",
    "fs",
    "signal",
    "ioctl",
] }

# Linux-specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]
nym-dbus.workspace = true

# Windows-specific dependencies
[target.'cfg(windows)'.dependencies]
nym-windows.workspace = true
nym-routing.workspace = true
nym-dns.workspace = true
nym-firewall.workspace = true
nym-firewall-config.workspace = true
windows = { workspace = true, features = ["Win32_NetworkManagement_Ndis"] }
winreg.workspace = true

# Desktop-specific dependencies
[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
hickory-server = { workspace = true, features = ["resolver"] }
socket2.workspace = true
nym-routing.workspace = true
nym-dns.workspace = true
nym-cgroup.workspace = true
nym-firewall.workspace = true
nym-firewall-config.workspace = true

# Apple-specific dependencies
[target.'cfg(target_os = "macos")'.dependencies]
nym-macos.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
tracing-oslog.workspace = true

[target.'cfg(any(target_os = "ios"))'.dependencies]
hickory-server = { workspace = true, features = ["resolver"] }
socket2.workspace = true
libc.workspace = true
nym-dns.workspace = true
nym-firewall-config.workspace = true

# Android-specific dependencies
[target.'cfg(target_os = "android")'.dependencies]
hickory-proto.workspace = true
nym-socks5-proxy.workspace = true
pnet_packet.workspace = true
rand.workspace = true
tracing-android.workspace = true

# iOS-specific dependencies
[target.'cfg(target_os = "ios")'.dependencies]
debounced.workspace = true
dispatch2.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
socket2.workspace = true
tempfile.workspace = true
tracing-test.workspace = true

[build-dependencies]
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
vergen-gitcl = { workspace = true, default-features = false, features = [
    "build",
    "cargo",
    "rustc",
] }


[features]
default = ["cgroup2"]
metrics-server = ["nym-client-core/metrics-server"]
cgroup2 = ["nym-split-tunnel/cgroup2", "nym-firewall/cgroup2"]

[package.metadata.cargo-machete]
ignored = ["vergen"]
