package main

/*
// Generated by rust2go. Please DO NOT edit this C part manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct StringRef {
  const uint8_t *ptr;
  uintptr_t len;
} StringRef;

typedef struct ListRef {
  const void *ptr;
  uintptr_t len;
} ListRef;

typedef struct NetstackRequestGoRef {
  struct StringRef wg_ip;
  struct StringRef private_key;
  struct StringRef public_key;
  struct StringRef endpoint;
  struct StringRef dns;
  uint8_t ip_version;
  struct ListRef ping_hosts;
  struct ListRef ping_ips;
  uint8_t num_ping;
  uint64_t send_timeout_sec;
  uint64_t recv_timeout_sec;
  uint64_t download_timeout_sec;
  struct StringRef awg_args;
} NetstackRequestGoRef;

typedef struct NetstackResponseRef {
  bool can_handshake;
  uint16_t sent_ips;
  uint16_t received_ips;
  uint16_t sent_hosts;
  uint16_t received_hosts;
  bool can_resolve_dns;
  struct StringRef downloaded_file;
  uint64_t download_duration_sec;
  struct StringRef download_error;
} NetstackResponseRef;

// New retrieval function to bypass callback issues
extern struct NetstackResponseRef CNetstackCall_get_last_response();

// hack from: https://stackoverflow.com/a/69904977
__attribute__((weak))
inline void NetstackCall_ping_cb(const void *f_ptr, struct NetstackResponseRef resp, const void *slot) {
((void (*)(struct NetstackResponseRef, const void*))f_ptr)(resp, slot);
}
*/
import "C"
import (
	"log"
	"runtime"
	"sync"
	"unsafe"
)

// Global storage to keep strings alive during callbacks
var (
	stringStorage = make(map[uintptr][]byte)
	storageMutex  sync.Mutex
	storageID     uintptr = 1
)

var NetstackCallImpl NetstackCall

type NetstackCall interface {
	ping(req NetstackRequestGo) NetstackResponse
}

// Global variables to store the last response and its C strings
var lastResponse NetstackResponse
var lastResponseCStrings struct {
	downloaded_file *C.char
	download_error  *C.char
}

//export CNetstackCall_ping
func CNetstackCall_ping(req C.NetstackRequestGoRef, slot *C.void, cb *C.void) {
	log.Printf("[DEBUG] Starting CNetstackCall_ping")
	resp := NetstackCallImpl.ping(newNetstackRequestGo(req))
	log.Printf("[DEBUG] Ping function completed successfully, returning response")
	log.Printf("[DEBUG] Got response, creating refs")
	log.Printf("[DEBUG] Response downloaded_file length: %d", len(resp.downloaded_file))
	log.Printf("[DEBUG] Response download_error length: %d", len(resp.download_error))
	
	// Free any existing C strings
	if lastResponseCStrings.downloaded_file != nil {
		C.free(unsafe.Pointer(lastResponseCStrings.downloaded_file))
	}
	if lastResponseCStrings.download_error != nil {
		C.free(unsafe.Pointer(lastResponseCStrings.download_error))
	}
	
	// Store response globally and create C strings for it
	lastResponse = resp
	lastResponseCStrings.downloaded_file = C.CString(resp.downloaded_file)
	lastResponseCStrings.download_error = C.CString(resp.download_error)
	
	log.Printf("[DEBUG] Stored response globally with C strings, bypassing callback")
	
	// Don't call the callback at all - let Rust side retrieve via different mechanism
	// C.NetstackCall_ping_cb(unsafe.Pointer(cb), safe_resp, unsafe.Pointer(slot))
	
	runtime.KeepAlive(resp)
	log.Printf("[DEBUG] CNetstackCall_ping completed without callback")
}

//export CNetstackCall_get_last_response
func CNetstackCall_get_last_response() C.NetstackResponseRef {
	log.Printf("[DEBUG] Retrieving last response")
	
	// Create response ref using C strings (properly pinned memory)
	resp_ref := C.NetstackResponseRef{
		can_handshake: C.bool(lastResponse.can_handshake),
		sent_ips: C.uint16_t(lastResponse.sent_ips),
		received_ips: C.uint16_t(lastResponse.received_ips),
		sent_hosts: C.uint16_t(lastResponse.sent_hosts),
		received_hosts: C.uint16_t(lastResponse.received_hosts),
		can_resolve_dns: C.bool(lastResponse.can_resolve_dns),
		downloaded_file: C.StringRef{
			ptr: (*C.uint8_t)(unsafe.Pointer(lastResponseCStrings.downloaded_file)),
			len: C.uintptr_t(len(lastResponse.downloaded_file)),
		},
		download_duration_sec: C.uint64_t(lastResponse.download_duration_sec),
		download_error: C.StringRef{
			ptr: (*C.uint8_t)(unsafe.Pointer(lastResponseCStrings.download_error)),
			len: C.uintptr_t(len(lastResponse.download_error)),
		},
	}
	
	log.Printf("[DEBUG] Created response ref with C strings for retrieval")
	return resp_ref
}

func newString(s_ref C.StringRef) string {
	return unsafe.String((*byte)(unsafe.Pointer(s_ref.ptr)), s_ref.len)
}
func refString(s *string, buffer *[]byte) C.StringRef {
	// Test: provide a minimal string for empty cases to see if NULL pointers are the issue
	if s == nil || len(*s) == 0 {
		log.Printf("[DEBUG] refString: empty string, providing minimal placeholder")
		placeholder := []byte(" ") // Single space as placeholder
		storageMutex.Lock()
		id := storageID
		storageID++
		stringStorage[id] = placeholder
		stored_bytes := stringStorage[id]
		storageMutex.Unlock()
		
		return C.StringRef{
			ptr: (*C.uint8_t)(unsafe.Pointer(&stored_bytes[0])),
			len: C.uintptr_t(1),
		}
	}
	
	// For non-empty strings, store normally
	str_bytes := []byte(*s)
	storageMutex.Lock()
	id := storageID
	storageID++
	stringStorage[id] = str_bytes
	stored_bytes := stringStorage[id]
	storageMutex.Unlock()
	
	log.Printf("[DEBUG] refString: stored string len=%d in global storage id=%d", len(str_bytes), id)
	return C.StringRef{
		ptr: (*C.uint8_t)(unsafe.Pointer(&stored_bytes[0])),
		len: C.uintptr_t(len(stored_bytes)),
	}
}

func cntString(s *string, cnt *uint) [0]C.StringRef { 
	old_cnt := *cnt
	*cnt += uint(len(*s))
	log.Printf("[DEBUG] cntString: string len=%d, cnt: %d -> %d", len(*s), old_cnt, *cnt)
	return [0]C.StringRef{} 
}
func new_list_mapper[T1, T2 any](f func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		input := unsafe.Slice((*T1)(unsafe.Pointer(x.ptr)), x.len)
		output := make([]T2, len(input))
		for i, v := range input {
			output[i] = f(v)
		}
		return output
	}
}
func new_list_mapper_primitive[T1, T2 any](_ func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		return unsafe.Slice((*T2)(unsafe.Pointer(x.ptr)), x.len)
	}
}

// only handle non-primitive type T
func cnt_list_mapper[T, R any](f func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef {
		for _, v := range *s {
			f(&v, cnt)
		}
		*cnt += uint(len(*s)) * size_of[R]()
		return [0]C.ListRef{}
	}
}

// only handle primitive type T
func cnt_list_mapper_primitive[T, R any](_ func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef { return [0]C.ListRef{} }
}

// only handle non-primitive type T
func ref_list_mapper[T, R any](f func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*buffer) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(len(*s)),
			}
		}
		ret := C.ListRef{
			ptr: unsafe.Pointer(&(*buffer)[0]),
			len: C.uintptr_t(len(*s)),
		}
		children_bytes := int(size_of[R]()) * len(*s)
		children := (*buffer)[:children_bytes]
		*buffer = (*buffer)[children_bytes:]
		for _, v := range *s {
			child := f(&v, buffer)
			len := unsafe.Sizeof(child)
			copy(children, unsafe.Slice((*byte)(unsafe.Pointer(&child)), len))
			children = children[len:]
		}
		return ret
	}
}

// only handle primitive type T
func ref_list_mapper_primitive[T, R any](_ func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*s) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(0),
			}
		}
		return C.ListRef{
			ptr: unsafe.Pointer(&(*s)[0]),
			len: C.uintptr_t(len(*s)),
		}
	}
}
func size_of[T any]() uint {
	var t T
	return uint(unsafe.Sizeof(t))
}
func cvt_ref[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		buffer := make([]byte, cnt)
		return ref_f(p, &buffer), buffer
	}
}
func cvt_ref_cap[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR, add_cap uint) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		total_size := cnt + add_cap
		buffer := make([]byte, total_size)  // Make buffer with full size, not just capacity
		return ref_f(p, &buffer), buffer
	}
}

func newC_uint8_t(n C.uint8_t) uint8    { return uint8(n) }
func newC_uint16_t(n C.uint16_t) uint16 { return uint16(n) }
func newC_uint32_t(n C.uint32_t) uint32 { return uint32(n) }
func newC_uint64_t(n C.uint64_t) uint64 { return uint64(n) }
func newC_int8_t(n C.int8_t) int8       { return int8(n) }
func newC_int16_t(n C.int16_t) int16    { return int16(n) }
func newC_int32_t(n C.int32_t) int32    { return int32(n) }
func newC_int64_t(n C.int64_t) int64    { return int64(n) }
func newC_bool(n C.bool) bool           { return bool(n) }
func newC_uintptr_t(n C.uintptr_t) uint { return uint(n) }
func newC_intptr_t(n C.intptr_t) int    { return int(n) }
func newC_float(n C.float) float32      { return float32(n) }
func newC_double(n C.double) float64    { return float64(n) }

func cntC_uint8_t(_ *uint8, _ *uint) [0]C.uint8_t    { return [0]C.uint8_t{} }
func cntC_uint16_t(_ *uint16, _ *uint) [0]C.uint16_t { return [0]C.uint16_t{} }
func cntC_uint32_t(_ *uint32, _ *uint) [0]C.uint32_t { return [0]C.uint32_t{} }
func cntC_uint64_t(_ *uint64, _ *uint) [0]C.uint64_t { return [0]C.uint64_t{} }
func cntC_int8_t(_ *int8, _ *uint) [0]C.int8_t       { return [0]C.int8_t{} }
func cntC_int16_t(_ *int16, _ *uint) [0]C.int16_t    { return [0]C.int16_t{} }
func cntC_int32_t(_ *int32, _ *uint) [0]C.int32_t    { return [0]C.int32_t{} }
func cntC_int64_t(_ *int64, _ *uint) [0]C.int64_t    { return [0]C.int64_t{} }
func cntC_bool(_ *bool, _ *uint) [0]C.bool           { return [0]C.bool{} }
func cntC_uintptr_t(_ *uint, _ *uint) [0]C.uintptr_t { return [0]C.uintptr_t{} }
func cntC_intptr_t(_ *int, _ *uint) [0]C.intptr_t    { return [0]C.intptr_t{} }
func cntC_float(_ *float32, _ *uint) [0]C.float      { return [0]C.float{} }
func cntC_double(_ *float64, _ *uint) [0]C.double    { return [0]C.double{} }

func refC_uint8_t(p *uint8, _ *[]byte) C.uint8_t    { return C.uint8_t(*p) }
func refC_uint16_t(p *uint16, _ *[]byte) C.uint16_t { return C.uint16_t(*p) }
func refC_uint32_t(p *uint32, _ *[]byte) C.uint32_t { return C.uint32_t(*p) }
func refC_uint64_t(p *uint64, _ *[]byte) C.uint64_t { return C.uint64_t(*p) }
func refC_int8_t(p *int8, _ *[]byte) C.int8_t       { return C.int8_t(*p) }
func refC_int16_t(p *int16, _ *[]byte) C.int16_t    { return C.int16_t(*p) }
func refC_int32_t(p *int32, _ *[]byte) C.int32_t    { return C.int32_t(*p) }
func refC_int64_t(p *int64, _ *[]byte) C.int64_t    { return C.int64_t(*p) }
func refC_bool(p *bool, _ *[]byte) C.bool           { return C.bool(*p) }
func refC_uintptr_t(p *uint, _ *[]byte) C.uintptr_t { return C.uintptr_t(*p) }
func refC_intptr_t(p *int, _ *[]byte) C.intptr_t    { return C.intptr_t(*p) }
func refC_float(p *float32, _ *[]byte) C.float      { return C.float(*p) }
func refC_double(p *float64, _ *[]byte) C.double    { return C.double(*p) }

type NetstackRequestGo struct {
	wg_ip                string
	private_key          string
	public_key           string
	endpoint             string
	dns                  string
	ip_version           uint8
	ping_hosts           []string
	ping_ips             []string
	num_ping             uint8
	send_timeout_sec     uint64
	recv_timeout_sec     uint64
	download_timeout_sec uint64
	awg_args             string
}

func newNetstackRequestGo(p C.NetstackRequestGoRef) NetstackRequestGo {
	return NetstackRequestGo{
		wg_ip:                newString(p.wg_ip),
		private_key:          newString(p.private_key),
		public_key:           newString(p.public_key),
		endpoint:             newString(p.endpoint),
		dns:                  newString(p.dns),
		ip_version:           newC_uint8_t(p.ip_version),
		ping_hosts:           new_list_mapper(newString)(p.ping_hosts),
		ping_ips:             new_list_mapper(newString)(p.ping_ips),
		num_ping:             newC_uint8_t(p.num_ping),
		send_timeout_sec:     newC_uint64_t(p.send_timeout_sec),
		recv_timeout_sec:     newC_uint64_t(p.recv_timeout_sec),
		download_timeout_sec: newC_uint64_t(p.download_timeout_sec),
		awg_args:             newString(p.awg_args),
	}
}
func cntNetstackRequestGo(s *NetstackRequestGo, cnt *uint) [0]C.NetstackRequestGoRef {
	cnt_list_mapper(cntString)(&s.ping_hosts, cnt)
	cnt_list_mapper(cntString)(&s.ping_ips, cnt)
	return [0]C.NetstackRequestGoRef{}
}
func refNetstackRequestGo(p *NetstackRequestGo, buffer *[]byte) C.NetstackRequestGoRef {
	return C.NetstackRequestGoRef{
		wg_ip:                refString(&p.wg_ip, buffer),
		private_key:          refString(&p.private_key, buffer),
		public_key:           refString(&p.public_key, buffer),
		endpoint:             refString(&p.endpoint, buffer),
		dns:                  refString(&p.dns, buffer),
		ip_version:           refC_uint8_t(&p.ip_version, buffer),
		ping_hosts:           ref_list_mapper(refString)(&p.ping_hosts, buffer),
		ping_ips:             ref_list_mapper(refString)(&p.ping_ips, buffer),
		num_ping:             refC_uint8_t(&p.num_ping, buffer),
		send_timeout_sec:     refC_uint64_t(&p.send_timeout_sec, buffer),
		recv_timeout_sec:     refC_uint64_t(&p.recv_timeout_sec, buffer),
		download_timeout_sec: refC_uint64_t(&p.download_timeout_sec, buffer),
		awg_args:             refString(&p.awg_args, buffer),
	}
}

type NetstackResponse struct {
	can_handshake         bool
	sent_ips              uint16
	received_ips          uint16
	sent_hosts            uint16
	received_hosts        uint16
	can_resolve_dns       bool
	downloaded_file       string
	download_duration_sec uint64
	download_error        string
}

func newNetstackResponse(p C.NetstackResponseRef) NetstackResponse {
	return NetstackResponse{
		can_handshake:         newC_bool(p.can_handshake),
		sent_ips:              newC_uint16_t(p.sent_ips),
		received_ips:          newC_uint16_t(p.received_ips),
		sent_hosts:            newC_uint16_t(p.sent_hosts),
		received_hosts:        newC_uint16_t(p.received_hosts),
		can_resolve_dns:       newC_bool(p.can_resolve_dns),
		downloaded_file:       newString(p.downloaded_file),
		download_duration_sec: newC_uint64_t(p.download_duration_sec),
		download_error:        newString(p.download_error),
	}
}
func cntNetstackResponse(s *NetstackResponse, cnt *uint) [0]C.NetstackResponseRef {
	log.Printf("[DEBUG] cntNetstackResponse: downloaded_file='%s' (len=%d)", s.downloaded_file, len(s.downloaded_file))
	log.Printf("[DEBUG] cntNetstackResponse: download_error='%s' (len=%d)", s.download_error, len(s.download_error))
	cntString(&s.downloaded_file, cnt)
	cntString(&s.download_error, cnt)
	return [0]C.NetstackResponseRef{}
}
func refNetstackResponse(p *NetstackResponse, buffer *[]byte) C.NetstackResponseRef {
	return C.NetstackResponseRef{
		can_handshake:         refC_bool(&p.can_handshake, buffer),
		sent_ips:              refC_uint16_t(&p.sent_ips, buffer),
		received_ips:          refC_uint16_t(&p.received_ips, buffer),
		sent_hosts:            refC_uint16_t(&p.sent_hosts, buffer),
		received_hosts:        refC_uint16_t(&p.received_hosts, buffer),
		can_resolve_dns:       refC_bool(&p.can_resolve_dns, buffer),
		downloaded_file:       refString(&p.downloaded_file, buffer),
		download_duration_sec: refC_uint64_t(&p.download_duration_sec, buffer),
		download_error:        refString(&p.download_error, buffer),
	}
}
func main() {}

