[package]
name = "nym-ipc-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
hyper-util.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, features = ["net"] }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation"] }


