# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

platform :mac do
  desc "Bump version"
  lane :bump_version do
    app_version = ARGV[2]

    puts "App version to set: #{app_version}"

    if app_version.nil? || app_version.strip.empty?
      UI.user_error!("App version is missing. Please provide an app version, e.g., 'fastlane mac bump_version 1.3'")
    end

    project_path = '../NymVPN.xcodeproj'
    project = Xcodeproj::Project.open(project_path)

    allowTargets = ["NymVPN", "NymMixnetTunnel", "NymVPNDaemon", "NymVPND"]

    project.targets.each do |projectTarget|
      if allowTargets.include?(projectTarget.name)
        projectTarget.build_configurations.each do |configuration|
          configuration.build_settings["MARKETING_VERSION"] = app_version
        end
      end
    end

    project.save
  end

  desc "Bump build"
  lane :bump_build do |options|
    # Optionally passed build number (string or int)
    provided_build = options[:build].to_i if options[:build]

    project_path = '../NymVPN.xcodeproj'
    project = Xcodeproj::Project.open(project_path)

    allowTargets = ["NymVPN", "NymMixnetTunnel", "NymVPNDaemon", "NymVPND"]

    project.targets.each do |projectTarget|
      next unless allowTargets.include?(projectTarget.name)

      projectTarget.build_configurations.each do |configuration|
        current = configuration.build_settings["CURRENT_PROJECT_VERSION"].to_i
        new_build = provided_build && provided_build > 0 ? provided_build : (current + 1)

        configuration.build_settings["CURRENT_PROJECT_VERSION"] = new_build.to_s
        UI.message("✅ #{projectTarget.name}: #{current} → #{new_build}")
      end
    end

    project.save
  end
end
