[package]
name = "nym-vpn-lib-uniffi"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
cfg-if.workspace = true
ipnetwork.workspace = true
itertools.workspace = true
sentry = { workspace = true, features = [
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
    "tracing",
    "logs",
] }
time.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true, features = ["codec", "rt"] }
tracing.workspace = true
serde_json.workspace = true
uniffi = { workspace = true, features = ["tokio"] }
nym-bandwidth-controller = { workspace = true }
nym-sdk.workspace = true
nym-offline-monitor.workspace = true
nym-diagnostic.workspace = true
nym-vpn-lib.workspace = true
nym-vpn-lib-types = { workspace = true, features = [
    "uniffi-bindings",
    "nym-type-conversions",
    "serde",
] }
nym-vpn-account-controller.workspace = true
nym-vpn-network-config.workspace = true
nym-vpn-store.workspace = true
nym-vpn-api-client.workspace = true
nym-http-api-client.workspace = true
nym-common.workspace = true
nym-gateway-directory.workspace = true
nym-platform-metadata = { workspace = true, features = ["user-agent-macro"] }
nym-favorites.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
futures.workspace = true
nym-vpn-proto = { workspace = true, features = ["rpc_client"] }

[target.'cfg(target_os = "android")'.dependencies]
iprange.workspace = true
ipnet.workspace = true
jni.workspace = true
log.workspace = true
ndk-context.workspace = true
rand.workspace = true
tracing-android.workspace = true
nym-firewall-config.workspace = true
webpki-roots.workspace = true
rustls = { workspace = true, default-features = false, features = [
    "ring",
    "std",
] }
inventory.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
vergen-gitcl = { workspace = true, default-features = false, features = [
    "build",
    "cargo",
    "rustc",
] }

[package.metadata.cargo-machete]
ignored = ["vergen"]
