[package]
name = "nym-vpn-lib-uniffi"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
ipnetwork.workspace = true
itertools.workspace = true
lazy_static.workspace = true
sysinfo.workspace = true
sentry = { workspace = true, features = [
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
    "tracing",
    "logs",
] }
time.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true, features = ["codec", "rt"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
uniffi = { workspace = true, features = ["tokio"] }

nym-bin-common.workspace = true
nym-sdk.workspace = true
nym-statistics.workspace = true
nym-statistics-api-client.workspace = true
nym-offline-monitor.workspace = true
nym-vpn-lib.workspace = true
nym-vpn-lib-types = { workspace = true, features = [
    "uniffi-bindings",
    "nym-type-conversions",
] }
nym-vpn-account-controller.workspace = true
nym-vpn-network-config.workspace = true
nym-vpn-store.workspace = true
nym-vpn-api-client.workspace = true
nym-http-api-client.workspace = true
nym-common.workspace = true
nym-gateway-directory.workspace = true
nym-platform-metadata.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
nym-vpn-proto = { workspace = true, features = ["rpc_client"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
tracing-oslog.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android_logger.workspace = true
log.workspace = true
rand.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
vergen-gitcl = { workspace = true, default-features = false, features = [
    "build",
    "cargo",
    "rustc",
] }

[package.metadata.cargo-machete]
ignored = ["vergen"]
