[package]
name = "nym-statistics"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
nym-bin-common.workspace = true
nym-vpn-lib-types.workspace = true
nym-statistics-api-client.workspace = true
nym-statistics-common.workspace = true

futures.workspace = true
rand.workspace = true
strum = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = [
    "runtime-tokio-rustls",
    "sqlite",
    "time",
] }
nym-sqlx-pool-guard.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros"] }
tokio-util.workspace = true
time.workspace = true
tracing.workspace = true

[build-dependencies]
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
