[package]
name = "nym-vpn-proto"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
hyper = { workspace = true }
prost-types.workspace = true
prost.workspace = true
serde_json = { workspace = true, optional = true }
tonic-prost.workspace = true
tonic.workspace = true
tokio-stream = { workspace = true, optional = true, features = ["net"] }
tower = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
time = { workspace = true, optional = true, features = ["parsing"] }
nym-vpn-lib-types = { workspace = true, optional = true, features = ["serde"] }
nym-ipc = { workspace = true, optional = true }
nym-network-defaults = { workspace = true, optional = true }

[build-dependencies]
tonic-prost-build.workspace = true

[features]
default = []
conversions = [
    "dep:nym-vpn-lib-types",
    "dep:nym-network-defaults",
    "dep:thiserror",
    "dep:time",
    "dep:serde_json",
]
rpc_client = [
    "conversions",
    "dep:nym-vpn-lib-types",
    "dep:nym-ipc",
    "dep:thiserror",
    "dep:tokio-stream",
    "dep:tower",
    "dep:time",
]

[package.metadata.cargo-machete]
ignored = ["tonic-prost"]
