package net.nymtech.billing.model

enum class BillingCode {
	OK,
	USER_CANCELED,
	SERVICE_UNAVAILABLE,
	BILLING_UNAVAILABLE,
	ITEM_UNAVAILABLE,
	DEVELOPER_ERROR,
	ERROR,
	ITEM_ALREADY_OWNED,
	ITEM_NOT_OWNED,
	FEATURE_NOT_SUPPORTED,
	SERVICE_DISCONNECTED,
	NETWORK_ERROR,
	UNKNOWN,
}
