[package]
name = "test-rpc"
description = "Supports IPC between test-runner and test-manager"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-rustls = { workspace = true, features = [
    "logging",
    "webpki-roots",
    "http1",
    "ring",
] }
hyper-util = { workspace = true }
log = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tarpc = { workspace = true, features = ["tokio1", "serde-transport", "serde1"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "rt"] }
tokio-rustls = { workspace = true }
tokio-serde = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
webpki-roots = { workspace = true }
