[package]
name = "nym-offline"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
futures.workspace = true
tokio.workspace = true
debounced.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
windows-sys = { workspace = true, features = [
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }

nym-common = { path = "../nym-common" }
nym-routing = { path = "../nym-routing" }
nym-windows = { path = "../nym-windows" }
nym-apple-dispatch = { path = "../nym-apple-dispatch" }
nym-apple-network = { path = "../nym-apple-network" }
