[package]
name = "nym-routing"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true }
ipnetwork = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = [
    "process",
    "rt-multi-thread",
    "net",
    "io-util",
    "time",
] }

[target.'cfg(not(target_os="android"))'.dependencies]
nym-common = { path = "../nym-common" }

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
netlink-packet-route = { version = "0.17", features = ["rich_nlas"] }
netlink-sys = "0.8.3"
rtnetlink = "0.11"

[target.'cfg(target_os = "macos")'.dependencies]
bitflags = "2"
libc.workspace = true
nix = { version = "0.28", features = ["socket", "fs", "net"] }
system-configuration.workspace = true


[target.'cfg(windows)'.dependencies]
nym-windows = { path = "../nym-windows" }
widestring = "1.0"

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = ["Win32_NetworkManagement_Ndis", "Win32_Globalization"]

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
