[package]
name = "nym-id-fork"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
zeroize.workspace = true

nym-credential-storage-fork = { path = "../nym-credential-storage-fork" }
nym-credentials-fork = { path = "../nym-credentials-fork" }
