default_platform(:android)

# Google Play supported metadata locales
# https://support.google.com/googleplay/android-developer/table/4419860?hl=en

platform :android do

	desc 'Deploy an internal version to Google Play'
	lane :internal do |options|
		gradle(task: "clean bundleGeneralRelease", project_dir: "nym-vpn-android/")
		skip_bundle = options[:skip_bundle]
		skip_metadata = options[:skip_metadata]
		upload_to_play_store(track: 'internal', skip_upload_apk: true, skip_upload_aab: skip_bundle, skip_upload_metadata: skip_metadata, skip_upload_changelogs: skip_metadata)
	end

	desc "Deploy an alpha version to Google Play"
	lane :alpha do |options|
		gradle(task: "clean bundleGeneralRelease", project_dir: "nym-vpn-android/")
		skip_bundle = options[:skip_bundle]
		skip_metadata = options[:skip_metadata]
		upload_to_play_store(track: 'alpha', skip_upload_apk: true, skip_upload_aab: skip_bundle, skip_upload_metadata: skip_metadata, skip_upload_changelogs: skip_metadata)
	end

	desc "Deploy a beta version to Google Play"
	lane :beta do |options|
		gradle(task: "clean bundleGeneralRelease", project_dir: "nym-vpn-android/")
		skip_bundle = options[:skip_bundle]
		skip_metadata = options[:skip_metadata]
		upload_to_play_store(track: 'beta', skip_upload_apk: true, skip_upload_aab: skip_bundle, skip_upload_metadata: skip_metadata, skip_upload_changelogs: skip_metadata)
	end

	desc "Deploy a production version to Google Play"
	lane :production do |options|
		gradle(task: "clean bundleGeneralRelease", project_dir: "nym-vpn-android/")
		skip_bundle = options[:skip_bundle]
		skip_metadata = options[:skip_metadata]
		upload_to_play_store(track: 'production', skip_upload_apk: true, skip_upload_aab: skip_bundle, skip_upload_metadata: skip_metadata, skip_upload_changelogs: skip_metadata)
	end
end

