package net.nymtech.nymvpn.ui.screens.settings

data class SettingsActions(
	val onGetStartedClick: () -> Unit = {},
	val onAccountClick: () -> Unit = {},
	val onPassphraseClick: () -> Unit = {},
	val onSupportClick: () -> Unit = {},
	val onLegalClick: () -> Unit = {},
	val onQuitClick: () -> Unit = {},
	val onLogoutClick: () -> Unit = {},
	val onAppVersionClick: () -> Unit = {},
	val onSplitTunnelingClick: () -> Unit = {},
	val onAutoConnectEnable: (enabled: Boolean) -> Unit = {},
	val onBypassLanEnable: (enabled: Boolean) -> Unit = {},
	val onAdBlockingEnable: (enabled: Boolean) -> Unit = {},
	val onKillSwitchClick: () -> Unit = {},
	val onCensorshipClick: () -> Unit = {},
	val onDnsClick: () -> Unit = {},
	val onAppearanceClick: () -> Unit = {},
	val onPrivacyClick: () -> Unit = {},
	val onNotificationsClick: () -> Unit = {},
	val onBatterySettingsClick: () -> Unit = {},
	val onShortcutsEnable: (enabled: Boolean) -> Unit = {},
	val onMixnetTuningClick: () -> Unit = {},
	val onGeoExclusionClick: () -> Unit = {},
)
