package net.nymtech.nymvpn.ui.screens.settings

data class SettingsActions(
	val onLoginClick: () -> Unit = {},
	val onAccountClick: () -> Unit = {},
	val onPassphraseClick: () -> Unit = {},
	val onSupportClick: () -> Unit = {},
	val onResetClick: () -> Unit = {},
	val onLegalClick: () -> Unit = {},
	val onSystemStatusClick: () -> Unit = {},
	val onLogoutClick: () -> Unit = {},
	val onQuitClick: () -> Unit = {},
	val onAppVersionClick: () -> Unit = {},
	val onSplitTunnelingClick: () -> Unit = {},
	val onAutoConnectEnable: (enabled: Boolean) -> Unit = {},
	val onBypassLanEnable: (enabled: Boolean) -> Unit = {},
	val onSupportIPv6Enable: (enabled: Boolean) -> Unit = {},
	val onAutoselectServerEnable: (enabled: Boolean) -> Unit = {},
	val onKillSwitchClick: () -> Unit = {},
	val onCensorshipClick: () -> Unit = {},
	val onAppearanceClick: () -> Unit = {},
	val onPrivacyClick: () -> Unit = {},
	val onLogsClick: () -> Unit = {},
	val onNotificationsClick: () -> Unit = {},
	val onBatterySettingsClick: () -> Unit = {},
	val onShortcutsEnable: (enabled: Boolean) -> Unit = {},
	val onDeviceStartupEnable: (enabled: Boolean) -> Unit = {},
	val onSystemTrayEnable: (enabled: Boolean) -> Unit = {},
)
