default_platform(:android)

platform :android do

  desc 'Deploy an internal version to Google Play'
  lane :internal do
    gradle(task: "clean bundleGeneralRelease")
    upload_to_play_store(track: 'internal', skip_upload_apk: true, skip_upload_metadata: true)
  end

  desc "Deploy an alpha version to Google Play"
    lane :alpha do
      gradle(task: "clean bundleGeneralRelease")
      upload_to_play_store(track: 'alpha', skip_upload_apk: true, skip_upload_metadata: true)
  end

  desc "Deploy a beta version to Google Play"
  lane :beta do
    gradle(task: "clean bundleGeneralRelease")
    upload_to_play_store(track: 'beta', skip_upload_apk: true, skip_upload_metadata: true)
  end

  desc "Deploy a production version to Google Play"
    lane :production do
      gradle(task: "clean bundleGeneralRelease")
      upload_to_play_store(track: 'production', skip_upload_apk: true, skip_upload_metadata: true)
  end

  desc "Deploy metadata to Google Play"
      lane :metadata do
        upload_to_play_store(skip_upload_apk: true, skip_upload_aab: true)
  end

end
