[target.aarch64-linux-android]
rustflags = ["-L", "./android/app/build/extraJni/arm64-v8a"]
[target.x86_64-linux-android]
rustflags = ["-L", "./android/app/build/extraJni/x86_64"]
[target.armv7-linux-androideabi]
rustflags = ["-L", "./android/app/build/extraJni/armeabi-v7a"]
[target.i686-linux-android]
rustflags = ["-L", "./android/app/build/extraJni/x86"]
[target.aarch64-apple-ios]
rustflags = ["-L", "./build/lib/universal-apple-darwin"]
[target.x86_64-apple-ios]
rustflags = ["-L", "./build/lib/universal-apple-darwin"]
[target.aarch64-apple-ios-sim]
rustflags = ["-L", "./build/lib/universal-apple-darwin"]
