[package]
name = "nym-statistics-api-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
nym-statistics-common.workspace = true
nym-http-api-client.workspace = true
serde = { workspace = true, features = ["derive"] }

thiserror.workspace = true
url.workspace = true
