[package]
name = "nym-ipc"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
thiserror.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, features = ["net"] }
tokio-util.workspace = true
tracing.workspace = true
tonic.workspace = true

nym-ipc-client.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
nix.workspace = true
zbus.workspace = true
zbus_polkit.workspace = true


[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation"] }
nym-windows.workspace = true

[features]
authentication = []
