[package]
name = "nym-ipc"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-stream = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
hyper-util = { workspace = true, features = ["tokio"] }
thiserror = { workspace = true, optional = true }
tokio = { workspace = true, features = ["io-util"] }
tokio-stream = { workspace = true, features = ["net"] }
tokio-util = { workspace = true }
tracing.workspace = true
tonic = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { workspace = true, optional = true }
zbus = { workspace = true, optional = true }
zbus_polkit = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = { workspace = true }
objc2 = { workspace = true }
objc2-core-foundation = { workspace = true, features = ["CFString"] }
objc2-foundation = { workspace = true, features = [
    "NSString",
    "NSXPCConnection",
] }
objc2-security = { workspace = true, features = ["CSCommon", "SecCode"] }


[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation"] }
nym-windows = { workspace = true, optional = true }

[dev-dependencies]
strum.workspace = true

[build-dependencies]
cc = { workspace = true }

[features]
xpc = []
daemon = [
    "async-stream",
    "async-trait",
    "nix",
    "nym-windows",
    "thiserror",
    "zbus",
    "zbus_polkit",
]
