//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: health.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Health is gRPC's mechanism for checking whether a server is able to handle
/// RPCs. Its semantics are documented in
/// https://github.com/grpc/grpc/blob/master/doc/health-checking.md.
///
/// Usage: instantiate `Grpc_Health_V1_HealthClient`, then call methods of this protocol to make API calls.
internal protocol Grpc_Health_V1_HealthClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol? { get }

  func check(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>

  func watch(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions?,
    handler: @escaping (Grpc_Health_V1_HealthCheckResponse) -> Void
  ) -> ServerStreamingCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>
}

extension Grpc_Health_V1_HealthClientProtocol {
  internal var serviceName: String {
    return "grpc.health.v1.Health"
  }

  /// Check gets the health of the specified service. If the requested service
  /// is unknown, the call will fail with status NOT_FOUND. If the caller does
  /// not specify a service name, the server should respond with its overall
  /// health status.
  ///
  /// Clients should set a deadline when calling Check, and can declare the
  /// server unhealthy if they do not receive a timely response.
  ///
  /// Check implementations should be idempotent and side effect free.
  ///
  /// - Parameters:
  ///   - request: Request to send to Check.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func check(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse> {
    return self.makeUnaryCall(
      path: Grpc_Health_V1_HealthClientMetadata.Methods.check.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckInterceptors() ?? []
    )
  }

  /// Performs a watch for the serving status of the requested service.
  /// The server will immediately send back a message indicating the current
  /// serving status.  It will then subsequently send a new message whenever
  /// the service's serving status changes.
  ///
  /// If the requested service is unknown when the call is received, the
  /// server will send a message setting the serving status to
  /// SERVICE_UNKNOWN but will *not* terminate the call.  If at some
  /// future point, the serving status of the service becomes known, the
  /// server will send a new message with the service's serving status.
  ///
  /// If the call terminates with status UNIMPLEMENTED, then clients
  /// should assume this method is not supported and should not retry the
  /// call.  If the call terminates with any other status (including OK),
  /// clients should retry the call with appropriate exponential backoff.
  ///
  /// - Parameters:
  ///   - request: Request to send to Watch.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func watch(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Grpc_Health_V1_HealthCheckResponse) -> Void
  ) -> ServerStreamingCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse> {
    return self.makeServerStreamingCall(
      path: Grpc_Health_V1_HealthClientMetadata.Methods.watch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Grpc_Health_V1_HealthClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Grpc_Health_V1_HealthNIOClient")
internal final class Grpc_Health_V1_HealthClient: Grpc_Health_V1_HealthClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the grpc.health.v1.Health service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Grpc_Health_V1_HealthNIOClient: Grpc_Health_V1_HealthClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol?

  /// Creates a client for the grpc.health.v1.Health service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Health is gRPC's mechanism for checking whether a server is able to handle
/// RPCs. Its semantics are documented in
/// https://github.com/grpc/grpc/blob/master/doc/health-checking.md.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Grpc_Health_V1_HealthAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol? { get }

  func makeCheckCall(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>

  func makeWatchCall(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Grpc_Health_V1_HealthAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Grpc_Health_V1_HealthClientMetadata.serviceDescriptor
  }

  internal var interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCheckCall(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse> {
    return self.makeAsyncUnaryCall(
      path: Grpc_Health_V1_HealthClientMetadata.Methods.check.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckInterceptors() ?? []
    )
  }

  internal func makeWatchCall(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse> {
    return self.makeAsyncServerStreamingCall(
      path: Grpc_Health_V1_HealthClientMetadata.Methods.watch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Grpc_Health_V1_HealthAsyncClientProtocol {
  internal func check(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Grpc_Health_V1_HealthCheckResponse {
    return try await self.performAsyncUnaryCall(
      path: Grpc_Health_V1_HealthClientMetadata.Methods.check.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckInterceptors() ?? []
    )
  }

  internal func watch(
    _ request: Grpc_Health_V1_HealthCheckRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Grpc_Health_V1_HealthCheckResponse> {
    return self.performAsyncServerStreamingCall(
      path: Grpc_Health_V1_HealthClientMetadata.Methods.watch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWatchInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Grpc_Health_V1_HealthAsyncClient: Grpc_Health_V1_HealthAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Grpc_Health_V1_HealthClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Grpc_Health_V1_HealthClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'check'.
  func makeCheckInterceptors() -> [ClientInterceptor<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>]

  /// - Returns: Interceptors to use when invoking 'watch'.
  func makeWatchInterceptors() -> [ClientInterceptor<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>]
}

internal enum Grpc_Health_V1_HealthClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Health",
    fullName: "grpc.health.v1.Health",
    methods: [
      Grpc_Health_V1_HealthClientMetadata.Methods.check,
      Grpc_Health_V1_HealthClientMetadata.Methods.watch,
    ]
  )

  internal enum Methods {
    internal static let check = GRPCMethodDescriptor(
      name: "Check",
      path: "/grpc.health.v1.Health/Check",
      type: GRPCCallType.unary
    )

    internal static let watch = GRPCMethodDescriptor(
      name: "Watch",
      path: "/grpc.health.v1.Health/Watch",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// Health is gRPC's mechanism for checking whether a server is able to handle
/// RPCs. Its semantics are documented in
/// https://github.com/grpc/grpc/blob/master/doc/health-checking.md.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Grpc_Health_V1_HealthProvider: CallHandlerProvider {
  var interceptors: Grpc_Health_V1_HealthServerInterceptorFactoryProtocol? { get }

  /// Check gets the health of the specified service. If the requested service
  /// is unknown, the call will fail with status NOT_FOUND. If the caller does
  /// not specify a service name, the server should respond with its overall
  /// health status.
  ///
  /// Clients should set a deadline when calling Check, and can declare the
  /// server unhealthy if they do not receive a timely response.
  ///
  /// Check implementations should be idempotent and side effect free.
  func check(request: Grpc_Health_V1_HealthCheckRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Grpc_Health_V1_HealthCheckResponse>

  /// Performs a watch for the serving status of the requested service.
  /// The server will immediately send back a message indicating the current
  /// serving status.  It will then subsequently send a new message whenever
  /// the service's serving status changes.
  ///
  /// If the requested service is unknown when the call is received, the
  /// server will send a message setting the serving status to
  /// SERVICE_UNKNOWN but will *not* terminate the call.  If at some
  /// future point, the serving status of the service becomes known, the
  /// server will send a new message with the service's serving status.
  ///
  /// If the call terminates with status UNIMPLEMENTED, then clients
  /// should assume this method is not supported and should not retry the
  /// call.  If the call terminates with any other status (including OK),
  /// clients should retry the call with appropriate exponential backoff.
  func watch(request: Grpc_Health_V1_HealthCheckRequest, context: StreamingResponseCallContext<Grpc_Health_V1_HealthCheckResponse>) -> EventLoopFuture<GRPCStatus>
}

extension Grpc_Health_V1_HealthProvider {
  internal var serviceName: Substring {
    return Grpc_Health_V1_HealthServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Check":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Grpc_Health_V1_HealthCheckRequest>(),
        responseSerializer: ProtobufSerializer<Grpc_Health_V1_HealthCheckResponse>(),
        interceptors: self.interceptors?.makeCheckInterceptors() ?? [],
        userFunction: self.check(request:context:)
      )

    case "Watch":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Grpc_Health_V1_HealthCheckRequest>(),
        responseSerializer: ProtobufSerializer<Grpc_Health_V1_HealthCheckResponse>(),
        interceptors: self.interceptors?.makeWatchInterceptors() ?? [],
        userFunction: self.watch(request:context:)
      )

    default:
      return nil
    }
  }
}

/// Health is gRPC's mechanism for checking whether a server is able to handle
/// RPCs. Its semantics are documented in
/// https://github.com/grpc/grpc/blob/master/doc/health-checking.md.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Grpc_Health_V1_HealthAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Grpc_Health_V1_HealthServerInterceptorFactoryProtocol? { get }

  /// Check gets the health of the specified service. If the requested service
  /// is unknown, the call will fail with status NOT_FOUND. If the caller does
  /// not specify a service name, the server should respond with its overall
  /// health status.
  ///
  /// Clients should set a deadline when calling Check, and can declare the
  /// server unhealthy if they do not receive a timely response.
  ///
  /// Check implementations should be idempotent and side effect free.
  func check(
    request: Grpc_Health_V1_HealthCheckRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Grpc_Health_V1_HealthCheckResponse

  /// Performs a watch for the serving status of the requested service.
  /// The server will immediately send back a message indicating the current
  /// serving status.  It will then subsequently send a new message whenever
  /// the service's serving status changes.
  ///
  /// If the requested service is unknown when the call is received, the
  /// server will send a message setting the serving status to
  /// SERVICE_UNKNOWN but will *not* terminate the call.  If at some
  /// future point, the serving status of the service becomes known, the
  /// server will send a new message with the service's serving status.
  ///
  /// If the call terminates with status UNIMPLEMENTED, then clients
  /// should assume this method is not supported and should not retry the
  /// call.  If the call terminates with any other status (including OK),
  /// clients should retry the call with appropriate exponential backoff.
  func watch(
    request: Grpc_Health_V1_HealthCheckRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Grpc_Health_V1_HealthCheckResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Grpc_Health_V1_HealthAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Grpc_Health_V1_HealthServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Grpc_Health_V1_HealthServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Grpc_Health_V1_HealthServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Check":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Grpc_Health_V1_HealthCheckRequest>(),
        responseSerializer: ProtobufSerializer<Grpc_Health_V1_HealthCheckResponse>(),
        interceptors: self.interceptors?.makeCheckInterceptors() ?? [],
        wrapping: { try await self.check(request: $0, context: $1) }
      )

    case "Watch":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Grpc_Health_V1_HealthCheckRequest>(),
        responseSerializer: ProtobufSerializer<Grpc_Health_V1_HealthCheckResponse>(),
        interceptors: self.interceptors?.makeWatchInterceptors() ?? [],
        wrapping: { try await self.watch(request: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

internal protocol Grpc_Health_V1_HealthServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'check'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCheckInterceptors() -> [ServerInterceptor<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>]

  /// - Returns: Interceptors to use when handling 'watch'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeWatchInterceptors() -> [ServerInterceptor<Grpc_Health_V1_HealthCheckRequest, Grpc_Health_V1_HealthCheckResponse>]
}

internal enum Grpc_Health_V1_HealthServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Health",
    fullName: "grpc.health.v1.Health",
    methods: [
      Grpc_Health_V1_HealthServerMetadata.Methods.check,
      Grpc_Health_V1_HealthServerMetadata.Methods.watch,
    ]
  )

  internal enum Methods {
    internal static let check = GRPCMethodDescriptor(
      name: "Check",
      path: "/grpc.health.v1.Health/Check",
      type: GRPCCallType.unary
    )

    internal static let watch = GRPCMethodDescriptor(
      name: "Watch",
      path: "/grpc.health.v1.Health/Watch",
      type: GRPCCallType.serverStreaming
    )
  }
}
