[package]
name = "test-runner"
description = "Runs inside the VM where the Nym VPN app is being tested"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
dirs = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
socket2 = { workspace = true, features = ["all"] }
surge-ping = { workspace = true }
tarpc = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tokio-serde = { workspace = true }
tokio-serial = { workspace = true }


test-rpc = { path = "../test-rpc" }
nym-ipc = { path = "../../nym-ipc" }
nym-vpnd = { path = "../../nym-vpnd" }


[dependencies.tokio-util]
version = "0.7"
features = ["codec"]
default-features = false

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["user"] }

[target.'cfg(target_os = "linux")'.dependencies]
rs-release = "0.1.7"
