[package]
name = "test-runner"
description = "Runs inside the VM where the Nym VPN app is being tested"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
dirs = "5.0.1"
futures = { workspace = true }
tarpc = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tokio-serial = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
parity-tokio-ipc = "0.9"
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-serde = { workspace = true }
surge-ping = { workspace = true }
rand = "0.8"

libc = "0.2"
chrono = { workspace = true, features = ["serde"] }

test-rpc = { path = "../test-rpc" }
nym-ipc = { path = "../../nym-ipc" }
nym-vpnd = { path = "../../nym-vpnd" }

socket2 = { workspace = true, features = ["all"] }

[dependencies.tokio-util]
version = "0.7"
features = ["codec"]
default-features = false

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["user"] }

[target.'cfg(target_os = "linux")'.dependencies]
rs-release = "0.1.7"
