[package]
name = "nym-vpn-lib-types-uniffi"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
ipnetwork.workspace = true
time.workspace = true
thiserror.workspace = true
url.workspace = true
uniffi = { workspace = true, features = ["tokio"] }
nym-config.workspace = true
nym-sdk.workspace = true
nym-ip-packet-requests.workspace = true
nym-vpn-lib-types = { workspace = true, features = ["nym-type-conversions"] }
nym-vpn-account-controller.workspace = true
nym-vpn-network-config.workspace = true
nym-vpn-api-client.workspace = true
nym-gateway-directory.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
