[package]
name = "test-manager"
description = "Manager process orchestrating e2e tests of the Mullvad VPN app"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-tempfile = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
data-encoding-macro = { workspace = true }
dirs = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
hyper-util = { workspace = true }
ipnetwork = { workspace = true }
inventory = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
nix = { workspace = true, features = ["net"] }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ssh2 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tokio-serial = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
uuid = { workspace = true }

test_macro = { path = "./test_macro" }
test-rpc = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
nym-vpn-proto = { workspace = true, features = ["rpc_client"] }
nym-vpn-lib-types = { workspace = true, features = ["nym-type-conversions"] }
nym-vpn-api-client = { workspace = true }
nym-network-defaults = { workspace = true }
bip39 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["process", "test-util"] }

[target.'cfg(target_os = "macos")'.dependencies]
tun = { workspace = true }
nix = { workspace = true, features = ["signal", "process"] }
