[package]
name = "nym-vpnd-types-uniffi"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
time.workspace = true
uniffi = { workspace = true, features = ["tokio"] }

nym-gateway-directory.workspace = true
nym-vpn-api-client.workspace = true
nym-vpnd-types.workspace = true
nym-vpn-lib-types-uniffi.workspace = true
