// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GatewaySelectionAlgorithm =
  | 'explicit'
  | 'autoEntryExplicitExit'
  | 'auto';

export type GatewaySelectionAlgorithmConfig = {
  /**
   * Whether selection algorithm uses geo-location is enabled.
   */
  enableGeoLocation: boolean;
  /**
   * The gateway selection algorithm that should be used.
   */
  gatewaySelectionAlgorithm: GatewaySelectionAlgorithm;
};
