// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountLinks = {
  signUp: string;
  signIn: string;
  account: string | null;
};

export type Address = { nymAddress: string; gatewayId: string };

export type App = {
  name: string;
  /**
   * Absolute path to the main executable.
   */
  executable_path: string;
  /**
   * Absolute path to the cached icon PNG, when available. Stored in tauri app cache directory.
   */
  icon: string | null;
  /**
   * Whether this app was added by the user via the file dialog (custom) or discovered.
   */
  is_custom: boolean;
};

export type Asn = { asn: string; name: string; type: AsnType };

export type AsnType = 'other' | 'residential';

export type BackgroundCoverTrafficRate = { value: number; multiplier: string };

export type BridgeAddress = { listenAddr: string; remoteAddr: string };

export type Cli = {
  /**
   * Print build information
   */
  buildInfo: boolean;
  /**
   * Set the log level
   */
  logLevel: 'trace' | 'debug' | 'info' | 'warn' | 'error' | null;
  /**
   * Disable the splash-screen
   */
  nosplash: boolean;
  devMode: boolean;
  /**
   * Remove all app local files, like config, data, and cache files
   */
  cleanLocalFiles: boolean;
};

export type ConnectingProgress =
  | 'resolving-api-addresses'
  | 'awaiting-account-readiness'
  | 'awaiting-credentials-availability'
  | 'refreshing-gateways'
  | 'selecting-gateways'
  | 'registering-with-gateways'
  | 'connecting-tunnel';

export type ConnectingState = {
  tunnelType: TunnelType;
  progress: ConnectingProgress;
  tunnel: TunnelData | null;
  retryAttempt: number;
  entryGwId: string | null;
  exitGwId: string | null;
};

export type ContinuousTrafficSendingRate = {
  value: number;
  throughput: string;
};

export type Country = { name: string; code: string };

export type DbKey =
  | 'ui-theme'
  | 'ui-root-font-size'
  | 'ui-language'
  | 'technical-optin-seen'
  | 'desktop-notifications'
  | 'last-network-env'
  | 'network-stats-enabled'
  | 'custom-split-tunnel-apps'
  | 'cache-mx-entry-gateways'
  | 'cache-mx-exit-gateways'
  | 'cache-wg-gateways'
  | 'cache-account-id'
  | 'cache-device-id';

export type DeeplinkKind =
  | 'privy'
  | 'privyLink'
  | 'autologinRenew'
  | 'autologinView'
  | 'createAccount';

export type DisplayServer = 'x11' | 'wayland' | { unknown: string | null };

export type DownloadUpdateEvent =
  | { event: 'started'; data: { contentLength: bigint } }
  | { event: 'progress'; data: { chunkLength: number } }
  | { event: 'finished' };

/**
 * Enum of the possible specialized errors emitted by the daemon
 * or the app backend side, to be passed to the UI layer
 */
export type ErrorKey =
  | 'internal'
  | 'vpnd-client'
  | 'not-connected-to-daemon'
  | 'auth-denied'
  | 'entry-gw-down'
  | 'exit-gw-down-ipv4'
  | 'exit-gw-down-ipv6'
  | 'exit-gw-routing-error-ipv4'
  | 'exit-gw-routing-error-ipv6'
  | 'mixnet-no-bandwidth'
  | 'account-invalid-mnemonic'
  | 'account-invalid-secret'
  | 'no-account-stored'
  | 'no-device-stored'
  | 'existing-account'
  | 'bandwidth-exceeded'
  | 'account-status-not-active'
  | 'no-subscription'
  | 'max-device-reached'
  | 'device-time-desync'
  | 'split-tunnel-app-invalid'
  | 'split-tunnel-app-duplicate'
  | 'insufficient-funds'
  | 'get-mixnet-entry-countries-query'
  | 'get-mixnet-exit-countries-query'
  | 'get-wg-countries-query';

export type Favorite = { kind: FavoriteKind; value: string };

/**
 * The hop a favorite applies to. Favorites are independent per hop.
 */
export type FavoriteHop = 'entry' | 'exit';

/**
 * What a favorite points at. `value` is a gateway identity, an ISO-3166
 * two-letter country code, or a region name depending on `kind`.
 */
export type FavoriteKind = 'gateway' | 'country' | 'region';

export type Favorites = { entry: Array<Favorite>; exit: Array<Favorite> };

export type FeatureFlags = {
  quic: boolean;
  domainFronting: boolean;
  zknymCredential: boolean;
};

export type FrontingMode = 'off' | 'onRetry' | 'always';

export type Gateway = {
  id: string;
  type: GatewayType;
  name: string;
  country: Country;
  location: Location;
  description: string | null;
  asn: Asn | null;
  mxScore: Score;
  wgScore: Score;
  wgPerformance: Performance | null;
  exitIpv4: string | null;
  exitIpv6: string | null;
  buildVersion: string | null;
  quic: boolean;
  nodeFamilyName: string | null;
};

export type GatewaySelectionAlgorithm =
  | 'explicit'
  | 'autoEntryExplicitExit'
  | 'auto';

export type GatewaySelectionAlgorithmConfig = {
  enableGeoLocation: boolean;
  gatewaySelectionAlgorithm: GatewaySelectionAlgorithm;
};

export type GatewayType = 'mx-entry' | 'mx-exit' | 'wg';

export type GatewaysByCountry = {
  country: Country;
  regions: Array<Region>;
  gateways: Array<Gateway>;
  type: GatewayType;
  quic: boolean;
};

export type GeoExclusionSettings = {
  enabled: boolean;
  listenPort: number;
  excludedCountries: Array<string>;
};

export type GpuType = 'nvidia' | 'amd' | 'intel' | { unknown: string | null };

export type Hop = 'entry' | 'exit';

export type HttpRpcSettings = { listenAddress: string | null };

export type JsEnv = {
  devMode: boolean;
  updaterEnabled: boolean;
  noSplash: boolean;
  defaultVpnMode: 'mixnet' | 'wg';
  defaultSentry: boolean;
  defaultNetstats: boolean;
  defaultQuic: boolean;
  startupError: StartupError | null;
};

export type Location = {
  latitude: number;
  longitude: number;
  city: string;
  region: string;
};

export type MixingDelay = {
  minValue: number;
  maxValue: number;
  defaultValue: number;
};

export type MixnetData = {
  nymAddress: Address;
  exitIpr: Address;
  ipv4: string;
  ipv6: string | null;
  entryIp: string;
  exitIp: string;
};

export type MixnetEvent =
  | 'entry-gw-down'
  | 'exit-gw-down-ipv4'
  | 'exit-gw-down-ipv6'
  | 'exit-gw-routing-error-ipv4'
  | 'exit-gw-routing-error-ipv6'
  | 'connected-ipv4'
  | 'connected-ipv6'
  | 'no-bandwidth'
  | { 'remaining-bandwidth': bigint }
  | 'sphinx-packet-metrics';

export type MixnetEventPayload = { event: MixnetEvent } | { error: ErrorKey };

export type MixnetTrafficConfig = {
  poissonParameterForLoopCoverStream: number | null;
  averagePacketDelay: number | null;
  messageSendingAverageDelay: number | null;
  disablePoissonRate: boolean;
  disableBackgroundCoverTraffic: boolean;
  minMixnodePerformance: number | null;
  minGatewayMixnetPerformance: number | null;
};

export type MixnetTrafficDefaults = {
  mixingDelay: MixingDelay;
  disablePoissonRate: boolean;
  defaultBackgroundTraffic: BackgroundCoverTrafficRate;
  defaultContinuousTraffic: ContinuousTrafficSendingRate;
  allBackgroundTraffic: Array<BackgroundCoverTrafficRate>;
  allContinuousTraffic: Array<ContinuousTrafficSendingRate>;
};

export type NetworkCompat = { core: boolean | null; tauri: boolean | null };

export type NetworkEnv = 'mainnet' | 'canary' | 'sandbox';

export type OsInfo = {
  /**
   * long version
   */
  version: string;
  kernel: string;
  arch: string;
  hash: string;
  displayServer: DisplayServer | null;
  gpu: GpuType | null;
};

export type Performance = {
  score: Score;
  load: Score;
  lastUpdatedUtc: string;
  /**
   * uptime percentage on the last 24 hours
   */
  uptime24h: number;
};

export type Region = {
  name: string;
  country: Country;
  gateways: Array<Gateway>;
  type: GatewayType;
  quic: boolean;
};

export type Score = 'offline' | 'low' | 'medium' | 'high';

export type SelectedNode =
  | { country: { code: string } }
  | { gateway: { id: string } }
  | { region: string }
  | 'random';

export type Socks5Settings = { listenAddress: string | null };

export type Socks5State = 'disabled' | 'idle' | 'connected' | 'error';

export type Socks5Status = {
  state: Socks5State;
  socks5Settings: Socks5Settings | null;
  httpRpcSettings: HttpRpcSettings | null;
  errorMessage: string | null;
  activeConnections: number;
};

export type SplitApp = { path: string };

export type SplitTunnelSettings = { enabled: boolean; apps: Array<SplitApp> };

export type StartupError = {
  key: 'internal' | 'db-open' | 'db-locked';
  detail: string | null;
};

export type SystemMessage = {
  name: string;
  message: string;
  display_from: bigint | null;
  display_until: bigint | null;
  properties: { [key in string]?: string } | null;
};

export type TAccountMode = 'privy' | 'decentralised' | 'api';

export type TAccountState =
  | 'ready'
  | 'logged-out'
  | 'syncing'
  | 'offline'
  | 'decentralised'
  | 'bandwidth-exceeded'
  | 'status-not-active'
  | 'no-subscription'
  | 'pending-subscription'
  | 'max-device-reached'
  | { error: TBackendError };

export type TAccountSummary = {
  trafficUsedGb: bigint;
  trafficLimitGb: bigint;
  trafficResetTime: bigint | null;
  fairUsageDataUnavailable: boolean;
  accountAddr: string;
  canonicalAccountAddr: string | null;
  authMethods: Array<TAuthMethod>;
  isLinked: boolean;
  fairUsageLeft: boolean;
  isSubscriptionActive: boolean;
  subscription: TSubscription | null;
  isSubscriptionStacked: boolean;
};

export type TApiTimeSkew = {
  localTime: string;
  estimatedRemoteTime: string;
  acceptablySynced: boolean;
};

export type TAuthMethod = {
  id: string;
  pubkey: string;
  kind: string;
  label: string;
  status: TVpnAccountStatus;
};

export type TAutologinResponse = { url: string; 'pin-code': string };

/**
 * Generic error type made to be passed to the frontend and
 * displayed in the UI as localized error message
 */
export type TBackendError = {
  /**
   * Error message for debugging/logs purposes
   * not intended to be displayed to the user
   */
  message: string;
  /**
   * Error key to be used in the UI to display localized error message
   */
  key: ErrorKey;
  /**
   * Extra data to be passed along to help specialize the problem
   */
  data: { [key in string]?: string } | null;
};

export type TCompleteDnsReport = {
  system: TDiagnosticResult<Array<TDnsResolution>>;
  byNameserver: Array<TDiagnosticResult<Array<TDnsResolution>>>;
};

export type TDiagnosticEndpointResponse = {
  status: string;
  url: string;
  frontHosts: Array<string> | null;
};

export type TDiagnosticGateway = {
  identityKey: string;
  name: string;
  description: string | null;
};

export type TDiagnosticHealthResponse = {
  status: string;
  timestampUtc: string;
};

export type TDiagnosticReport = {
  dns: TCompleteDnsReport | null;
  http: TDiagnosticResult<THttpReport> | null;
  gateway: TGatewayReport | null;
  hybridTransport: TDiagnosticResult<THybridTransportReport> | null;
};

export type TDiagnosticResult<T> = {
  ok: boolean;
  value: T | null;
  error: string | null;
};

export type TDiagnosticRunParams = {
  gateway: string | null;
  skipDns: boolean;
  skipHttp: boolean;
  skipHybridTransport: boolean;
};

export type TDnsResolution = {
  nameservers: string;
  hostname: string;
  resolution: TDiagnosticResult<Array<string>>;
  resolutionDurationMs: bigint;
};

export type TGatewayReport = {
  gateway: TDiagnosticResult<TDiagnosticGateway | null>;
  tcp: TDiagnosticResult<null> | null;
  websocket: TDiagnosticResult<null> | null;
  websocketRequest: TDiagnosticResult<string> | null;
  lpHandshake: TDiagnosticResult<null> | null;
};

export type THttpReport = {
  remoteTime: TDiagnosticResult<TApiTimeSkew>;
  healthResponse: TDiagnosticResult<TDiagnosticHealthResponse>;
  nbNymnodes: TDiagnosticResult<number>;
  byEndpoint: Array<TDiagnosticResult<TDiagnosticEndpointResponse>>;
};

export type THybridTransportReport = {
  routingId: string;
  handshakeDurationMs: bigint;
};

export type TNymVpnSubscription = {
  createdOnUtc: string;
  lastUpdatedUtc: string;
  id: string;
  validUntilUtc: bigint;
  validFromUtc: bigint;
  status: string;
  kind: TVpnSubscriptionKind;
  isRecurring: boolean;
};

export type TSubscription = {
  status: TSubscriptionStatus;
  subscription: TNymVpnSubscription;
};

export type TSubscriptionStatus = 'pending' | 'active';

export type TTunnelState =
  | 'disconnected'
  | { connected: Tunnel }
  | { connecting: ConnectingState }
  | { disconnecting: TunnelAction | null }
  | { error: TunnelError }
  | { offline: { reconnect: boolean } };

export type TVpnAccountStatus = 'active' | 'inactive' | 'delete-me';

export type TVpnSubscriptionKind =
  | 'one-month'
  | 'one-year'
  | 'two-years'
  | 'freepass'
  | { other: string };

/**
 * Only the discriminant is needed by the UI to decide the connect flow, so the
 * `Selected` entry/exit payload is intentionally dropped.
 */
export type TentativeGateways =
  | 'selected'
  | 'needs-relaxed-independence-criteria'
  | 'no-gateways-available';

export type ThemeMode = 'system' | 'light' | 'dark';

export type Tunnel = {
  entryGwId: string;
  exitGwId: string;
  connectedAt: bigint;
  data: TunnelData;
};

export type TunnelAction = 'error' | 'reconnect' | 'offline';

export type TunnelData = MixnetData | WireguardData;

export type TunnelError =
  | { internal: string }
  | 'set-firewall-policy'
  | 'set-dns'
  | 'set-routing'
  | 'same-entry-and-exit-gw'
  | 'performant-entry-gw-unavailable'
  | 'performant-exit-gw-unavailable'
  | 'invalid-entry-gw-id'
  | 'invalid-exit-gw-id'
  | 'invalid-entry-gw-country'
  | 'invalid-exit-gw-country'
  | 'max-devices-reached'
  | 'bandwidth-exceeded'
  | 'inactive-subscription'
  | 'device-time-out-of-sync'
  | 'device-logged-out'
  | 'ipv6-unavailable'
  | 'tun-device'
  | 'tunnel-provider'
  | 'inactive-account'
  | 'credential-wasted-on-entry-gateway'
  | 'credential-wasted-on-exit-gateway'
  | 'need-full-disk-permissions'
  | 'split-tunnel'
  | 'needs-relaxed-independence-criteria'
  | 'credential-fetching-failed'
  | 'no-credential-available';

export type TunnelStateEvent = {
  state: TTunnelState;
  error: TBackendError | null;
};

export type TunnelType = 'wg' | 'mixnet';

/**
 * concrete UI mode
 */
export type UiTheme = 'light' | 'dark';

export type UpdateMetadata = { version: string; currentVersion: string };

export type VpnMode = 'mixnet' | 'wg';

export type VpndConfig = {
  entryNode: SelectedNode;
  exitNode: SelectedNode;
  customDns: Array<string> | null;
  enableCustomDns: boolean;
  allowLan: boolean;
  enableAdBlocking: boolean;
  disableIpv6: boolean;
  vpnMode: VpnMode;
  bridges: boolean;
  netstack: boolean;
  frontingMode: FrontingMode;
  minGatewayVpnPerformance: number | null;
  residentialExit: boolean;
  mixnetTraffic: MixnetTrafficConfig;
  mixnetTrafficDefaults: MixnetTrafficDefaults;
  splitTunnel: SplitTunnelSettings;
  geoExclusion: GeoExclusionSettings;
  gatewaySelectionAlgorithmConfig: GatewaySelectionAlgorithmConfig;
  gatewayIndependenceNotifications: boolean;
};

export type VpndInfo = { version: string; network: string; gitCommit: string };

export type VpndStatus =
  | { ok: VpndInfo | null }
  | {
      nonCompat: {
        /**
         * The current daemon info, including its version
         */
        current: VpndInfo;
        /**
         * The SemVer version requirement
         */
        requirement: string;
      };
    }
  | 'down'
  | 'authDenied';

export type WgNode = {
  endpoint: string;
  publicKey: string;
  privateIpv4: string;
  privateIpv6: string | null;
};

export type WindowPosition =
  | { type: 'Physical'; x: number; y: number }
  | { type: 'Logical'; x: number; y: number };

export type WindowSize =
  | { type: 'Physical'; width: number; height: number }
  | { type: 'Logical'; width: number; height: number };

export type WireguardData = {
  entryBridgeAddr: BridgeAddress | null;
  entry: WgNode;
  exit: WgNode;
};
