// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountLinks = {
  signUp: string;
  signIn: string;
  account: string | null;
};

export type Address = { nymAddress: string; gatewayId: string };

export type Asn = { asn: string; name: string; type: AsnType };

export type AsnType = 'other' | 'residential';

export type BridgeAddress = { listenAddr: string; remoteAddr: string };

export type Cli = {
  /**
   * Print build information
   */
  buildInfo: boolean;
  /**
   * IP address of the DNS server to use when connected to the VPN
   */
  dns: string | null;
  /**
   * Enable writing app logs to a file
   */
  logFile: boolean;
  /**
   * Set the log level
   */
  logLevel: 'trace' | 'debug' | 'info' | 'warn' | 'error' | null;
  /**
   * Disable the splash-screen
   */
  nosplash: boolean;
  devMode: boolean;
  /**
   * Remove all app local files, like config, data, and cache files
   */
  cleanLocalFiles: boolean;
};

export type ConnectingProgress =
  | 'resolving-api-addresses'
  | 'awaiting-account-readiness'
  | 'refreshing-gateways'
  | 'selecting-gateways'
  | 'registering-with-gateways'
  | 'connecting-tunnel';

export type ConnectingState = {
  tunnelType: TunnelType;
  progress: ConnectingProgress;
  tunnel: TunnelData | null;
  retryAttempt: number;
  entryGwId: string | null;
  exitGwId: string | null;
};

export type Country = { name: string; code: string };

export type DbKey =
  | 'ui-theme'
  | 'ui-root-font-size'
  | 'ui-language'
  | 'vpn-mode'
  | 'entry-node'
  | 'exit-node'
  | 'welcome-screen-seen'
  | 'desktop-notifications'
  | 'last-network-env'
  | 'disable-ipv6'
  | 'network-stats-enabled'
  | 'quic-enabled'
  | 'domain-fronting-enabled'
  | 'cache-mx-entry-gateways'
  | 'cache-mx-exit-gateways'
  | 'cache-wg-gateways'
  | 'cache-account-id'
  | 'cache-device-id'
  | 'streaming-optimized-label-seen';

export type DisplayServer = 'x11' | 'wayland' | { unknown: string | null };

export type DownloadUpdateEvent =
  | { event: 'started'; data: { contentLength: bigint } }
  | { event: 'progress'; data: { chunkLength: number } }
  | { event: 'finished' };

/**
 * Enum of the possible specialized errors emitted by the daemon
 * or the app backend side, to be passed to the UI layer
 */
export type ErrorKey =
  | 'internal'
  | 'grpc'
  | 'not-connected-to-daemon'
  | 'entry-gw-down'
  | 'exit-gw-down-ipv4'
  | 'exit-gw-down-ipv6'
  | 'exit-gw-routing-error-ipv4'
  | 'exit-gw-routing-error-ipv6'
  | 'mixnet-no-bandwidth'
  | 'account-invalid-mnemonic'
  | 'no-account-stored'
  | 'no-device-stored'
  | 'existing-account'
  | 'bandwidth-exceeded'
  | 'account-status-not-active'
  | 'no-subscription'
  | 'max-device-reached'
  | 'device-time-desync'
  | 'get-mixnet-entry-countries-query'
  | 'get-mixnet-exit-countries-query'
  | 'get-wg-countries-query';

export type FeatureFlags = {
  quic: boolean;
  domainFronting: boolean;
  zknymCredential: boolean;
  gatewayUpdateVersion: string | null;
};

export type Gateway = {
  id: string;
  type: GatewayType;
  name: string;
  country: Country;
  location: Location;
  description: string | null;
  asn: Asn | null;
  mxScore: Score;
  wgScore: Score;
  wgPerformance: Performance | null;
  exitIpv4: string | null;
  exitIpv6: string | null;
  buildVersion: string | null;
  quic: boolean;
};

export type GatewayNode = {
  id: string;
  name: string;
  country: Country;
  region: string;
  city: string;
};

export type GatewayType = 'mx-entry' | 'mx-exit' | 'wg';

export type GatewaysByCountry = {
  country: Country;
  regions: Array<Region>;
  gateways: Array<Gateway>;
  type: GatewayType;
  quic: boolean;
};

export type GpuType = 'nvidia' | 'amd' | 'intel' | { unknown: string | null };

export type Hop = 'entry' | 'exit';

export type JsEnv = {
  devMode: boolean;
  updaterEnabled: boolean;
  noSplash: boolean;
  defaultVpnMode: 'mixnet' | 'wg';
  defaultSentry: boolean;
  defaultNetstats: boolean;
  defaultQuic: boolean;
  defaultDomainFronting: boolean;
  startupError: StartupError | null;
};

export type Location = {
  latitude: number;
  longitude: number;
  city: string;
  region: string;
};

export type MixnetData = {
  nymAddress: Address;
  exitIpr: Address;
  ipv4: string;
  ipv6: string | null;
  entryIp: string;
  exitIp: string;
};

export type MixnetEvent =
  | 'entry-gw-down'
  | 'exit-gw-down-ipv4'
  | 'exit-gw-down-ipv6'
  | 'exit-gw-routing-error-ipv4'
  | 'exit-gw-routing-error-ipv6'
  | 'connected-ipv4'
  | 'connected-ipv6'
  | 'no-bandwidth'
  | { 'remaining-bandwidth': bigint }
  | 'sphinx-packet-metrics';

export type MixnetEventPayload = { event: MixnetEvent } | { error: ErrorKey };

export type NetworkCompat = { core: boolean | null; tauri: boolean | null };

export type NetworkEnv = 'mainnet' | 'canary' | 'qa' | 'sandbox';

export type OsInfo = {
  /**
   * long version
   */
  version: string;
  kernel: string;
  arch: string;
  hash: string;
  displayServer: DisplayServer | null;
  gpu: GpuType | null;
};

export type Performance = {
  score: Score;
  load: Score;
  lastUpdatedUtc: string;
  /**
   * uptime percentage on the last 24 hours
   */
  uptime24h: number;
};

export type Region = {
  name: string;
  country: Country;
  gateways: Array<Gateway>;
  type: GatewayType;
  quic: boolean;
};

export type RegionNode = { name: string; country: Country };

export type Score = 'offline' | 'low' | 'medium' | 'high';

export type SelectedNode =
  | { type: 'country'; node: Country }
  | { type: 'gateway'; node: GatewayNode }
  | { type: 'region'; node: RegionNode };

export type StartupError = {
  key: 'internal' | 'db-open' | 'db-locked';
  detail: string | null;
};

export type SystemMessage = {
  name: string;
  message: string;
  display_from: bigint | null;
  display_until: bigint | null;
  properties: { [key in string]?: string } | null;
};

export type TAccountState =
  | 'ready'
  | 'logged-out'
  | 'syncing'
  | 'offline'
  | 'decentralised'
  | 'bandwidth-exceeded'
  | 'status-not-active'
  | 'no-subscription'
  | 'max-device-reached'
  | 'requesting-zk-nyms'
  | { error: TBackendError };

/**
 * Generic error type made to be passed to the frontend and
 * displayed in the UI as localized error message
 */
export type TBackendError = {
  /**
   * Error message for debugging/logs purposes
   * not intended to be displayed to the user
   */
  message: string;
  /**
   * Error key to be used in the UI to display localized error message
   */
  key: ErrorKey;
  /**
   * Extra data to be passed along to help specialize the problem
   */
  data: { [key in string]?: string } | null;
};

export type TTunnelState =
  | 'disconnected'
  | { connected: Tunnel }
  | { connecting: ConnectingState }
  | { disconnecting: TunnelAction | null }
  | { error: TunnelError }
  | { offline: { reconnect: boolean } };

export type ThemeMode = 'system' | 'light' | 'dark';

export type Tunnel = {
  entryGwId: string;
  exitGwId: string;
  connectedAt: bigint;
  data: TunnelData;
};

export type TunnelAction = 'error' | 'reconnect' | 'offline';

export type TunnelData = MixnetData | WireguardData;

export type TunnelError =
  | { internal: string }
  | 'set-firewall-policy'
  | 'set-dns'
  | 'set-routing'
  | 'same-entry-and-exit-gw'
  | 'performant-entry-gw-unavailable'
  | 'performant-exit-gw-unavailable'
  | 'invalid-entry-gw-id'
  | 'invalid-exit-gw-id'
  | 'invalid-entry-gw-country'
  | 'invalid-exit-gw-country'
  | 'max-devices-reached'
  | 'bandwidth-exceeded'
  | 'inactive-subscription'
  | 'device-time-out-of-sync'
  | 'device-logged-out'
  | 'ipv6-unavailable'
  | 'tun-device'
  | 'tunnel-provider'
  | 'inactive-account'
  | 'credential-wasted-on-entry-gateway'
  | 'credential-wasted-on-exit-gateway';

export type TunnelStateEvent = {
  state: TTunnelState;
  error: TBackendError | null;
};

export type TunnelType = 'wg' | 'mixnet';

/**
 * concrete UI mode
 */
export type UiTheme = 'light' | 'dark';

export type UpdateMetadata = { version: string; currentVersion: string };

export type VpnMode = 'mixnet' | 'wg';

export type VpndInfo = { version: string; network: string; gitCommit: string };

export type VpndStatus =
  | { ok: VpndInfo | null }
  | {
      nonCompat: {
        /**
         * The current daemon info, including its version
         */
        current: VpndInfo;
        /**
         * The SemVer version requirement
         */
        requirement: string;
      };
    }
  | 'down';

export type WgNode = {
  endpoint: string;
  publicKey: string;
  privateIpv4: string;
  privateIpv6: string | null;
};

export type WindowPosition =
  | { type: 'Physical'; x: number; y: number }
  | { type: 'Logical'; x: number; y: number };

export type WindowSize =
  | { type: 'Physical'; width: number; height: number }
  | { type: 'Logical'; width: number; height: number };

export type WireguardData = {
  entryBridgeAddr: BridgeAddress | null;
  entry: WgNode;
  exit: WgNode;
};
