[package]
name = "nym-privy"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bip39.workspace = true
hex.workspace = true
sha2.workspace = true
thiserror.workspace = true

