[package]
name = "nym-vpn-account-controller"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
#si-scale = { workspace = true, features = ["lossy-conversions"] }
aes-gcm.workspace = true
async-trait.workspace = true
#bincode.workspace = true
bip39 = { workspace = true, features = ["zeroize"] }
bs58.workspace = true
pbkdf2.workspace = true
futures.workspace = true
hkdf.workspace = true
nym-coconut-dkg-common.workspace = true
nym-common.workspace = true
nym-bandwidth-controller.workspace = true
nym-bandwidth-fetcher.workspace = true
nym-crypto = { workspace = true, features = ["asymmetric", "rand"] }
nym-endpoint-health.workspace = true
nym-network-defaults.workspace = true
nym-offline-monitor.workspace = true
nym-sdk.workspace = true
nym-upgrade-mode-check.workspace = true
nym-validator-client.workspace = true
nym-vpn-api-client.workspace = true
nym-vpn-credential-fetcher.workspace = true
nym-vpn-lib-types = { workspace = true, features = ["nym-type-conversions"] }
nym-vpn-network-config.workspace = true
nym-vpn-store.workspace = true
rand.workspace = true
serde.workspace = true
sha2.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
time.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
tokio = { workspace = true, features = ["fs"] }
tracing.workspace = true
#zeroize.workspace = true
url.workspace = true

[dev-dependencies]
anyhow.workspace = true
rand.workspace = true
nym-compact-ecash.workspace = true
nym-credential-proxy-requests.workspace = true
nym-credentials.workspace = true
nym-credentials-interface.workspace = true
nym-ecash-time.workspace = true
nym-http-api-client.workspace = true
tempfile.workspace = true
wiremock.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
