[package]
name = "nym-vpn-account-controller"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
# nym-client-core = { workspace = true, features = ["cli", "fs-credentials-storage", "fs-surb-storage", "fs-gateways-storage"] }
nym-compact-ecash.workspace = true
nym-config.workspace = true
nym-credential-proxy-requests.workspace = true
nym-credential-storage.workspace = true
nym-credentials-interface.workspace = true
nym-credentials.workspace = true
nym-ecash-time.workspace = true
nym-http-api-client.workspace = true
nym-sdk.workspace = true
nym-validator-client.workspace = true
nym-vpn-api-client = { path = "../nym-vpn-api-client" }
nym-vpn-store = { path = "../nym-vpn-store" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
si-scale.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
time.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
