[package]
name = "nym-vpn-network-config"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
itertools.workspace = true
reqwest = { workspace = true, default-features = false, features = [
    "blocking",
    "rustls-tls",
    "json",
] }
nym-config.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
time = { workspace = true, features = ["serde-human-readable"] }
tokio = { workspace = true, features = ["time", "macros"] }
tokio-util.workspace = true
tracing.workspace = true
url = { workspace = true, features = ["serde"] }
futures-util = "0.3"

[build-dependencies]
serde_json.workspace = true
