[package]
name = "nym-firewall-config"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ipnetwork.workspace = true
nym-network-defaults.workspace = true

[lints]
workspace = true
