[package]
name = "nym-diagnostic"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true


[dependencies]
nym-authenticator-client.workspace = true
nym-bandwidth-controller.workspace = true
nym-bin-common.workspace = true
nym-client-core.workspace = true
nym-credentials-interface.workspace = true
nym-crypto.workspace = true
nym-gateway-directory.workspace = true
nym-gateway-requests.workspace = true
nym-http-api-client.workspace = true
nym-ip-packet-client.workspace = true
nym-lp.workspace = true
nym-lp-data.workspace = true
nym-registration-common.workspace = true
nym-registration-client.workspace = true
nym-sdk.workspace = true
nym-topology.workspace = true
nym-validator-client.workspace = true
nym-vpn-lib-types = { workspace = true, features = [
    "serde",
    "nym-type-conversions",
] }
nym-platform-metadata = { workspace = true, features = ["user-agent-macro"] }
nym-vpn-api-client.workspace = true
nym-vpn-network-config.workspace = true

anyhow.workspace = true
async-trait.workspace = true
boringtun.workspace = true
clap.workspace = true
futures.workspace = true
hickory-resolver = { workspace = true, features = [
    "system-config",
    "tokio",
    "tls-ring",
    "https-ring",
] }
pnet_packet.workspace = true
rand10.workspace = true
rand.workspace = true
rustls = { workspace = true, features = ["ring"] }
semver.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tokio-util.workspace = true
tokio-tungstenite.workspace = true
tokio-rustls.workspace = true
webpki-roots.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true


[build-dependencies]
vergen-gitcl = { workspace = true, default-features = false, features = [
    "build",
    "cargo",
    "rustc",
] }
