# Publish vpn-x on AUR

name: aur-nym-vpn-x
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Tag name of the release"
        required: true
        default: nym-vpn-x-v0.1.0
      pkgrel:
        description: "PKGBUILD package release number"
        required: false
        type: number
        default: 1
      publish_aur:
        description: "publish PKGBUILD changes to AUR"
        type: boolean
        required: false
        default: true

jobs:
  aur-publish:
    name: Publish package in AUR
    runs-on: ubuntu-latest
    env:
      PKGNAME: nymvpn-x
      PKGBUILD: nym-vpn-x/.pkg/aur/PKGBUILD
      PKGREL: ${{ inputs.pkgrel }}
      RELEASE_TAG: ${{ inputs.release_tag }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download sources
        run: |
          curl -LfsSo "$RELEASE_TAG.tar.gz" "https://github.com/$REPOSITORY/archive/refs/tags/$RELEASE_TAG.tar.gz"
          mkdir tarball
          tar -xzf "$RELEASE_TAG.tar.gz" -C tarball
          ls -la tarball/nym-vpn-client-$RELEASE_TAG
      - name: Get app version
        id: app-version
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.version --entry="tarball/nym-vpn-client-${{ env.RELEASE_TAG }}/nym-vpn-x/src-tauri"
      - name: Update PKGBUILD
        working-directory: nym-vpn-x
        env:
          TARBALL: ${{ github.workspace }}/${{ env.RELEASE_TAG }}.tar.gz
          PKGVER: ${{ steps.app-version.outputs.metadata }}
        run: .pkg/aur/update.sh
      - name: Show PKGBUILD
        run: cat "$PKGBUILD"
      - name: Publish
        if: inputs.publish_aur == true
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.1
        with:
          pkgname: ${{ env.PKGNAME }}
          pkgbuild: ${{ env.PKGBUILD }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: ${{ inputs.release_tag }}
          assets: |
            nym-vpn-x/.pkg/aur/nymvpn-x-wrapper.sh
            nym-vpn-x/.pkg/aur/nymvpn-x.desktop
            nym-vpn-x/.pkg/aur/nymvpn-x.svg
