# Publish vpn-x on AUR

name: aur-nym-vpn-x
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Tag name of the release"
        required: true
        default: nym-vpn-x-v0.1.0
      pkgver:
        description: "PKGBUILD package version (should match the release version)"
        required: true
        default: 0.1.0
      pkgrel:
        description: "PKGBUILD package release number"
        required: false
        default: 1

jobs:
  aur-publish:
    name: Publish package in AUR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nym-vpn-x
    env:
      PKGNAME: nymvpn-x
      PKGBUILD: .pkg/aur/PKGBUILD
      PKGVER: ${{ inputs.pkgver }}
      PKGREL: ${{ inputs.pkgrel }}
      RELEASE_TAG: ${{ inputs.release_tag }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download sources
        run: curl -LfsSo "$RELEASE_TAG.tar.gz" "https://github.com/$REPOSITORY/archive/refs/tags/$RELEASE_TAG.tar.gz"
      - name: Update PKGBUILD
        run: .pkg/aur/update.sh
      - name: Show PKGBUILD
        run: cat "$PKGBUILD"
      - name: Publish
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.1
        with:
          pkgname: ${{ env.PKGNAME }}
          pkgbuild: ${{ env.PKGBUILD }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: ${{ inputs.release_tag }}
          assets: |
            .pkg/aur/nymvpn-x-wrapper.sh
            .pkg/aur/nymvpn-x.desktop
            .pkg/aur/nymvpn-x.svg

