name: build-nym-vpn-core-linux
on:
  pull_request:
    types: [opened]
    paths:
      - ".github/workflows/build-nym-vpn-core-linux.yml"
  workflow_dispatch:
  workflow_call:
    secrets:
      VPND_SENTRY_DSN:
        required: true
    outputs:
      RUST_VERSION:
        value: ${{ jobs.build-linux.outputs.RUST_VERSION }}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wireguard-go-linux:
    uses: ./.github/workflows/build-wireguard-go-linux.yml

  build-linux:
    strategy:
      matrix:
        include:
          - os: "ubuntu-22.04"
            arch: "x86_64"
          - os: "ubuntu-22.04-arm"
            arch: "aarch64"

    if: github.actor != 'dependabot[bot]'
    needs: build-wireguard-go-linux
    env:
      UPLOAD_DIR_LINUX: linux_artifacts-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    outputs:
      UPLOAD_DIR_LINUX: ${{ env.UPLOAD_DIR_LINUX }}
      RUST_VERSION: ${{ steps.rust-version.outputs.rustc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libdbus-1-dev libmnl-dev libnftnl-dev protobuf-compiler

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12" # 3.21.12: the version on ubuntu 24.04. Don't change this!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-edit
          cache-key: ${{ matrix.arch }}

      - name: Get workspace version
        id: workspace-version
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: workspace.package.version --entry nym-vpn-core

      - name: Append timestamp if it's a dev version
        run:
          ./scripts/append-timestamp-to-version.sh nym-vpn-core/Cargo.toml ${{
          steps.workspace-version.outputs.metadata }}

      - name: Download wireguard-go artifacts
        uses: actions/download-artifact@v8
        with:
          name: wireguard_go-${{ matrix.arch }}
          path: build/lib

      - name: Build nym-vpn-core
        working-directory: nym-vpn-core
        env:
          SENTRY_DSN: ${{ secrets.VPND_SENTRY_DSN }}
        run: |
          cargo build --release
          ls -la nym-vpn-core/target/release/ || true

      - name: Get rust version used for build
        id: rust-version
        run: |
          echo "rustc=$(rustc -V)" >> $GITHUB_OUTPUT

      - name: Move things around to prepare for upload
        env:
          SRC_BINARY: nym-vpn-core/target/release/
        run: |
          mkdir ${{ env.UPLOAD_DIR_LINUX }}
          cp -vpr ${{ env.SRC_BINARY }}/nym-vpnc ${{ env.UPLOAD_DIR_LINUX }}
          cp -vpr ${{ env.SRC_BINARY }}/nym-vpnd ${{ env.UPLOAD_DIR_LINUX }}
          cp -vpr ${{ env.SRC_BINARY }}/nym-socks5-proxy ${{ env.UPLOAD_DIR_LINUX }}
          cp -vpr ${{ env.SRC_BINARY }}/nym-diagnostic ${{ env.UPLOAD_DIR_LINUX }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.UPLOAD_DIR_LINUX }}
          path: ${{ env.UPLOAD_DIR_LINUX }}
          if-no-files-found: error
          retention-days: 1
