name: build-winfw-windows
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/build-winfw-windows.yml"
      - "nym-windows/**"
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

# https://github.com/actions/runner-images/issues/1794#issuecomment-707217728

jobs:
  build-winfw:
    strategy:
      fail-fast: false
      matrix:
        cpu_arch: [x64, ARM64]
    runs-on: "custom-windows-11"

    steps:
      - name: "Cleanup working directory"
        shell: bash
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true

      - name: Cache winfw
        uses: actions/cache@v6
        id: cache
        with:
          path: nym-vpn-windows/winfw/bin
          key: winfw-${{ matrix.cpu_arch }}-${{ hashFiles('nym-vpn-windows/winfw/src', 'nym-vpn-windows/libshared/src', 'nym-vpn-windows/libwfp/**/src', 'nym-vpn-windows/windows-libraries/src') }}

      - name: Install cargo-get
        if: steps.cache.outputs.cache-hit != 'true'
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-get

      - name: Setup MSBuild.exe
        if: steps.cache.outputs.cache-hit != 'true'
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57

      - name: Install GNU make
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          winget list GnuWin32.Make || winget install --disable-interactivity --accept-source-agreements --id GnuWin32.Make
          echo "${env:ProgramFiles(x86)}\GnuWin32\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Setup VS dev shell
        if: steps.cache.outputs.cache-hit != 'true'
        uses: humbletim/vsdevenv-shell@503210b7b39a7405e534ea93c36a733b93f01087

      - name: Build winfw
        if: steps.cache.outputs.cache-hit != 'true'
        shell: vsdevenv x64 pwsh {0}
        working-directory: nym-vpn-core
        run: make -f Windows.mk winfw CPU_ARCH=${{ matrix.cpu_arch == 'ARM64' && 'ARM64' || 'AMD64' }} RELEASE=1 PWSH=1

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: winfw_${{ matrix.cpu_arch }}
          path: |
            ${{ github.workspace }}/nym-vpn-windows/winfw/bin/${{ matrix.cpu_arch }}-Release/winfw.dll
            ${{ github.workspace }}/nym-vpn-windows/winfw/bin/${{ matrix.cpu_arch }}-Release/winfw.lib
          if-no-files-found: error
          retention-days: 1
