name: build-wireguard-go-ios
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [opened]
    paths:
      - "wireguard/**"
      - ".github/workflows/build-wireguard-go-ios.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-libwg-ios:
    runs-on: custom-macos-15
    timeout-minutes: 5

    steps:
      - name: "Cleanup working directory"
        shell: bash
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout nym-vpn-client
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Cache libwg
        uses: actions/cache@v6
        id: cache
        with:
          path: build/lib
          key: libwg-ios-go${{ env.GOLANG_VERSION }}-${{ hashFiles('.github/workflows/build-wireguard-go-ios.yml', 'wireguard/libwg/**/*.{go,diff,mod,h}', 'wireguard/build-wireguard-go.sh') }}

      - name: Install Go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache-dependency-path: wireguard/libwg/go.sum

      - name: Build wireguard
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./wireguard/build-wireguard-go.sh --ios

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: wireguard-go_ios_universal
          path: build/lib
          if-no-files-found: error
          retention-days: 1
