name: build-wireguard-go-windows
on:
  pull_request:
    types: [opened]
    paths:
      - "wireguard/**"
      - ".github/workflows/build-wireguard-go-windows.yml"
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  AGENT_ISSELFHOSTED: 1 # https://github.com/actions/setup-go/issues/432

jobs:
  build-libwg-windows:
    strategy:
      fail-fast: false
      matrix:
        cpu_arch: [x64, ARM64]

    runs-on: "custom-windows-11"

    steps:
      - name: "Cleanup working directory"
        uses: ./.github/actions/cleanup

      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Cache libwg
        uses: actions/cache@v6
        id: cache
        with:
          path: build/lib
          key: libwg-windows-${{ matrix.cpu_arch || 'x64' }}-go${{ env.GOLANG_VERSION }}-${{ hashFiles('.github/workflows/build-wireguard-go-windows.yml', 'wireguard/libwg/**/*.{go,diff,mod,h}', 'wireguard/build-wireguard-go.sh') }}

      - name: Install Go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache-dependency-path: wireguard/libwg/go.sum

      - name: Setup msys2
        if: steps.cache.outputs.cache-hit != 'true'
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          update: true
          msystem: CLANG64
          install: mingw-w64-clang-x86_64-clang

      - name: Install x64 msys2 packages
        if: steps.cache.outputs.cache-hit != 'true' && (matrix.cpu_arch == '' || matrix.cpu_arch == 'x64')
        shell: msys2 {0}
        run: |
          pacman -S --needed --noconfirm mingw-w64-x86_64-binutils mingw-w64-x86_64-gcc

      - name: Install ARM64 msys2 packages
        if: steps.cache.outputs.cache-hit != 'true' && matrix.cpu_arch == 'ARM64'
        shell: msys2 {0}
        run: |
          pacman -S --needed --noconfirm mingw-w64-clang-aarch64-clang mingw-w64-clang-aarch64-headers mingw-w64-clang-aarch64-crt-git

      - name: Install GNU make
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          winget list GnuWin32.Make || winget install --disable-interactivity --accept-source-agreements --id GnuWin32.Make
          echo "${env:ProgramFiles(x86)}\GnuWin32\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Install cargo-get
        if: steps.cache.outputs.cache-hit != 'true'
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-get

      - name: Setup VS dev shell
        if: steps.cache.outputs.cache-hit != 'true'
        uses: humbletim/vsdevenv-shell@503210b7b39a7405e534ea93c36a733b93f01087

      - name: Build wireguard
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        shell: vsdevenv x64 pwsh {0}
        working-directory: nym-vpn-core
        run: make -f Windows.mk libwg CPU_ARCH=${{ matrix.cpu_arch == 'ARM64' && 'ARM64' || 'AMD64' }} PWSH=1

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: wireguard-go_${{ matrix.cpu_arch == 'ARM64' && 'aarch64' || 'x86_64' }}-pc-windows-msvc
          path: build/lib
          if-no-files-found: error
          retention-days: 1
