name: build-wireguard-go-android
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - "wireguard/**"
      - ".github/workflows/build-wireguard-go-android.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: 'ubuntu-22.04'

    steps:
      - name: Checkout nym-vpn-client
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build wireguard
        run: ./wireguard/build-wireguard-go.sh --android --docker

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-go_aarch64-linux-android
          path: build/lib/aarch64-linux-android
          retention-days: 1
