name: build-nym-vpn-core-mac
on:
  pull_request:
    types: [opened]
    paths:
      - ".github/workflows/build-nym-vpn-core-mac.yml"
  workflow_dispatch:
  workflow_call:
    secrets:
      VPND_SENTRY_DSN:
        required: true

env:
  CARGO_TERM_COLOR: always
  UPLOAD_DIR_MAC: ${{ github.workspace }}/mac_artifacts

jobs:
  build-wireguard-go-mac:
    uses: ./.github/workflows/build-wireguard-go-mac.yml

  build-mac:
    if: github.actor != 'dependabot[bot]'
    needs: build-wireguard-go-mac
    runs-on: custom-macos-15
    timeout-minutes: 60
    outputs:
      UPLOAD_DIR_MAC: ${{ env.UPLOAD_DIR_MAC }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
          targets: x86_64-apple-darwin aarch64-apple-darwin

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-swift
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-swift
          version: 0.11.0

      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-edit

      - name: Get workspace version
        id: workspace-version
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: workspace.package.version --entry nym-vpn-core

      - name: Append timestamp if it's a dev version
        run: ./scripts/append-timestamp-to-version.sh nym-vpn-core/Cargo.toml ${{ steps.workspace-version.outputs.metadata }}

      - name: Download wireguard-go artifacts
        uses: actions/download-artifact@v8
        with:
          name: wireguard-go_apple_universal
          path: build/lib/universal-apple-darwin

      - name: Build binaries
        working-directory: nym-vpn-core
        env:
          SENTRY_DSN: ${{ secrets.VPND_SENTRY_DSN }}
        run: |
          make -f macOS.mk
          cp -v -R crates/nym-vpn-rpc-uniffi/NymVPNRpc ${{ env.UPLOAD_DIR_MAC }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: mac_artifacts
          path: ${{ env.UPLOAD_DIR_MAC }}
          if-no-files-found: error
          retention-days: 1
