name: build-wireguard-go-ios
on: [workflow_dispatch, workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout nym-vpn-client
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: "**/go.sum"

      - name: Build wireguard
        run: ./wireguard/build-wireguard-go.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-go_ios_universal
          path: |
            build/lib/universal-apple-darwin
          retention-days: 10
