name: build-nym-vpn-core-mac
on: [workflow_dispatch, workflow_call]

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET: release
  WG_GO_LIB_PATH: ${{ github.workspace }}/lib
  WG_GO_LIB_NAME: wireguard-go_apple_universal
  UPLOAD_DIR_MAC: mac_artifacts

jobs:
  build-wireguard-go-mac:
    uses: ./.github/workflows/build-wireguard-go-mac.yml

  build-mac:
    needs: build-wireguard-go-mac
    runs-on: macos-14
    outputs:
      UPLOAD_DIR_MAC: ${{ env.UPLOAD_DIR_MAC }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: brndnmtthws/rust-action-rustup@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install extra arch apple
        run: |
          rustup target add x86_64-apple-darwin

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download wireguard-go artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WG_GO_LIB_NAME }}
          path: ${{ env.WG_GO_LIB_PATH }}

      - name: Build nym-vpn-core (native)
        env:
          RUSTFLAGS: "-L ${{ env.WG_GO_LIB_PATH }}"
        run: |
          cargo build --${{ env.CARGO_TARGET }}
          ls -la target/release/ || true

      - name: Build nym-vpn-core (x86_64)
        env:
          RUSTFLAGS: "-L ${{ env.WG_GO_LIB_PATH }}"
        run: |
          cargo build --${{ env.CARGO_TARGET }} --target x86_64-apple-darwin
          ls -la target/x86_64-apple-darwin/release/ || true

      - name: Create universal binaries and prepare for upload
        env:
          SRC_NATIVE_BINARY: target/${{ env.CARGO_TARGET }}/
          SRC_X86_64_BINARY: target/x86_64-apple-darwin/${{ env.CARGO_TARGET }}/
        run: |
          mkdir ${{ env.UPLOAD_DIR_MAC }}
          lipo -create -output ${{ env.UPLOAD_DIR_MAC }}/nym-vpn-cli ${{ env.SRC_NATIVE_BINARY }}/nym-vpn-cli ${{ env.SRC_X86_64_BINARY }}/nym-vpn-cli
          lipo -create -output ${{ env.UPLOAD_DIR_MAC }}/nym-vpnc ${{ env.SRC_NATIVE_BINARY }}/nym-vpnc ${{ env.SRC_X86_64_BINARY }}/nym-vpnc
          lipo -create -output ${{ env.UPLOAD_DIR_MAC }}/nym-vpnd ${{ env.SRC_NATIVE_BINARY }}/nym-vpnd ${{ env.SRC_X86_64_BINARY }}/nym-vpnd
          lipo -create -output ${{ env.UPLOAD_DIR_MAC }}/nym-gateway-probe ${{ env.SRC_NATIVE_BINARY }}/nym-gateway-probe ${{ env.SRC_X86_64_BINARY }}/nym-gateway-probe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.UPLOAD_DIR_MAC }}
          path: ${{ env.UPLOAD_DIR_MAC }}
          retention-days: 1
