name: build-wireguard-go-ios
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [opened]
    paths:
      - "wireguard/**"
      - ".github/workflows/build-wireguard-go-ios.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: custom-macos-15
    timeout-minutes: 5

    steps:
      - name: Checkout nym-vpn-client
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ vars.REQUIRED_GOLANG_VERSION }}
          cache: false

      - name: Cache Go modules
        uses: actions/cache@v5
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build wireguard
        run: ./wireguard/build-wireguard-go.sh --ios

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-go_ios_universal
          path: |
            build/lib/aarch64-apple-ios
            build/lib/aarch64-apple-ios-sim
            build/lib/x86_64-apple-ios
          if-no-files-found: error
          retention-days: 10
