name: build-wireguard-go-android
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - "wireguard/**"
      - ".github/workflows/build-wireguard-go-android.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: arc-linux-latest

    steps:
      - name: Checkout nym-vpn-client
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ vars.REQUIRED_GOLANG_VERSION }}
          cache-dependency-path: wireguard/libwg/go.sum

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ vars.REQUIRED_NDK_VERSION }}
          add-to-path: false

      - name: Set env
        shell: bash
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "NDK_TOOLCHAIN_DIR=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

      - name: Build wireguard
        run: ./wireguard/build-wireguard-go.sh --android

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-go_aarch64-linux-android
          path: build/lib/aarch64-linux-android
          if-no-files-found: error
          retention-days: 1
