name: build-nym-vpn-core-android
on:
  pull_request:
    types: [opened]
    paths:
      - ".github/workflows/build-nym-vpn-core-android.yml"
  workflow_dispatch:
  workflow_call:
    outputs:
      RUST_VERSION:
        value: ${{ jobs.build-android.outputs.RUST_VERSION }}

env:
  CARGO_TERM_COLOR: always
  UPLOAD_DIR_ANDROID: android_artifacts

jobs:
  build-wireguard-go-android:
    uses: ./.github/workflows/build-wireguard-go-android.yml

  build-android:
    if: github.actor != 'dependabot[bot]'
    needs: build-wireguard-go-android
    runs-on: arc-linux-latest
    outputs:
      UPLOAD_DIR_ANDROID: ${{ env.UPLOAD_DIR_ANDROID }}
      RUST_VERSION: ${{ steps.rust-version.outputs.rustc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y rsync

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: aarch64-linux-android,x86_64-linux-android

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: false

      - name: Set env
        shell: bash
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "NDK_TOOLCHAIN_DIR=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

      - name: Install cargo-ndk
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-ndk

      - name: Install cargo-license
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-license

      - name: Get workspace version
        id: workspace-version
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: workspace.package.version --entry nym-vpn-core

      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-edit

      - name: Append timestamp if it's a dev version
        run: ./scripts/append-timestamp-to-version.sh nym-vpn-core/Cargo.toml ${{ steps.workspace-version.outputs.metadata }}

      - name: Download wireguard-go artifacts (aarch64)
        uses: actions/download-artifact@v8
        with:
          name: wireguard-go_aarch64-linux-android
          path: build/lib/aarch64-linux-android

      - name: Download wireguard-go artifacts (x86_64)
        uses: actions/download-artifact@v8
        with:
          name: wireguard-go_x86_64-linux-android
          path: build/lib/x86_64-linux-android

      - name: Build nym-vpn-core for android
        working-directory: nym-vpn-core
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          VPNLIB_SENTRY_DSN: ${{ secrets.VPND_SENTRY_DSN }}
        run: |
          make -f Android.mk RELEASE=true

      - name: Get rust version used for build
        id: rust-version
        run: |
          echo "rustc=$(rustc -V)" >> $GITHUB_OUTPUT

      - name: Move things around to prepare for upload
        run: |
          mkdir ${{ env.UPLOAD_DIR_ANDROID }}
          mkdir ${{ env.UPLOAD_DIR_ANDROID }}/arm64-v8a
          mkdir ${{ env.UPLOAD_DIR_ANDROID }}/x86_64
          cp nym-vpn-android/core/src/main/jniLibs/arm64-v8a/libnym_vpn_lib.so ${{ env.UPLOAD_DIR_ANDROID }}/arm64-v8a/
          cp nym-vpn-android/core/src/main/jniLibs/arm64-v8a/libnym_vpn_lib_types.so ${{ env.UPLOAD_DIR_ANDROID }}/arm64-v8a/
          cp nym-vpn-android/core/src/main/jniLibs/x86_64/libnym_vpn_lib.so ${{ env.UPLOAD_DIR_ANDROID }}/x86_64/
          cp nym-vpn-android/core/src/main/jniLibs/x86_64/libnym_vpn_lib_types.so ${{ env.UPLOAD_DIR_ANDROID }}/x86_64/

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.UPLOAD_DIR_ANDROID }}
          path: ${{ env.UPLOAD_DIR_ANDROID }}
          if-no-files-found: error
          retention-days: 1
