name: build-nym-vpn-core-ios
on:
  pull_request:
    types: [opened]
    paths:
      - ".github/workflows/build-nym-vpn-core-ios.yml"
  workflow_dispatch:
  workflow_call:
    outputs:
      RUST_VERSION:
        value: ${{ jobs.build-ios.outputs.RUST_VERSION }}

env:
  IPHONEOS_DEPLOYMENT_TARGET: 16.0
  CARGO_TERM_COLOR: always
  UPLOAD_DIR_IOS: ios_artifacts

jobs:
  build-wireguard-go-ios:
    uses: ./.github/workflows/build-wireguard-go-ios.yml

  build-ios:
    if: github.actor != 'dependabot[bot]'
    needs: build-wireguard-go-ios
    runs-on: custom-macos-15
    timeout-minutes: 30
    outputs:
      UPLOAD_DIR_IOS: ${{ env.UPLOAD_DIR_IOS }}
      RUST_VERSION: ${{ steps.rust-version.outputs.rustc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
          targets: aarch64-apple-ios aarch64-apple-ios-sim

      - name: Install cargo-swift
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-swift
          version: 0.11.0

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get workspace version
        id: workspace-version
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: workspace.package.version --entry nym-vpn-core

      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-edit

      - name: Append timestamp if it's a dev version
        run: ./scripts/append-timestamp-to-version.sh nym-vpn-core/Cargo.toml ${{ steps.workspace-version.outputs.metadata }}

      - name: Download wireguard-go artifacts
        uses: actions/download-artifact@v8
        with:
          name: wireguard-go_ios_universal
          path: build/lib

      - name: Build nym-vpn-lib
        working-directory: nym-vpn-core
        env:
          VPNLIB_SENTRY_DSN: ${{ secrets.VPND_SENTRY_DSN }}
        run: |
          make -f iOS.mk RELEASE=1

      - name: Get rust version used for build
        id: rust-version
        run: |
          echo "rustc=$(rustc -V)" >> $GITHUB_OUTPUT

      - name: Move things around to prepare for upload
        env:
          SRC_DIR: nym-vpn-core/crates/nym-vpn-lib-uniffi/NymVPNLib
        run: |
          mkdir ${{ env.UPLOAD_DIR_IOS }}
          cp -vpr ${{ env.SRC_DIR }} ${{ env.UPLOAD_DIR_IOS }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.UPLOAD_DIR_IOS }}
          path: ${{ env.UPLOAD_DIR_IOS }}
          if-no-files-found: error
          retention-days: 1
