name: build-nym-vpn-core-windows
on:
  pull_request:
    types: [opened]
    paths:
      - ".github/workflows/build-nym-vpn-core-windows.yml"
  workflow_dispatch:
  workflow_call:
    secrets:
      VPND_SENTRY_DSN:
        required: true
    outputs:
      RUST_VERSION:
        value: ${{ jobs.build-windows.outputs.RUST_VERSION }}
      UPLOAD_DIR_WINDOWS:
        value: ${{ jobs.build-windows.outputs.UPLOAD_DIR_WINDOWS }}

env:
  CARGO_TERM_COLOR: always
  LIBS_PATH: build/lib/x86_64-pc-windows-msvc
  WINFW_PATH: build/winfw/x64-Release
  WINTUN_DIST_DIR: wintun-dist
  UPLOAD_DIR_WINDOWS: windows_artifacts

jobs:
  build-wireguard-go-windows:
    uses: ./.github/workflows/build-wireguard-go-windows.yml

  build-winfw-windows:
    uses: ./.github/workflows/build-winfw-windows.yml

  build-windows:
    if: github.actor != 'dependabot[bot]'
    needs: [build-wireguard-go-windows, build-winfw-windows]
    runs-on: custom-windows-11
    outputs:
      UPLOAD_DIR_WINDOWS: ${{ env.UPLOAD_DIR_WINDOWS }}
      RUST_VERSION: ${{ steps.rust-version.outputs.rustc }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Install GNU make
        run: |
          winget list GnuWin32.Make || winget install --disable-interactivity --accept-source-agreements --id GnuWin32.Make
          echo "${env:ProgramFiles(x86)}\GnuWin32\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ vars.REQUIRED_RUSTC_VERSION }}
          components: rustfmt, clippy

      - name: Get workspace version
        id: workspace-version
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: workspace.package.version --entry nym-vpn-core

      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-edit

      - name: Install cargo-get
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-get

      - name: Append timestamp if it's a dev version
        shell: bash
        run: ./scripts/append-timestamp-to-version.sh nym-vpn-core/Cargo.toml ${{ steps.workspace-version.outputs.metadata }}

      - name: Download wireguard-go-windows artifacts
        uses: actions/download-artifact@v6
        with:
          name: wireguard-go_x86_64-pc-windows-msvc
          path: ${{ env.LIBS_PATH }}

      - name: Download winfw artifacts
        uses: actions/download-artifact@v6
        with:
          name: winfw
          path: ${{ env.WINFW_PATH }}

      - name: Download wintun
        shell: pwsh
        working-directory: nym-vpn-core
        run: |
          make -f Windows.mk wintun PWSH=1 CPU_ARCH=AMD64 TARGET_DIR="${{ github.workspace }}/${{ env.WINTUN_DIST_DIR }}"

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build nym-vpn-core
        working-directory: nym-vpn-core
        env:
          SENTRY_DSN: ${{ secrets.VPND_SENTRY_DSN }}
        run: |
          cargo build --release

      - name: Get rust version used for build
        id: rust-version
        run: |
          echo "rustc=$(rustc -V)" >> $GITHUB_OUTPUT

      - name: Move things around to prepare for upload
        shell: bash
        env:
          SRC_BINARY: nym-vpn-core/target/release
        run: |
          echo "moving binaries into ${{ env.UPLOAD_DIR_WINDOWS }}"
          rm -rf ${{ env.UPLOAD_DIR_WINDOWS }} || true
          mkdir ${{ env.UPLOAD_DIR_WINDOWS }}
          cp -vpr ${{ env.SRC_BINARY }}/nym-vpnc.exe ${{ env.UPLOAD_DIR_WINDOWS }}
          cp -vpr ${{ env.SRC_BINARY }}/nym-vpnd.exe ${{ env.UPLOAD_DIR_WINDOWS }}
          cp -vpr ${{ env.LIBS_PATH }}/libwg.dll ${{ env.UPLOAD_DIR_WINDOWS }}
          cp -vpr ${{ env.WINFW_PATH }}/winfw.dll ${{ env.UPLOAD_DIR_WINDOWS }}
          cp -vpr ${{ env.WINTUN_DIST_DIR }}/wintun.dll ${{ env.UPLOAD_DIR_WINDOWS }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.UPLOAD_DIR_WINDOWS }}
          path: ${{ env.UPLOAD_DIR_WINDOWS }}
          if-no-files-found: error
          retention-days: 1
