name: build-wireguard-go-linux
on:
  pull_request:
    types: [opened]
    paths:
      - "wireguard/**"
      - ".github/workflows/build-wireguard-go-linux.yml"
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-libwg:
    strategy:
      matrix:
        include:
          - os: "ubuntu-22.04"
            arch: "x86_64"
          - os: "ubuntu-22.04-arm"
            arch: "aarch64"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout nym-vpn-client
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Cache libwg
        uses: actions/cache@v6
        id: cache
        with:
          path: build/lib
          key: libwg-${{ matrix.os }}-go${{ env.GOLANG_VERSION }}-cachev2-${{ hashFiles('wireguard/libwg/**/*.{go,diff,mod,h}', 'wireguard/build-wireguard-go.sh') }}

      - name: Install system dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Install Go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION}}
          cache-dependency-path: wireguard/libwg/go.sum

      - name: Build wireguard
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./wireguard/build-wireguard-go.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: wireguard-go-${{ matrix.arch }}-linux-unknown
          path: build/lib
          if-no-files-found: error
          retention-days: 1
