name: bump-release-branch

on:
  workflow_dispatch:
    inputs:
      is_release_bump:
        description: "Release 🚀 (drops beta suffix)"
        required: true
        type: boolean
        default: false
      branch:
        description: "Git branch to run against (uses github ref if not set). Unless testing, leave it blank, select the branch from dropdown instead"
        type: string
        required: false
      dry_run:
        description: "Test run that will only print git diff and all changes being made"
        required: true
        type: boolean
        default: true

env:
  CARGO_TERM_COLOR: always
  GIT_USER: NYM CI
  GIT_EMAIL: ci@nymtech.net

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  next-release-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      next_version: ${{ steps.version.outputs.next_version }}
    env:
      GIT_BRANCH: ${{ inputs.branch || github.ref_name }}
    steps:
      - name: Validate input
        run: |
          if [ ! echo "${{ env.GIT_BRANCH }}" | grep -P '^release/.+$' && ! ${{ inputs.dry_run }} ]; then
            echo "::error:: Branch must start with 'release/' (got: ${{ env.GIT_BRANCH }})"
            exit 1
          fi

      - name: Configure git
        run: |
          git config --global user.name "${{ env.GIT_USER }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: ${{ env.GIT_BRANCH }}

      - name: Install cargo-get
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-get

      - name: Compute version
        id: version
        working-directory: nym-vpn-core
        run: |
          CURRENT_VERSION=$(cargo get workspace.package.version)
          echo "::notice:: Current version: $CURRENT_VERSION"

          NEXT_VERSION=$(cargo get workspace.package.version --major --minor --patch --delimiter '.')
          PRE=$(cargo get workspace.package.version --pre)

          # This must not be the case once develop contains "-beta.1" in Cargo.toml
          if [ "$PRE" = "beta" ]; then
            PRE="beta.0"
          elif ! echo "$PRE" | grep -Pq '^beta\.[1-9][0-9]?$'; then
            echo "::error:: Version '$CURRENT_VERSION' does not have a '-beta.*' suffix"
            exit 1
          fi

          # Increment beta version if not a release bump
          if [ "${{ inputs.is_release_bump }}" = "false" ]; then
            SEQ=$(echo "$PRE" | cut -d. -f2)
            SEQ=$(($SEQ + 1))
            NEXT_VERSION="$NEXT_VERSION-beta.$SEQ"
          fi

          echo "::notice:: Next version: $NEXT_VERSION"
          echo "next_version=$NEXT_VERSION" >> "$GITHUB_OUTPUT"

  bump-release-branch:
    needs: next-release-version
    uses: ./.github/workflows/bump-all-platforms.yml
    with:
      branch: ${{ inputs.branch || github.ref_name }}
      version: ${{ needs.next-release-version.outputs.next_version }}
      update_linux_installer: ${{ inputs.is_release_bump }}
      update_changelog: ${{ inputs.is_release_bump }}
      dry_run: ${{ inputs.dry_run }}
