name: ci-nym-vpn-core-macos

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "nym-vpn-core/crates/**"
      - "nym-vpn-core/Cargo.toml"
      - "nym-vpn-core/Cargo.lock"
      - ".github/workflows/ci-nym-vpn-core-macos.yml"
  workflow_dispatch:

env:
  CI_TESTING: true
  CARGO_TERM_COLOR: always
  AGENT_ISSELFHOSTED: 1 # https://github.com/actions/setup-go/issues/432
  RUSTC_WRAPPER: sccache
  SCCACHE_REDIS_ENDPOINT: ${{ secrets.SCCACHE_REDIS_OUTSIDE_CLUSTER_ENDPOINT }}
  SCCACHE_REDIS_PASSWORD: ${{ secrets.SCCACHE_REDIS_PASSWORD }}
  SCCACHE_REDIS_EXPIRATION: 86400

jobs:
  build-wireguard-go-mac:
    uses: ./.github/workflows/build-wireguard-go-mac.yml

  build:
    runs-on: custom-macos-15
    needs: build-wireguard-go-mac
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - uses: mozilla-actions/sccache-action@v0.0.10

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION}}
          cache-dependency-path: wireguard/libwg/go.sum

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12" # 3.21.12: the version on ubuntu 24.04. Don't change this!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: wireguard-go_apple_universal
          path: build/lib

      - name: rustfmt check
        working-directory: nym-vpn-core
        run: |
          cargo fmt --check --all

      - name: Clippy
        working-directory: nym-vpn-core
        run: |
          cargo clippy --workspace --locked -- -Dwarnings

      - name: Build and test
        working-directory: nym-vpn-core
        run: |
          cargo build --workspace --locked
          cargo test --workspace --locked --exclude nym-ifconfig
