name: ci-nym-ifconfig-macos
on:
  pull_request:
    paths:
      - .github/workflows/ci-nym-ifconfig-macos.yml
      - "crates/nym-ifconfig/**/*.rs"
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Setup sccache
        uses: ./.github/actions/setup-sccache

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Build
        working-directory: nym-vpn-core
        run: cargo build --package nym-ifconfig --locked

      - name: Test
        working-directory: nym-vpn-core
        run: sudo cargo test --package nym-ifconfig
