name: ci-nym-ifconfig-macos
on:
  pull_request:
    paths:
      - .github/workflows/ci-nym-ifconfig-macos.yml
      - "crates/nym-ifconfig/**/*.rs"
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ vars.REQUIRED_RUSTC_VERSION }}

      - uses: mozilla-actions/sccache-action@v0.0.10
      - name: Set Rust caching env vars
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Build
        working-directory: nym-vpn-core
        run: cargo build --package nym-ifconfig --locked

      - name: Test
        working-directory: nym-vpn-core
        run: sudo cargo test --package nym-ifconfig
