name: ci-nym-vpn-desktop-js

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "nym-vpn-desktop/src/**"
      - "nym-vpn-desktop/package.json"
      - "nym-vpn-desktop/index.html"
      - "nym-vpn-desktop/.eslintrc.cjs"
      - "nym-vpn-desktop/vite.config.ts"
      - ".github/workflows/ci-nym-vpn-desktop-js.yml"

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            nym-vpn-desktop
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nym-vpn-desktop/package-lock.json
      - name: Install dependencies
        working-directory: nym-vpn-desktop
        run: npm ci
      - name: Typecheck
        working-directory: nym-vpn-desktop
        run: npm run tscheck
      - name: Check lint
        working-directory: nym-vpn-desktop
        run: npm run lint
      - name: Check formatting
        working-directory: nym-vpn-desktop
        run: npm run fmt:check
      #      - name: Run tests
      #        working-directory: nym-vpn-desktop
      #        run: npm run test
      - name: Check build
        working-directory: nym-vpn-desktop
        run: npm run build
