name: ci-nym-vpn-app-macos

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/ci-nym-vpn-app-macos.yml"
      - "nym-vpn-apple/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: custom-macos-15
    steps:
      - name: "Cleanup working directory"
        uses: ./.github/actions/cleanup

      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup sccache
        uses: ./.github/actions/setup-sccache

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
          targets: x86_64-apple-darwin aarch64-apple-darwin

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12" # 3.21.12: the version on ubuntu 24.04. Don't change this!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-swift
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-swift
          version: ${{ env.CARGO_SWIFT_VERSION }}

      - name: Install xcbeautify
        run: |
          brew install xcbeautify

      - name: Add stubs for distributed binaries
        run: |
          touch nym-vpn-apple/NymVPND/nym-setup
          touch nym-vpn-apple/NymVPND/nym-vpnd
          touch nym-vpn-apple/NymVPND/nym-socks5-proxy

      - name: Add stubs for unused packages
        working-directory: nym-vpn-apple
        run: |
          echo "📦 Adding stubs for unused packages..."
          rm -rf NymVPNLib || true
          mkdir NymVPNLib || true
          cd NymVPNLib
          swift package init --type library --name NymVPNLib --disable-xctest --disable-swift-testing
          echo "✅ Stubs added successfully."

      - name: Build rpc-swift-package
        run: |
          make -C nym-vpn-core -f macOS.mk rpc-swift-package RELEASE="false"
          mv "nym-vpn-core/crates/nym-vpn-rpc-uniffi/NymVPNRpc" "nym-vpn-apple/NymVPNRpc"

      - name: Apple unit tests
        uses: ./.github/workflows/apple/tests
        with:
          account-report-path: ${{ github.workspace }}/account-report.md

      - name: Build macOS app
        working-directory: nym-vpn-apple
        run: |
          set -o pipefail

          xcodebuild \
            -workspace "NymVPN.xcworkspace" \
            -scheme "NymVPNDaemon" \
            -configuration "Debug" \
            -destination "platform=macOS" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build | xcbeautify --renderer github-actions
