name: ci-nym-vpn-core-ios

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - "nym-vpn-core/crates/**"
      - "nym-vpn-core/Cargo.toml"
      - "nym-vpn-core/Cargo.lock"
      - ".github/workflows/ci-nym-vpn-core-ios.yml"
  workflow_dispatch:

env:
  IPHONEOS_DEPLOYMENT_TARGET: 16.0
  CARGO_TERM_COLOR: always
  AGENT_ISSELFHOSTED: 1 # https://github.com/actions/setup-go/issues/432

jobs:
  build-wireguard-go-ios:
    uses: ./.github/workflows/build-wireguard-go-ios.yml

  build:
    runs-on: custom-macos-15
    needs: [build-wireguard-go-ios]
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Setup sccache
        uses: ./.github/actions/setup-sccache

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
          targets: aarch64-apple-ios

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12" # 3.21.12: the version on ubuntu 24.04. Don't change this!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: wireguard-go_ios_universal
          path: build/lib

      - name: rustfmt check
        working-directory: nym-vpn-core
        run: |
          cargo fmt --check --all

      - name: Clippy
        working-directory: nym-vpn-core
        run: |
          cargo clippy --target aarch64-apple-ios -p nym-vpn-lib-uniffi --locked -- -Dwarnings

      - name: Build
        working-directory: nym-vpn-core
        run: |
          cargo build --profile ci --target aarch64-apple-ios -p nym-vpn-lib-uniffi --locked

      - name: Generate uniffi
        working-directory: nym-vpn-core
        run: |
          cargo run -p uniffi-bindgen generate \
            --library target/aarch64-apple-ios/debug/libnym_vpn_lib_uniffi.a  \
            --config crates/nym-vpn-lib-uniffi/uniffi.toml \
            --language swift --out-dir build -n
