name: ci-nym-vpn-app-js

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ci-nym-vpn-app-js.yml'
      - 'nym-vpn-app/**'
  workflow_dispatch:

jobs:
  check:
    if: github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        os: [arc-linux-latest, custom-windows-11]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            nym-vpn-app
            crowdin-configs

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: nym-vpn-app/package-lock.json

      - name: Install dependencies
        working-directory: nym-vpn-app
        run: npm ci

      - name: Install Crowdin CLI
        run: |
          npm install -g @crowdin/cli

      - name: Verify Crowdin install
        run: |
          crowdin --version

      - name: Download translations from Crowdin (Linux)
        if: matrix.os == 'arc-linux-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: |
          crowdin download translations \
            --config crowdin-configs/linux-windows.yml \
            --project-id "$CROWDIN_PROJECT_ID" \
            --token "$CROWDIN_PERSONAL_TOKEN"

      - name: Download translations from Crowdin (Windows)
        if: matrix.os == 'custom-windows-11'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        shell: pwsh
        run: |
          crowdin download translations `
            --config crowdin-configs/linux-windows.yml `
            --project-id "$env:CROWDIN_PROJECT_ID" `
            --token "$env:CROWDIN_PERSONAL_TOKEN"

      - name: Typecheck
        working-directory: nym-vpn-app
        run: npm run tscheck

      - name: Check lint
        working-directory: nym-vpn-app
        run: npm run lint

      - name: Check formatting
        working-directory: nym-vpn-app
        run: npm run fmt:check

      #      - name: Run tests
      #        working-directory: nym-vpn-app
      #        run: npm run test

      - name: Check build
        working-directory: nym-vpn-app
        run: npm run build
