name: ci-nym-vpn-core-windows

on:
  #push:
  pull_request:
    paths:
      - "nym-vpn-core/**"
      - "nym-vpn-windows/**"
      - ".github/workflows/ci-nym-vpn-core-windows.yml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  AGENT_ISSELFHOSTED: 1 # https://github.com/actions/setup-go/issues/432

jobs:
  build-wireguard-go:
    uses: ./.github/workflows/build-wireguard-go-windows.yml

  build:
    runs-on: custom-windows-11
    needs: build-wireguard-go

    steps:
      - name: "Cleanup working directory"
        shell: bash
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Support longpaths on windows
        run: git config --system core.longpaths true

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ vars.REQUIRED_RUSTC_VERSION }}
          components: rustfmt, clippy

      - name: Install target i686-pc-windows-msvc
        run: |
          rustup target add i686-pc-windows-msvc

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.REQUIRED_GOLANG_VERSION }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12" # 3.21.12: the version on ubuntu 24.04. Don't change this!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GNU make
        run: |
          winget list GnuWin32.Make || winget install --disable-interactivity --id GnuWin32.Make
          echo "${env:ProgramFiles(x86)}\GnuWin32\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wireguard-go_x86_64-pc-windows-msvc
          path: build/lib/x86_64-pc-windows-msvc
    
      - name: 'Test: list files'
        shell: bash
        run: |
          ls -la build
          ls -la build/lib
          ls -la build/lib/x86_64-pc-windows-msvc

      - name: Build Windows dependencies
        working-directory: nym-vpn-core
        run: make -f Windows.mk winfw CPU_ARCH=amd64

      - name: rustfmt check
        working-directory: nym-vpn-core
        run: |
          cargo fmt --check --all

      - name: Clippy
        working-directory: nym-vpn-core
        run: |
          cargo clippy --workspace --exclude nym-gateway-probe --locked -- -Dwarnings

      - name: Build
        working-directory: nym-vpn-core
        run: |
          cargo build --verbose --workspace --exclude nym-gateway-probe --locked

      - name: Run tests
        working-directory: nym-vpn-core
        run: |
          cargo test --verbose --workspace --exclude nym-gateway-probe --locked
