name: ci-nym-vpn-app-js

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ci-nym-vpn-app-js.yml'
      - 'nym-vpn-app/**'
  workflow_dispatch:

jobs:
  check:
    if: github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        os: [arc-linux-latest, custom-windows-11]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            nym-vpn-app

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: nym-vpn-app/package-lock.json

      - name: Install dependencies
        working-directory: nym-vpn-app
        run: npm ci

      - name: Update localizations Crowdin (Ubuntu)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: |
          # Install Crowdin CLI Debian package
          wget -qO - https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
          echo "deb https://artifacts.crowdin.com/repo/deb/ /" | sudo tee /etc/apt/sources.list.d/crowdin.list
          sudo apt-get update
          sudo apt-get install -y crowdin

          # Verify installation
          crowdin --version || (echo "crowdin cli install failed" && exit 1)

          # Download translations using the same config and tokens
          crowdin download translations \
            --config crowdin-configs/linux-windows.yml \
            --project-id "$CROWDIN_PROJECT_ID" \
            --token "$CROWDIN_PERSONAL_TOKEN"

      - name: Typecheck
        working-directory: nym-vpn-app
        run: npm run tscheck

      - name: Check lint
        working-directory: nym-vpn-app
        run: npm run lint

      - name: Check formatting
        working-directory: nym-vpn-app
        run: npm run fmt:check

      #      - name: Run tests
      #        working-directory: nym-vpn-app
      #        run: npm run test

      - name: Check build
        working-directory: nym-vpn-app
        run: npm run build
