name: ci-nym-vpn-core-linux

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "nym-vpn-core/crates/**"
      - "nym-vpn-core/Cargo.toml"
      - "nym-vpn-core/Cargo.lock"
      - ".github/workflows/ci-nym-vpn-core-linux.yml"
  workflow_dispatch:

env:
  CI_TESTING: true
  CARGO_TERM_COLOR: always
  AGENT_ISSELFHOSTED: 1 # https://github.com/actions/setup-go/issues/432

jobs:
  build-wireguard-go-linux:
    uses: ./.github/workflows/build-wireguard-go-linux.yml

  build:
    runs-on: arc-linux-latest
    needs: build-wireguard-go-linux

    steps:
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev libmnl-dev libnftnl-dev protobuf-compiler git curl gcc g++ make unzip jq

      - name: Checkout repo
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Setup sccache
        uses: ./.github/actions/setup-sccache

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12" # 3.21.12: the version on ubuntu 24.04. Don't change this!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: wireguard-go_x86_64-linux-unknown
          path: build/lib

      - name: rustfmt check
        working-directory: nym-vpn-core
        run: |
          cargo fmt --check --all

      - name: Clippy
        working-directory: nym-vpn-core
        run: |
          cargo clippy --workspace --locked -- -Dwarnings

      - name: Build
        working-directory: nym-vpn-core
        run: |
          cargo build --profile ci --workspace --locked

      - name: Build tests
        working-directory: nym-vpn-core
        run: |
          CARGO_OUTPUT=$(cargo test --profile ci --no-run --workspace --locked --message-format json)

          NYM_CONNECTION_MONITOR_TESTS_BIN=$(echo "$CARGO_OUTPUT" | jq --raw-output 'select(.reason == "compiler-artifact" and .target.name == "nym_connection_monitor" and .executable != null) | .executable')

          echo "Found test binary for nym-connection-monitor: $NYM_CONNECTION_MONITOR_TESTS_BIN"
          sudo setcap 'cap_net_raw+ep' $NYM_CONNECTION_MONITOR_TESTS_BIN

      - name: Run tests
        working-directory: nym-vpn-core
        run: |
          cargo test --profile ci --workspace --locked --exclude nym-ifconfig
