name: ci-nym-vpn-core-cargo-deny
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "nym-vpn-core/**/Cargo.lock"
      - "nym-vpn-core/**/Cargo.toml"
      - "nym-vpn-core/deny.toml"
      - ".github/workflows/ci-nym-vpn-core-cargo-deny.yml"
  workflow_dispatch:
jobs:
  cargo-deny:
    runs-on: arc-linux-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install cargo-deny
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-deny

      - name: Run cargo-deny
        run: cargo deny --manifest-path ./nym-vpn-core/Cargo.toml --locked --all-features check licenses bans sources
