name: ci-nym-vpn-core-windows

on:
  # push:
  pull_request:
    paths:
      - "nym-vpn-core/**"
      - "nym-vpn-windows/**"
      - ".github/workflows/ci-nym-vpn-core-windows.yml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  AGENT_ISSELFHOSTED: 1 # https://github.com/actions/setup-go/issues/432

jobs:
  build:
    runs-on: custom-windows-11

    steps:
      - name: "Cleanup working directory"
        shell: bash
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Support longpaths on windows
        run: git config --system core.longpaths true

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85
          components: rustfmt, clippy

      - name: Install target i686-pc-windows-msvc
        run: |
          rustup target add i686-pc-windows-msvc

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12" # 3.21.12: the version on ubuntu 24.04. Don't change this!
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          update: false
          msystem: MINGW64
          install: mingw-w64-x86_64-clang

      - name: Install GNU make
        run: |
          winget list GnuWin32.Make || winget install --disable-interactivity --id GnuWin32.Make
          echo "${env:ProgramFiles(x86)}\GnuWin32\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Build Windows dependencies
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        working-directory: nym-vpn-core
        run: make -f Windows.mk winfw libwg CPU_ARCH=amd64

      - name: rustfmt check
        working-directory: nym-vpn-core
        run: |
          cargo fmt --check --all

      - name: Build
        working-directory: nym-vpn-core
        run: |
          cargo build --verbose --workspace --exclude nym-gateway-probe --locked

      - name: Run tests
        working-directory: nym-vpn-core
        run: |
          cargo test --verbose --workspace --exclude nym-gateway-probe --locked

      - name: Clippy
        working-directory: nym-vpn-core
        run: |
          cargo clippy --workspace --exclude nym-gateway-probe --locked -- -Dwarnings
