name: create-release-nym-vpn-core

on:
  workflow_dispatch:

jobs:
  check_admin_permission:
    runs-on: ubuntu-latest
    outputs:
      is_admin: ${{ steps.check.outputs.is_admin }}

    steps:
      - name: Check if user has admin access
        id: check
        run: |
          user_role=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission" \
            | jq -r '.permission')

          if [ "$user_role" == "admin" ]; then
            echo "User ${{ github.actor }} is an admin."
            echo "is_admin=true" >> $GITHUB_ENV
          else
            echo "User ${{ github.actor }} is not an admin."
            echo "is_admin=false" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_release:
    if: needs.check_admin_permission.outputs.is_admin == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create a new branch
        id: create_branch
        run: |
          BRANCH_NAME="release-nym-vpn-core-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Run release script
        run: |
          ./scripts/create-nym-vpn-core-release.sh

      - name: Run bump to dev version script
        run: |
          ./scripts/bump-nym-vpn-core-to-next-dev-version.sh

      # - name: Commit bumped version
      #   run: |
      #     git add .
      #     git commit -m "Bump version to next dev version"
          # git push origin ${{ env.branch_name }}

      - name: Open a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.branch_name }}
          title: "Release: ${{ env.branch_name }}"
          body: "Automated PR for the release."

      # - name: Push the new branch and tags
      #   run: |
      #     git push origin ${{ env.branch_name }}
      #     git push --tags

      # - name: Commit and push the bumped version
      #   run: |
      #     git add .
      #     git commit -m "Bump version to next dev version"
      #     git push origin ${{ env.branch_name }}

      # - name: Update PR with bumped version
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     branch: ${{ env.branch_name }}
      #     title: "Release: ${{ env.branch_name }} (Bumped)"
      #     body: "Automated PR with the bumped version."
      #     committer: "GitHub <noreply@github.com>"
      #     author: "GitHub Actions <actions@github.com>"

