name: crowdin-macos-ios-upload

on:
  push:
    branches:
      - develop
    paths: "nym-vpn-apple/NymVPN/Resources/Localizable.xcstrings"
  workflow_dispatch:

jobs:
  crowdin-upload:
    runs-on: arc-linux-latest-dind

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

        with:
          fetch-depth: 1
      - name: crowdin action
        uses: crowdin/github-action@v3
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
          config: "crowdin-configs/macos-ios.yml"
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
