name: cut-release-branch

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Enter release name (🏔️)"
        type: string
        required: true
      bump_type:
        description: Which component of version to bump on develop branch (MAJOR.MINOR.PATCH)
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: "minor"
      dry_run:
        description: "Test run that will only print git diff and all changes being made"
        required: true
        type: boolean

env:
  CARGO_TERM_COLOR: always
  GIT_USER: NYM CI
  GIT_EMAIL: ci@nymtech.net

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push-release-branch:
    name: Push release branch
    runs-on: arc-linux-latest
    outputs:
      major: ${{ steps.next_version.outputs.major }}
      minor: ${{ steps.next_version.outputs.minor }}
      patch: ${{ steps.next_version.outputs.patch }}
    steps:
      - name: Validate input
        env:
          RELEASE_NAME: ${{ inputs.release_name }}
        run: |
          if ! echo "$RELEASE_NAME" | grep -Pq '^[a-z]+$'; then
            echo "::error:: Invalid release name format (expected lowercase letters only)"
            exit 2
          fi

      - name: Configure git
        run: |
          git config --global user.name "${{ env.GIT_USER }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          ref: develop
          ssh-key: ${{ secrets.CI_RELEASE_DEPLOY_KEY }}

      - name: Setup sccache
        uses: ./.github/actions/setup-sccache

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install cargo-get
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-get

      - name: Compute next version for develop branch
        id: next_version
        working-directory: nym-vpn-core
        env:
          RELEASE_NAME: ${{ inputs.release_name }}
        run: |
          MAJOR=$(cargo get workspace.package.version --major)
          MINOR=$(cargo get workspace.package.version --minor)
          PATCH=$(cargo get workspace.package.version --patch)

          # Omit patch if zero to keep release branch shorter (release/2026.10-name)
          RELEASE_BRANCH_NAME="release/$MAJOR.$MINOR"
          if [ "$PATCH" -ne 0 ]; then
            RELEASE_BRANCH_NAME="${RELEASE_BRANCH_NAME}.${PATCH}"
          fi
          RELEASE_BRANCH_NAME="$RELEASE_BRANCH_NAME-$RELEASE_NAME"

          case "${{ inputs.bump_type }}" in
            major)
              MAJOR=$((MAJOR+1))
              MINOR=1
              PATCH=0
            ;;
            minor)
              MINOR=$(($MINOR+1))
              ;;
            patch)
              PATCH=$(($PATCH+1))
            ;;
          esac

          echo "major=$MAJOR" >> "$GITHUB_OUTPUT"
          echo "minor=$MINOR" >> "$GITHUB_OUTPUT"
          echo "patch=$PATCH" >> "$GITHUB_OUTPUT"
          echo "release_branch=$RELEASE_BRANCH_NAME" >> "$GITHUB_OUTPUT"

      - name: Create release branch
        env:
          RELEASE_BRANCH: ${{ steps.next_version.outputs.release_branch }}
        run: |
          # match any i.e `yyyy.xx-*`
          HEAD_COUNT=$(git ls-remote --heads origin 'refs/heads/release/${{ env.RELEASE_BRANCH }}-*' | wc -l | tr -d ' ')

          if [ "$HEAD_COUNT" -eq "0" ]; then
            # create release branch and push it to remote
            git checkout -b "${{ env.RELEASE_BRANCH }}"
            echo "::notice:: Created release branch: ${{ env.RELEASE_BRANCH }}"
            if [ '${{ inputs.dry_run }}' == 'true' ]; then
              echo "::warning:: Dry run, skipping push to origin/${{ env.RELEASE_BRANCH }}"
            else
              git push origin "${{ env.RELEASE_BRANCH }}"
            fi
          else
            echo "::error:: '${{ env.RELEASE_BRANCH }}-*' branch already exists but it must not!"
            exit 1
          fi

  bump-develop:
    name: Create PR updating version in develop branch
    uses: ./.github/workflows/bump-all-platforms.yml
    needs: push-release-branch
    permissions:
      contents: write
      pull-requests: write
    with:
      branch: develop
      major: ${{ needs.push-release-branch.outputs.major }}
      minor: ${{ needs.push-release-branch.outputs.minor }}
      patch: ${{ needs.push-release-branch.outputs.patch }}
      release_kind: beta
      pre_release_ident: 1
      update_linux_installer: false
      update_changelog: true
      dry_run: ${{ inputs.dry_run }}
