name: distribute-release

on:
  workflow_call:
    inputs:
      publish_play:
        description: Publish to Play Store
        type: boolean
        required: true
      publish_play_metadata:
        description: Publish Play Store metadata
        type: boolean
        required: true
      publish_testflight:
        description: Publish to TestFlight
        type: boolean
        required: true
      publish_to_public_testflight:
        description: Publish to public TestFlight group
        type: boolean
        required: true
    secrets:
      ANDROID_SERVICE_ACCOUNT_JSON:
        required: true
      APP_STORE_CONNECT_API_KEY:
        required: true
      APP_STORE_CONNECT_API_ISSUER_ID:
        required: true
      APP_STORE_CONNECT_API_PRIVATE_KEY:
        required: true
env:
  CARGO_TERM_COLOR: always
  UPLOAD_DIR_IOS: ios_artifacts

jobs:
  publish-playstore:
    name: Publish to Google Play
    if: ${{ inputs.publish_play }}
    uses: ./.github/workflows/publish-nym-vpn-android.yml
    with:
      track: alpha
      publish-bundle: true
      publish-metadata: ${{ inputs.publish_play_metadata }}
    secrets: inherit

  publish-testflight:
    name: Publish to TestFlight
    if: ${{ inputs.publish_testflight }}
    uses: ./.github/workflows/publish-nym-vpn-ios.yml
    with:
      is_public: ${{ inputs.publish_to_public_testflight }}
    secrets: inherit

  handle-testflight-failures:
    needs: [publish-testflight]
    name: Handle TestFlight failures
    runs-on: arc-linux-latest
    if: needs.publish-testflight.result == 'failure'
    steps:
      - name: Print failure message
        run: |
          echo "::warning:: Failed to publish to TestFlight!"

  handle-playstore-failures:
    needs: [publish-playstore]
    runs-on: arc-linux-latest
    name: Handle Play Store failures
    if: needs.publish-playstore.result == 'failure'
    steps:
      - name: Print failure message
        run: |
          echo "::warning:: Failed to publish to Google Play!"
