name: find-stale-branches

on:
  workflow_dispatch:

permissions:
  issues: read
  contents: read

jobs:
  stale_branches:
    runs-on: arc-linux-latest-dind
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v8.2.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          days-before-stale: 120
          days-before-delete: 180
          pr-check: false
          dry-run: true
