name: generate-build-info-nym-vpn-app
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build-profile:
        description: "Rust build profile"
        required: true
        default: Release
        type: string
      rust-version:
        description: "Rust version"
        required: true
        type: string

jobs:
  generate-build-info-nym-vpn-app:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Get current date
        id: date
        run:
          echo "date=$(date)" >> $GITHUB_OUTPUT

      - name: Generate build-info
        run: |
          touch build-info.txt
          echo "App name:      $(yq -oy '.productName' nym-vpn-app/src-tauri/tauri.conf.json)" >> build-info.txt
          echo "Version:       $(yq -oy '.package.version' nym-vpn-app/src-tauri/Cargo.toml)" >> build-info.txt
          echo "Tauri version: $(yq -ptoml -oy '.package[] | select(.name == "tauri") | .version' nym-vpn-app/src-tauri/Cargo.lock)" >> build-info.txt
          echo "Rustc version: ${{ inputs.rust-version}}" >> build-info.txt
          echo "Build profile: ${{ inputs.build-profile}}" >> build-info.txt
          echo "Date:          ${{ steps.date.outputs.date }}" >> build-info.txt
          cat build-info.txt

      - name: Upload build-info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info.txt
          retention-days: 1
