name: nightly-release

on:
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release-nightly:
    name: Publish nightly release
    uses: ./.github/workflows/release-all-platforms.yml
    with:
      gh_release: auto
      release_channel: nightly
      android: false
      fdroid: true
      linux: true
      windows: true
      ios: true
      macos: true
      publish-metadata: false
