name: publish-nym-vpn-android

on:
  workflow_call:
    inputs:
      track:
        type: string
        default: "none"
      release_type:
        type: string
        default: "release"
      publish-bundle:
        type: boolean
        default: false
        description: "Publish the app bundle"
      publish-metadata:
        description: "Publish app metadata"
        type: boolean
        default: true

env:
  UPLOAD_DIR_ANDROID: android_artifacts_play
  RELEASE_NOTES: ""

jobs:
  publish-play:
    runs-on: arc-linux-latest
    env:
      # SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
      # SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
      # SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
      # KEY_STORE_FILE: "android_keystore.jks"
      # KEY_STORE_LOCATION: ${{ github.workspace }}/nym-vpn-android/app/keystore/
      RUBYOPT: "-rresolv-replace"
      BUNDLE_TIMEOUT: "120"
    steps:
      - uses: actions/checkout@v7

      - name: Dotenv Action
        uses: xom9ikk/dotenv@v2.4.0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      # - name: Set up JDK 21
      #   uses: actions/setup-java@v5
      #   with:
      #     distribution: "temurin"
      #     java-version: "21"
      #     cache: gradle

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v4

      # - name: Setup NDK
      #   uses: nttld/setup-ndk@v1
      #   id: setup-ndk
      #   with:
      #     ndk-version: ${{ env.NDK_VERSION }}
      #     add-to-path: false

      # - name: Set env
      #   shell: bash
      #   run: |
      #     echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
      #     echo "NDK_TOOLCHAIN_DIR=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

      # - name: Decode Keystore
      #   id: decode_keystore
      #   uses: timheuer/base64-to-file@v2.0
      #   with:
      #     fileName: ${{ env.KEY_STORE_FILE }}
      #     fileDir: ${{ env.KEY_STORE_LOCATION }}
      #     encodedString: ${{ secrets.ANDROID_KEYSTORE }}

      # - name: Create keystore path env var
      #   run: |
      #     store_path=${{ env.KEY_STORE_LOCATION }}${{ env.KEY_STORE_FILE }}
      #     echo "KEY_STORE_PATH=$store_path" >> $GITHUB_ENV

      # - name: Create service_account.json
      #   id: createServiceAccount
      #   run: echo '${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Get version code
        uses: ./.github/workflows/android/get-version-code

      - name: Install fastlane
        working-directory: nym-vpn-android
        run: bundle install

      - name: Download Android artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.UPLOAD_DIR_ANDROID }}
          path: dist

      - name: Find artifact file
        id: find_artifact
        run: |
          ARTIFACT_FILE=$(find "dist/" -name '*.aab' -type f | head -1)
          if [ -z "$ARTIFACT_FILE" ]; then
            echo "::error:: Failed to locate aab artifact"
            exit 1
          fi
          echo "artifact_file=$ARTIFACT_FILE" >> $GITHUB_ENV
          echo "::notice:: Found artifact for upload: $ARTIFACT_FILE"

      - name: Distribute app to fastlane track ${{ inputs.track }} 🚀
        working-directory: nym-vpn-android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
            bundle exec fastlane supply --aab "${{ steps.find_artifact.outputs.artifact_file }}" \
              --track ${{ inputs.track }} \
              --skip_upload_aab ${{ github.event.inputs.publish-bundle == 'true' }} \
              --skip_metadata ${{ inputs.publish-metadata }}
