name: publish-nym-vpn-android

on:
  workflow_call:
    inputs:
      track:
        type: string
        default: "none"
      publish_bundle:
        type: boolean
        default: false
        description: "Publish the app bundle"
      publish_metadata:
        description: "Publish app metadata"
        type: boolean
        default: true
      play_artifact_name:
        description: "The name of the Play Store artifact (aab)"
        type: string
        required: false
        default: ""
    secrets:
      ANDROID_SERVICE_ACCOUNT_JSON:
        required: true

env:
  UPLOAD_DIR_ANDROID: android_artifacts_play
  RELEASE_NOTES: ""

jobs:
  publish-play:
    runs-on: arc-linux-latest
    timeout-minutes: 30
    env:
      RUBYOPT: "-rresolv-replace"
      BUNDLE_TIMEOUT: "120"
    steps:
      - uses: actions/checkout@v7

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Create service_account.json
        id: createServiceAccount
        working-directory: nym-vpn-android
        run: echo '${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Install fastlane
        working-directory: nym-vpn-android
        run: bundle install

      - name: Set locale (for Fastlane)
        run: |
          echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Download Android artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.UPLOAD_DIR_ANDROID }}

      - name: Distribute app to fastlane track ${{ inputs.track }} 🚀
        env:
          FASTLANE_OPT_OUT_USAGE: "YES"
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ARTIFACT_FILE: ${{ inputs.play_artifact_name }}
          TRACK: ${{ inputs.track }}
          SKIP_UPLOAD_BUNDLE: ${{ !inputs.publish_bundle }}
          SKIP_UPLOAD_METADATA: ${{ !inputs.publish_metadata }}
        run: |
          if [ -z "$ARTIFACT_FILE" ]; then
            echo "::error:: No artifact file specified!"
            exit 1
          fi

          echo "🚀 Uploading to Google Play Store... (track=$TRACK, skip_bundle=$SKIP_UPLOAD_BUNDLE, skip_metadata=$SKIP_UPLOAD_METADATA)"

          bundle exec fastlane supply --aab "$ARTIFACT_FILE" \
            --track "$TRACK" \
            --skip-upload-aab $SKIP_UPLOAD_BUNDLE \
            --skip-upload-metadata $SKIP_UPLOAD_METADATA
