# Create a new release of the Linux installer script

name: release-linux-installer
on:
  workflow_dispatch:
    inputs:
      client_tag:
        description: "Tag name of the client release"
        required: true
        default: nym-vpn-x-v0.1.0
      client_version:
        description: "Version of the client"
        required: true
        default: 0.1.0
      daemon_tag:
        description: "Tag name of the daemon release"
        required: true
        default: nym-vpn-core-v0.1.0
      daemon_version:
        description: "Version of the daemon"
        required: true
        default: 0.1.0
      create_release:
        description: "Publish a new release of the installer"
        type: boolean
        required: false
        default: false

jobs:
  release-installer:
    name: Release Linux installer
    runs-on: ubuntu-latest
    env:
      VPNX_TAG: ${{ inputs.client_tag }}
      VPNX_VERSION: ${{ inputs.client_version }}
      VPND_TAG: ${{ inputs.daemon_tag }}
      VPND_VERSION: ${{ inputs.daemon_version }}
      INSTALLER: .pkg/installer.sh
      RELEASE_TAG: linux-install-${{ inputs.client_version }}
      RELEASE_NOTES: release-notes.md
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump installer script
        run: |
          sed -i "s/^vpnx_tag=.*/vpnx_tag=${{ inputs.client_tag }}/" $INSTALLER
          sed -i "s/^vpnd_tag=.*/vpnd_tag=${{ inputs.daemon_tag }}/" $INSTALLER
          sed -i "s/^vpnx_version=.*/vpnx_version=${{ inputs.client_version }}/" $INSTALLER
          sed -i "s/^vpnd_version=.*/vpnd_version=${{ inputs.daemon_version }}/" $INSTALLER
          mv $INSTALLER install.sh
      - name: Show installer script
        run: cat install.sh
      - name: Release notes
        run: |
          echo "## NymVPN Linux installer

          The script installs the following components
          - nym-vpnd \`${{ env.VPND_VERSION }}\` (VPN daemon)
          - nymvpn-x \`${{ env.VPNX_VERSION }}\` (VPN client app)

          \`\`\`
          curl -fsSL https://github.com/nymtech/nym-vpn-client/releases/download/${{ env.RELEASE_TAG }}/install.sh | bash
          \`\`\`

          #### To uninstall

          \`\`\`
          curl -fsSL https://github.com/nymtech/nym-vpn-client/releases/download/${{ env.RELEASE_TAG }}/install.sh | bash -s uninstall
          \`\`\`
          " > ${{ env.RELEASE_NOTES }}
          cat ${{ env.RELEASE_NOTES }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: inputs.create_release == true
        with:
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          body_path: ${{ env.RELEASE_NOTES }}
          files: install.sh

