name: tauri-post-release
on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true
      version:
        type: string
        required: true
      core_release_tag:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      release_tag:
        description: "App release tag"
        type: string
        required: true
        default: "nym-vpn-app-v1.2.3"
      version:
        description: "Semver app version"
        type: string
        required: true
        default: "1.2.3"
      core_release_tag:
        description: "vpn-core release tag"
        type: string
        required: true
        default: "nym-vpn-core-v1.2.3"

jobs:
  post-release:
    runs-on: arc-linux-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 1
          ref: "develop"

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Set release date
        # current date in YYYY-MM-DD format
        run: |
          date=$(date -u +'%Y-%m-%d')
          echo "release date: $date"
          echo "RELEASE_DATE=$date" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        working-directory: nym-vpn-app
        run: |
          new_entry="## [${{ inputs.version }}] - ${{ env.RELEASE_DATE }}"
          sed -i "s|^## \[Unreleased\]|## [Unreleased]\n\n$new_entry|" CHANGELOG.md
          cat CHANGELOG.md

      - name: Bump installer script
        working-directory: .pkg/linux
        env:
          APP_TAG: ${{ inputs.release_tag }}
          CORE_TAG: ${{ inputs.core_release_tag }}
        run: |
          ./bump.sh

      - name: Update flatpak metainfo
        working-directory: nym-vpn-app/.pkg/flatpak
        env:
          METAINFO_XML: net.nymtech.NymVPN.metainfo.xml
          VERSION: ${{ inputs.version }}
          RELEASE_TAG: ${{ inputs.release_tag }}
          RELEASE_DATE: ${{ env.RELEASE_DATE }}
        run: |
          ./update_metainfo.sh

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          GIT_BRANCH: "tauri_postrel_${{ inputs.version }}"
          COMMIT_MSG: "tauri: post release v${{ inputs.version }}"
          PR_BODY: |
            - update CHANGELOG.md
            - bump Linux installer script
            - update flatpak package metainfo.xml
        run: |
          git config --global user.name "NYM_bot"
          git config --global user.email "_@_"
          git switch -C ${{ env.GIT_BRANCH }}
          git add nym-vpn-app/CHANGELOG.md
          git add .pkg/linux
          git add nym-vpn-app/.pkg/flatpak
          git commit -m "${{ env.COMMIT_MSG }}"
          git push --force origin ${{ env.GIT_BRANCH }}
          existing=$(gh pr list --head "${{ env.GIT_BRANCH }}" --json number --jq 'length')
          if [[ "$existing" == "0" ]]; then
            gh pr create --title '${{ env.COMMIT_MSG }}' --body '${{ env.PR_BODY }}' --base develop --reviewer "agentpietrucha"
          else
            echo "PR already exists for branch ${{ env.GIT_BRANCH }}, skipping"
          fi
